import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import {createClient} from 'jsr:@supabase/supabase-js@2';
import {discoverCompaniesByName,companyNameJson} from '../_shared/company-name-discovery.ts';
import {familyStableId} from '../_shared/family-discovery.ts';
import {persistSourceEvidence} from '../_shared/source-evidence.ts';
const H={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const reply=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
const uuid=(s:unknown)=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s);
const PROXY='https://valora-proxy-git-max-v1-contatoguilhermegsantos-6547s-projects.vercel.app/api/source/base-empresarial';
function fallback(auth:string){if((Deno.env.get('BASE_EMPRESARIAL_PROXY_URL')||PROXY)!==PROXY)return undefined;return async(path:string,timeoutMs:number)=>{const p=new URL(path,'https://app.baseempresarial.com.br/api/v1');if(p.pathname!=='/companies/search')return {ok:false,status:400,data:null,error:'UNSUPPORTED_OPERATION'};const body={operation:'companies_search',corporate_name:p.searchParams.get('corporate_name')||undefined,trade_name:p.searchParams.get('trade_name')||undefined,page:1,per_page:20,timeout_ms:Math.max(1000,timeoutMs-500)};try{const r=await fetch(PROXY,{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});if(!r.ok){const h=r.headers.get('Retry-After')||'60';await r.body?.cancel();return {ok:false,status:r.status,data:null,error:'HTTP_'+r.status,retry_after_seconds:r.status===429?(/^\d+$/.test(h)?Number(h):Math.max(1,(Date.parse(h)-Date.now())/1000)||60):undefined}}return {ok:true,status:r.status,data:await companyNameJson(r),error:null}}catch(e){return {ok:false,status:null,data:null,error:e instanceof Error&&['AbortError','TimeoutError'].includes(e.name)?'TIMEOUT':'NETWORK_ERROR'}}}}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return reply({ok:true});if(req.method!=='POST')return reply({error:'POST required'},405);const auth=req.headers.get('Authorization');if(!auth)return reply({error:'Unauthorized'},401);
 try{const url=Deno.env.get('SUPABASE_URL')!,admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),client=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const session=await client.auth.getUser(),user=session.data?.user;if(session.error||!user)return reply({error:'Unauthorized'},401);
 const raw=await req.json().catch(()=>null);if(!raw||Array.isArray(raw)||typeof raw!=='object'||!uuid(raw.lead_id)||raw.research_run_id&&!uuid(raw.research_run_id)||Object.keys(raw).some(k=>!['lead_id','research_run_id'].includes(k)))return reply({error:'Valid lead and research run required'},400);
 const p=await admin.from('profiles').select('active_organization_id').eq('id',user.id).maybeSingle();if(p.error)throw Error('Profile');const org=p.data?.active_organization_id;if(!org)return reply({error:'No active organization'},409);const m=await admin.from('organization_members').select('role,status').eq('organization_id',org).eq('user_id',user.id).maybeSingle();if(m.error)throw Error('Membership');if(m.data?.status!=='ACTIVE'||!['OWNER','ADMIN','ANALYST','MEMBER'].includes(m.data.role))return reply({error:'Operator access required'},403);
 const [l,s]=await Promise.all([admin.from('leads').select('id,kind,name,city,state').eq('id',raw.lead_id).eq('organization_id',org).maybeSingle(),admin.from('source_registry').select('id,connection_status').eq('key','base_empresarial_rfb').maybeSingle()]);if(l.error||s.error)throw Error('Context');if(!l.data)return reply({error:'Lead not found'},404);if(l.data.kind!=='COMPANY')return reply({error:'Business name discovery requires a company lead'},409);if(raw.research_run_id){const run=await admin.from('research_runs').select('id').eq('id',raw.research_run_id).eq('lead_id',raw.lead_id).eq('organization_id',org).maybeSingle();if(run.error)throw Error('Run');if(!run.data)return reply({error:'Research run not found'},404)}
 if(!s.data||!['CONNECTED','CONNECTED_LIMITED'].includes(s.data.connection_status))return reply({ok:true,status:'BLOCKED',complete:false,candidates_found:0,candidates:[],note:'Fonte cadastral indisponível para descoberta empresarial.'});
 const started=Date.now(),result=await discoverCompaniesByName(l.data,{fallback:fallback(auth)}),candidates:any[]=[];let reviewRequired=false;
 for(const match of result.candidates){const id=await familyStableId(`company-name|${org}|${raw.lead_id}|${match.full_cnpj}`),reason=`O nome informado corresponde por prefixo à razão social ou nome fantasia de ${match.company_name}, CNPJ ${match.full_cnpj}. A marca ou semelhança do nome não confirma a entidade jurídica deste lead.`,document=await persistSourceEvidence(admin,{organization_id:org,lead_id:raw.lead_id,source_registry_id:s.data.id,title:'Candidato empresarial por nome — '+match.company_name,source_label:'Base Empresarial / cadastro público CNPJ-RFB',source_url:match.source_url,source_kind:'AGGREGATOR',document_type:'CNPJ_REGISTRY',publisher:'Base Empresarial',source_date:null,retrieved_at:new Date().toISOString(),dedupe_key:`${raw.lead_id}:company-name:${id}`,reliability_weight:0.75,raw_reference:JSON.stringify(match),excerpt:`Razão social ${match.company_name}; nome fantasia ${match.trade_name||'não informado'}; CNPJ ${match.full_cnpj}; município/UF do estabelecimento ${match.city||'não informado'}/${match.state||'não informado'}; CNAE ${match.cnae_code||'não informado'} — ${match.cnae_description||'não informado'}. Correspondência por ${match.match_bases.join(', ')}. Não comprova identidade do lead, titularidade de marca, vínculo de pessoa, parentesco ou posição financeira.`,verification_status:'VERIFIED',last_verified_at:new Date().toISOString(),usage_scope:'INTERNAL',created_by:user.id});if(document.error||!document.data)throw Error('Evidence');if(document.data.verification_status!=='VERIFIED'){reviewRequired=true;continue}
 const metadata={...match,evidence_id:document.data.id,source_key:'base_empresarial_rfb',search_lineage:result.search_lineage};const inserted=await admin.from('candidate_entities').upsert({id,organization_id:org,lead_id:raw.lead_id,research_run_id:raw.research_run_id||null,entity_type:'COMPANY',candidate_type:'RFB_COMPANY_NAME_MATCH',label:match.company_name,candidate_reason:reason,confidence:'LOW',validation_status:'UNVALIDATED',metadata,created_by:user.id},{onConflict:'id',ignoreDuplicates:true});if(inserted.error)throw Error('Candidate');const actual=await admin.from('candidate_entities').select('*').eq('id',id).eq('organization_id',org).eq('lead_id',raw.lead_id).maybeSingle();if(actual.error||!actual.data)throw Error('Candidate readback');if(actual.data.candidate_type!=='RFB_COMPANY_NAME_MATCH'||actual.data.metadata?.full_cnpj!==match.full_cnpj)throw Error('Candidate scope');if(actual.data.validation_status==='REJECTED')continue;
 const bound=await admin.from('evidence').select('id,verification_status,source_registry_id').eq('id',actual.data.metadata.evidence_id).eq('organization_id',org).eq('lead_id',raw.lead_id).maybeSingle();if(bound.error)throw Error('Bound evidence');if(!bound.data||bound.data.verification_status!=='VERIFIED'||bound.data.source_registry_id!==s.data.id){reviewRequired=true;continue}
 candidates.push({candidate_id:id,evidence_id:actual.data.metadata.evidence_id,confidence:actual.data.confidence,validation_status:actual.data.validation_status,...actual.data.metadata});
 }
 const attempts=result.search_lineage.source_attempts,last=attempts.at(-1),status=reviewRequired?'PARTIAL':result.status;const log=await admin.from('source_fetch_logs').insert({organization_id:org,research_run_id:raw.research_run_id||null,source_registry_id:s.data.id,endpoint_reference:'Base companies/search corporate_name and trade_name prefixes',success:attempts.some(a=>a.status===200&&!a.error),http_status:last?.status||null,result_status:'COMPANY_NAME_'+status,duration_ms:Date.now()-started,created_by:user.id});if(log.error)throw Error('Log');return reply({ok:result.ok,status,complete:result.complete&&!reviewRequired,query_name:result.search_lineage.query_name,candidates_found:candidates.length,candidates,search_lineage:result.search_lineage,notes:result.notes,retry_after_seconds:result.retry_after_seconds,review_required:reviewRequired,caveat:'Selecione e confirme o CNPJ do estabelecimento correto. O nome ou a marca não confirma identidade empresarial.'},status==='FAILED'?502:200);
 }catch{return reply({error:'Não foi possível concluir ou registrar a descoberta empresarial.',status:'FAILED',complete:false},500)}
});
