import {familyNetworkText} from './family-network-text.ts';
export const companyNameNorm=(v:unknown)=>familyNetworkText(v,300).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
export function isValidCompanyCnpj(value:unknown){const c=String(value??'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(!/^[A-Z0-9]{12}\d{2}$/.test(c)||/^(\d)\1{13}$/.test(c))return false;const digit=(text:string,w:number[])=>{const r=[...text].reduce((s,ch,i)=>s+(ch.charCodeAt(0)-48)*w[i],0)%11;return r<2?0:11-r};const d=digit(c.slice(0,12),[5,4,3,2,9,8,7,6,5,4,3,2]);return d===Number(c[12])&&digit(c.slice(0,12)+d,[6,5,4,3,2,9,8,7,6,5,4,3,2])===Number(c[13])}
type Read={ok:boolean;status:number|null;data:any;error:string|null;retry_after_seconds?:number};
type Options={fetcher?:typeof fetch;clock?:()=>number;deadlineMs?:number;fallback?:(path:string,timeoutMs:number)=>Promise<Read>};
export type CompanyNameMatch={full_cnpj:string;basic_cnpj:string;company_name:string;trade_name:string;city:string;state:string;cnae_code:string;cnae_description:string;registration_status:string;match_basis:string;match_bases:string[];exact_name_match:boolean;city_match:boolean;state_match:boolean;source_url:string;identity_confirmed:false;kinship_confirmed:false};
export async function companyNameJson(response:Response){const reader=response.body?.getReader();if(!reader)throw Error('INVALID_RESPONSE');const chunks:Uint8Array[]=[];let n=0;try{for(;;){const r=await reader.read();if(r.done)break;n+=r.value.byteLength;if(n>1024*1024)throw Error('RESPONSE_TOO_LARGE');chunks.push(r.value)}}catch(e){await reader.cancel().catch(()=>{});throw e}finally{reader.releaseLock()}const bytes=new Uint8Array(n);let at=0;for(const part of chunks){bytes.set(part,at);at+=part.length}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}
export async function discoverCompaniesByName(lead:{name?:string;city?:string;state?:string},options:Options={}){
 const clock=options.clock||Date.now,started=clock(),deadline=started+Math.min(45000,Math.max(1,options.deadlineMs||30000)),fetcher=options.fetcher||fetch;
 const original=familyNetworkText(lead.name,180),query=companyNameNorm(original),attempts:any[]=[],notes:string[]=[],found=new Map<string,CompanyNameMatch>();let incomplete=false,successful=0,retryAfter=0;
 const lineage={original:{name:original,city:familyNetworkText(lead.city,120)||null,state:familyNetworkText(lead.state,2)||null},query_name:query,query_fields:['corporate_name','trade_name'],match_mode:'PREFIX',geographic_filter_applied:false,identity_confirmed:false,kinship_confirmed:false,source_provider:'BASE_EMPRESARIAL',source_key:'base_empresarial_rfb',source_attempts:attempts,limits:{queries:2,rows_per_query:20,candidates:30},coverage:'Duas consultas cadastrais por prefixo de razão social e nome fantasia; confirmação do CNPJ pelo usuário é obrigatória.'};
 if(query.length<3||/\[identificador removido\]|[*#]|REDACTED/i.test(original))return {ok:true,status:'BLOCKED',complete:false,candidates:[],notes:['BUSINESS_NAME_REQUIRED'],search_lineage:lineage};
 async function read(path:string,field:string){let r:Read;const begin=clock();try{const resp=await fetcher('https://app.baseempresarial.com.br/api/v1'+path,{headers:{Accept:'application/json','User-Agent':'MAX-Intelligence/1.0'},redirect:'error',signal:AbortSignal.timeout(Math.max(1,Math.min(4000,deadline-clock()-100)))});if(resp.status===429){const h=resp.headers.get('Retry-After')||'60';retryAfter=Math.max(retryAfter,/^\d+$/.test(h)?Number(h):Math.max(1,(Date.parse(h)-clock())/1000)||60)}if(!resp.ok){await resp.body?.cancel();r={ok:false,status:resp.status,data:null,error:'HTTP_'+resp.status}}else{const data=await companyNameJson(resp);r={ok:true,status:resp.status,data,error:null}}}catch(e){const err=e as Error;r={ok:false,status:null,data:null,error:['TimeoutError','AbortError'].includes(err.name)?'TIMEOUT':['INVALID_RESPONSE','RESPONSE_TOO_LARGE'].includes(err.message)?err.message:err instanceof SyntaxError?'INVALID_RESPONSE':'NETWORK_ERROR'}}
  attempts.push({provider:'BASE_EMPRESARIAL',transport:'DIRECT',endpoint:'/companies/search',field,status:r.status,error:r.error,duration_ms:Math.max(0,clock()-begin)});
  if(!r.ok&&options.fallback&&['TIMEOUT','NETWORK_ERROR','HTTP_502','HTTP_503','HTTP_504'].includes(r.error||'')&&clock()+1000<deadline){const t=clock();try{r=await options.fallback(path,Math.min(13000,deadline-clock()-100))}catch{r={ok:false,status:null,data:null,error:'NETWORK_ERROR'}}retryAfter=Math.max(retryAfter,r.retry_after_seconds||0);attempts.push({provider:'BASE_EMPRESARIAL',transport:'OWNED_BRIDGE',endpoint:'/companies/search',field,status:r.status,error:r.error,duration_ms:Math.max(0,clock()-t)})}return r;
 }
 await Promise.all(['corporate_name','trade_name'].map(async field=>{if(clock()+300>=deadline){incomplete=true;notes.push('DEADLINE');return}const params=new URLSearchParams({[field]:original,page:'1',per_page:'20',sort:'id'}),r=await read('/companies/search?'+params,field);if(!r.ok){incomplete=true;notes.push(r.error||'QUERY_FAILED');return}const d=r.data;if(!Array.isArray(d?.data)||d.data.length>20){incomplete=true;notes.push('INVALID_RESPONSE');return}successful++;if(typeof d.meta?.has_more!=='boolean'||d.meta.has_more){incomplete=true;notes.push(typeof d.meta?.has_more==='boolean'?'PAGE_LIMIT_20':'PAGINATION_UNKNOWN')}
  for(const raw of d.data){const full=String(raw?.full_cnpj??'').toUpperCase().replace(/[^A-Z0-9]/g,''),company=familyNetworkText(raw?.corporate_name,255),trade=familyNetworkText(raw?.trade_name,255),value=field==='corporate_name'?company:trade,city=familyNetworkText(raw?.city_name,120),state=familyNetworkText(raw?.state_abbreviation,2).toUpperCase();if(!isValidCompanyCnpj(full)||!company||!value||!companyNameNorm(value).startsWith(query)){incomplete=true;notes.push('INVALID_OR_NONMATCHING_COMPANY_ROW');continue}const basis=field==='corporate_name'?'CORPORATE_NAME_PREFIX':'TRADE_NAME_PREFIX',prior=found.get(full);if(prior){if(!prior.match_bases.includes(basis))prior.match_bases.push(basis);prior.exact_name_match=prior.exact_name_match||companyNameNorm(value)===query;continue}if(found.size>=30){incomplete=true;notes.push('CANDIDATE_LIMIT_30');continue}found.set(full,{full_cnpj:full,basic_cnpj:full.slice(0,8),company_name:company,trade_name:trade,city,state,cnae_code:String(raw?.main_cnae??'').replace(/\D/g,'').slice(0,7),cnae_description:familyNetworkText(raw?.main_cnae_name),registration_status:familyNetworkText(String(raw?.registration_status??''),40),match_basis:basis,match_bases:[basis],exact_name_match:companyNameNorm(value)===query,city_match:Boolean(lead.city&&companyNameNorm(city)===companyNameNorm(lead.city)),state_match:Boolean(lead.state&&state===String(lead.state).toUpperCase()),source_url:'https://baseempresarial.com.br/empresa/'+full,identity_confirmed:false,kinship_confirmed:false})}
 }));
 return {ok:successful>0,status:!successful?'FAILED':incomplete?'PARTIAL':'COMPLETED',complete:successful===2&&!incomplete,candidates:[...found.values()].sort((a,b)=>Number(b.city_match)-Number(a.city_match)||Number(b.state_match)-Number(a.state_match)||Number(b.exact_name_match)-Number(a.exact_name_match)||a.full_cnpj.localeCompare(b.full_cnpj)),notes:[...new Set(notes)],retry_after_seconds:retryAfter||null,search_lineage:lineage};
}
