import {familyNorm, familyStableId, familyQueryFingerprint} from './family-discovery.ts';
import type {FamilyContext} from './family-discovery.ts';
import {familyNetworkText} from './family-network-text.ts';

const MINHA='https://minhareceita.org';
const BASE='https://app.baseempresarial.com.br/api/v1';
const IBGE='https://servicodados.ibge.gov.br/api/v1/localidades';
const MAX={index:3000,indexBytes:2000000,companies:120,people:160,edges:400,partners:100,pages:8,details:8,inverse:2,depth:3,weakCompanies:30};
type Provider='MINHA_RECEITA'|'BASE_EMPRESARIAL';
type Seed={candidate_id:string;full_cnpj:string;company_name:string;city:string;state:string;person_name?:string;match_basis?:string};
export type NetworkNode={key:string;type:'ROOT'|'COMPANY'|'PERSON_CITATION';label:string;full_cnpj?:string;person_name?:string;city?:string;state?:string;cnae_code?:string;cnae_description?:string;trade_name?:string;registration_status?:string;depth:number;candidate_id?:string;observation_key?:string;identity_confirmed:false;kinship_confirmed:false};
export type NetworkEdge={id:string;from:string;to:string;kind:'QSA_PARTICIPATION'|'SAME_NAME_CANDIDATE'|'SURNAME_CONTEXT_CANDIDATE'|'ROOT_CONTEXT_CANDIDATE';observation_key:string;match_basis:string;role?:string;confidence:'LOW';validation_status:'UNVALIDATED';identity_confirmed:false;kinship_confirmed:false};
export type NetworkObservation={key:string;provider:Provider;source_url:string;full_cnpj:string;company_name:string;city:string;state:string;cnae_code:string;cnae_description:string;trade_name?:string;registration_status?:string;people:Array<{name:string;role:string}>;queried_at:string;qsa_complete:boolean};
type DetailTask={full_cnpj?:string;basic_cnpj?:string;depth:number;origin_key:string;attempts:number};
type InverseTask={name:string;origin_key:string;depth:number;page:number;done:boolean;attempts:number};
export type NetworkState={version:1;query_fingerprint:string;city_code:string|null;municipal_started:boolean;municipal_cursor:string|null;municipal_exhausted:boolean;pagination_stalled:boolean;cursor_checkpoint:string[];municipal_index:NetworkObservation[];nodes:NetworkNode[];edges:NetworkEdge[];observations:NetworkObservation[];detail_queue:DetailTask[];processed_details:string[];inverse_queries:InverseTask[];cooldowns:Partial<Record<Provider,string>>;retry_not_before:string|null;pages_scanned:number;scanned_count:number;limits_reached:string[];coverage_errors:string[]};
type Options={fetcher?:typeof fetch;clock?:()=>number;deadlineMs?:number;baseAvailable?:boolean;minhaAvailable?:boolean;excludedCnpjs?:string[];excludedNodeKeys?:string[]};
const txt=(v:unknown,n=255)=>familyNetworkText(v,n);
const cnpj=(v:unknown)=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const isCnpj=(v:string)=>/^[A-Z0-9]{12}\d{2}$/.test(v);
const isRoot=(v:string)=>/^[A-Z0-9]{8}$/.test(v);
const cnae=(v:unknown)=>{const digits=String(v??'').replace(/\D/g,'');return digits&&digits.length<=7?digits.padStart(7,'0'):''};
const usefulName=(v:unknown)=>{const name=txt(v);return name&&!/[*#]|REDACTED|OCULTAD|SUPRIMID|ANONIMIZAD|\[identificador removido\]/i.test(name)&&familyNorm(name).split(' ').filter(t=>t&&!['DA','DE','DO','DAS','DOS','E'].includes(t)).length>=2?name:null};
const personKey=(full:string,name:string)=>'person:'+full+':'+familyNorm(name);
const companyKey=(full:string)=>'company:'+full;
const observeKey=(provider:Provider,full:string)=>provider+':'+full;
const flags={identity_confirmed:false as const,kinship_confirmed:false as const};
const fullNameIn=(label:string,name:string)=>(' '+familyNorm(label)+' ').includes(' '+familyNorm(name)+' ');
const hasToken=(label:string,token:string)=>familyNorm(label).split(' ').includes(token);
// These are tokens of a cited name, not a conclusion about which tokens are surnames.
const anchoredTokens=(name:string)=>familyNorm(name).split(' ').slice(1).filter(t=>t.length>=4&&!['JUNIOR','FILHO','NETO','SOBRINHO'].includes(t));
// PostgreSQL jsonb::text adds a space after each structural comma and colon.
// Match the commit RPC's 2,000,000-byte check, including multibyte strings.
function jsonbSizer(){
 const encoder=new TextEncoder(),strings=new Map<string,number>(),immutableObjects=new WeakMap<object,number>();
 const scalar=(value:any)=>{const json=JSON.stringify(value)??'null';let size=strings.get(json);if(size===undefined){size=encoder.encode(json).byteLength;strings.set(json,size)}return size};
 function size(value:any):number{
  if(value!==null&&typeof value==='object'){const cached=immutableObjects.get(value);if(cached!==undefined)return cached}
  if(Array.isArray(value))return 2+value.reduce((sum,v)=>sum+size(v===undefined?null:v),0)+Math.max(0,value.length-1)*2;
  if(value!==null&&typeof value==='object'){const entries=Object.entries(value).filter(([,v])=>v!==undefined&&typeof v!=='function'&&typeof v!=='symbol');return 2+entries.reduce((sum,[k,v])=>sum+scalar(k)+2+size(v),0)+Math.max(0,entries.length-1)*2}
  return scalar(value);
 }
 return {size,observation:(o:NetworkObservation)=>{let result=immutableObjects.get(o);if(result===undefined){result=size(o);immutableObjects.set(o,result)}return result}};
}
const safeTime=(v:any)=>typeof v==='string'&&Number.isFinite(Date.parse(v))?v:null;
function people(raw:any,provider:Provider){
 const rows=Array.isArray(raw)?raw:[],out:Array<{name:string;role:string}>=[],seen=new Set<string>();
 for(const p of rows.slice(0,MAX.partners)){
  const name=usefulName(provider==='MINHA_RECEITA'?p?.nome_socio:p?.partner_name);
  const physical=provider==='MINHA_RECEITA'?Number(p?.identificador_de_socio)===2:Number(p?.partner_identifier?.code)===2&&p?.is_legal_entity===false;
  if(!physical||!name||p?.name_redacted===true||p?.nome_ocultado===true||seen.has(familyNorm(name)))continue;
  seen.add(familyNorm(name));out.push({name,role:txt(provider==='MINHA_RECEITA'?p.qualificacao_socio:p.role||p.partner_qualification?.name,120)});
 }
 return {people:out,complete:Array.isArray(raw)&&rows.length<=MAX.partners};
}
function safeObservation(raw:any):NetworkObservation|null{
 const provider=raw?.provider as Provider,full=cnpj(raw?.full_cnpj),name=txt(raw?.company_name),city=txt(raw?.city,120),state=txt(raw?.state,2).toUpperCase(),code=cnae(raw?.cnae_code);
 if(!['MINHA_RECEITA','BASE_EMPRESARIAL'].includes(provider)||!isCnpj(full)||!name||!city||!/^[A-Z]{2}$/.test(state)||!code||!Array.isArray(raw?.people))return null;
 const selected=raw.people.slice(0,MAX.partners).flatMap((p:any)=>{const n=usefulName(p?.name);return n?[{name:n,role:txt(p.role,120)}]:[]});
 const prefix=observeKey(provider,full)+':',key=typeof raw.key==='string'&&raw.key.startsWith(prefix)&&/^[0-9a-f-]{36}$/.test(raw.key.slice(prefix.length))?raw.key:observeKey(provider,full);
 return {key,provider,source_url:provider==='MINHA_RECEITA'?MINHA+'/'+full:BASE+'/companies/'+full.slice(0,8),full_cnpj:full,company_name:name,city,state,cnae_code:code,cnae_description:txt(raw.cnae_description),trade_name:txt(raw.trade_name),registration_status:txt(raw.registration_status,80),people:selected,queried_at:safeTime(raw.queried_at)||new Date(0).toISOString(),qsa_complete:raw.qsa_complete===true&&raw.people.length<=MAX.partners};
}
async function stampObservation(o:NetworkObservation,normalize=familyNorm){const {key,source_url,queried_at,...document}=o;const id=await familyStableId(JSON.stringify({...document,people:[...o.people].sort((a,b)=>normalize(a.name).localeCompare(normalize(b.name))||a.role.localeCompare(b.role))}));return {...o,key:observeKey(o.provider,o.full_cnpj)+':'+id}}
function minhaObservation(raw:any,queriedAt:string){
 const members=people(raw?.qsa,'MINHA_RECEITA');
 return safeObservation({provider:'MINHA_RECEITA',full_cnpj:raw?.cnpj,company_name:raw?.razao_social,city:raw?.municipio,state:raw?.uf,cnae_code:raw?.cnae_fiscal,cnae_description:raw?.cnae_fiscal_descricao,trade_name:raw?.nome_fantasia,registration_status:raw?.descricao_situacao_cadastral,people:members.people,qsa_complete:members.complete,queried_at:queriedAt});
}
async function boundedJson(response:Response){
 const reader=response.body?.getReader();if(!reader)throw Error('INVALID_RESPONSE');const chunks:Uint8Array[]=[];let length=0;
 try{for(;;){const {done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>2*1024*1024)throw Error('RESPONSE_TOO_LARGE');chunks.push(value)}}catch(e){await reader.cancel().catch(()=>{});throw e}finally{reader.releaseLock()}
 const bytes=new Uint8Array(length);let pos=0;for(const chunk of chunks){bytes.set(chunk,pos);pos+=chunk.byteLength}
 try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}catch{throw Error('INVALID_RESPONSE')}
}
export async function expandFamilyNetwork(context:FamilyContext,seeds:Seed[],previous:any={},options:Options={}){
 const clock=options.clock||Date.now,started=clock(),deadline=started+Math.min(45000,Math.max(1,options.deadlineMs||45000)),fetcher=options.fetcher||fetch;
 const normalizedStrings=new Map<string,string>();const norm=(v:unknown)=>{const value=String(v??'');let result=normalizedStrings.get(value);if(result===undefined){result=familyNorm(value);normalizedStrings.set(value,result)}return result};
 const sizes=jsonbSizer(),byteSize=sizes.size;
 const baseAvailable=options.baseAvailable===true,minhaAvailable=options.minhaAvailable!==false;
 const fingerprint=await familyQueryFingerprint(context),same=previous?.query_fingerprint===fingerprint;
 const excluded=new Set((options.excludedCnpjs||[]).map(cnpj).filter(isCnpj)),excludedNodes=new Set(options.excludedNodeKeys||[]);
 const limitErrors:string[]=[],coverageErrors:string[]=[],notes:string[]=[],sourceAttempts:any[]=[];
 const push=(rows:string[],code:string)=>{if(!rows.includes(code))rows.push(code)};
 const cleanObs=(rows:any)=>Array.isArray(rows)?rows.map(safeObservation).filter((o:any)=>o&&!excluded.has(o.full_cnpj)):[];
 const state:NetworkState={version:1,query_fingerprint:fingerprint,city_code:same&&/^\d{7}$/.test(String(previous.city_code))?String(previous.city_code):null,municipal_started:same&&previous.municipal_started===true,municipal_cursor:same&&typeof previous.municipal_cursor==='string'&&previous.municipal_cursor.length>0&&previous.municipal_cursor.length<=1024?previous.municipal_cursor:null,municipal_exhausted:same&&previous.municipal_exhausted===true,pagination_stalled:same&&previous.pagination_stalled===true,cursor_checkpoint:same&&Array.isArray(previous.cursor_checkpoint)?previous.cursor_checkpoint.filter((v:any)=>typeof v==='string'&&v.length>0&&v.length<=1024).slice(-32):[],municipal_index:same?cleanObs(previous.municipal_index).slice(0,MAX.index):[],nodes:[],edges:[],observations:same?cleanObs(previous.observations).slice(0,MAX.edges):[],detail_queue:[],processed_details:same&&Array.isArray(previous.processed_details)?previous.processed_details.filter((v:any)=>typeof v==='string'&&/^(C:([A-Z0-9]{12}\d{2})|R:[A-Z0-9]{8})$/.test(v)).slice(0,500):[],inverse_queries:[],cooldowns:{},retry_not_before:null,pages_scanned:same?Math.max(0,Number(previous.pages_scanned)||0):0,scanned_count:same?Math.max(0,Number(previous.scanned_count)||0):0,limits_reached:limitErrors,coverage_errors:coverageErrors};
 if(same){for(const code of Array.isArray(previous.limits_reached)?previous.limits_reached:[])if(/^[A-Z0-9_]+$/.test(code))push(limitErrors,code);for(const code of Array.isArray(previous.coverage_errors)?previous.coverage_errors:[])if(/^[A-Z0-9_]+$/.test(code))push(coverageErrors,code)}
 for(const provider of ['MINHA_RECEITA','BASE_EMPRESARIAL'] as Provider[]){const value=same?safeTime(previous.cooldowns?.[provider]||previous.retry_not_before):null;if(value&&Date.parse(value)>clock())state.cooldowns[provider]=value}
 const nodes=new Map<string,NetworkNode>(),edges=new Map<string,NetworkEdge>(),observations=new Map<string,NetworkObservation>(state.observations.map(o=>[o.key,o])),index=new Map<string,NetworkObservation>(state.municipal_index.map(o=>[o.full_cnpj,o]));
 let indexBytes=2,indexVersion=0;for(const o of index.values())indexBytes+=sizes.observation(o)+2;if(index.size)indexBytes-=2;
 const taskKey=(t:DetailTask)=>t.full_cnpj?'C:'+t.full_cnpj:'R:'+t.basic_cnpj;
 const detailQueue=new Map<string,DetailTask>();
 function addTask(raw:any){const full=cnpj(raw?.full_cnpj),root=cnpj(raw?.basic_cnpj),depth=Math.max(1,Math.min(MAX.depth,Number(raw?.depth)||1)),origin=typeof raw?.origin_key==='string'?raw.origin_key:'root';if((!isCnpj(full)&&!isRoot(root))||excluded.has(full)||excludedNodes.has(origin)||!nodes.has(origin))return;const task={...(isCnpj(full)?{full_cnpj:full}:{basic_cnpj:root}),depth,origin_key:origin,attempts:Math.max(0,Math.min(2,Number(raw?.attempts)||0))};const key=taskKey(task);if(!state.processed_details.includes(key)&&!detailQueue.has(key)){if(detailQueue.size>=300){push(limitErrors,'DETAIL_QUEUE_LIMIT_300');return}detailQueue.set(key,task)}}
 nodes.set('root',{key:'root',type:'ROOT',label:context.lead_name,depth:0,...flags});
 if(same&&Array.isArray(previous.nodes))for(const raw of previous.nodes.slice(0,MAX.companies+MAX.people+1)){const full=cnpj(raw?.full_cnpj),name=usefulName(raw?.person_name),key=raw?.type==='COMPANY'?companyKey(full):raw?.type==='PERSON_CITATION'&&name?personKey(full,name):null;if(!key||!isCnpj(full)||excluded.has(full)||excludedNodes.has(key)||Number(raw.depth)>MAX.depth)continue;if(!nodes.has(key)&&[...nodes.values()].filter(n=>n.type===raw.type).length>=(raw.type==='COMPANY'?MAX.companies:MAX.people)){push(limitErrors,raw.type==='COMPANY'?'GRAPH_COMPANY_LIMIT_120':'GRAPH_PERSON_LIMIT_160');continue}const node:NetworkNode={key,type:raw.type,label:raw.type==='COMPANY'?txt(raw.label)||full:name!,full_cnpj:full,depth:Math.max(1,Number(raw.depth)||1),...flags};if(name&&raw.type==='PERSON_CITATION')node.person_name=name;else{node.city=txt(raw.city,120);node.state=txt(raw.state,2);node.cnae_code=cnae(raw.cnae_code);node.cnae_description=txt(raw.cnae_description);node.trade_name=txt(raw.trade_name);node.registration_status=txt(raw.registration_status,80)}if(typeof raw.candidate_id==='string'&&raw.type==='COMPANY')node.candidate_id=txt(raw.candidate_id);if(typeof raw.observation_key==='string'&&observations.has(raw.observation_key))node.observation_key=raw.observation_key;nodes.set(key,node)}
 if(same&&Array.isArray(previous.detail_queue))for(const raw of previous.detail_queue.slice(0,300))addTask(raw);
 const inverse=new Map<string,InverseTask>();
 if(same&&Array.isArray(previous.inverse_queries))for(const raw of previous.inverse_queries.slice(0,MAX.people+1)){const name=usefulName(raw?.name),origin=txt(raw?.origin_key,600);if(name&&origin&&!excludedNodes.has(origin)&&nodes.has(origin))inverse.set(familyNorm(name),{name,origin_key:origin,depth:Math.min(MAX.depth,Math.max(0,Number(raw.depth)||0)),page:Math.max(1,Math.min(100,Number(raw.page)||1)),done:raw.done===true,attempts:Math.min(2,Math.max(0,Number(raw.attempts)||0))})}
 const seedByFull=new Map<string,Seed>();for(const raw of seeds||[]){const full=cnpj(raw?.full_cnpj);if(!isCnpj(full)||excluded.has(full)||excludedNodes.has(companyKey(full)))continue;const person=usefulName(raw.person_name);const seed={candidate_id:txt(raw.candidate_id),full_cnpj:full,company_name:txt(raw.company_name)||full,city:txt(raw.city,120),state:txt(raw.state,2),person_name:person&&!excludedNodes.has(personKey(full,person))?person:undefined,match_basis:txt(raw.match_basis)};if(!nodes.has(companyKey(full))&&[...nodes.values()].filter(n=>n.type==='COMPANY').length>=MAX.companies){push(limitErrors,'GRAPH_COMPANY_LIMIT_120');continue}seedByFull.set(full,seed);if(!nodes.has(companyKey(full)))nodes.set(companyKey(full),{key:companyKey(full),type:'COMPANY',label:seed.company_name,full_cnpj:full,city:seed.city,state:seed.state,depth:1,candidate_id:seed.candidate_id,...flags});addTask({full_cnpj:full,depth:1,origin_key:'root'})}
 const edgeKinds=new Set(['QSA_PARTICIPATION','SAME_NAME_CANDIDATE','SURNAME_CONTEXT_CANDIDATE','ROOT_CONTEXT_CANDIDATE']);
 const edgeSignatures=new Set<string>();const edgeSignature=(kind:string,from:string,to:string)=>JSON.stringify(['family-network-edge-v1',kind,from,to]);
 if(same&&Array.isArray(previous.edges))for(const raw of previous.edges.slice(0,MAX.edges)){if(!edgeKinds.has(raw.kind)||!nodes.has(raw.from)||!nodes.has(raw.to)||!observations.has(raw.observation_key))continue;const signature=edgeSignature(raw.kind,raw.from,raw.to),id=await familyStableId(signature);edgeSignatures.add(signature);edges.set(id,{id,from:raw.from,to:raw.to,kind:raw.kind,observation_key:raw.observation_key,match_basis:txt(raw.match_basis,80),role:txt(raw.role,120),confidence:'LOW',validation_status:'UNVALIDATED',...flags})}
 let newSourceFailure=false,municipalPages=0,detailReads=0,inverseReads=0;
 let graphVersion=0,anchorVersion=-1,companyCount=[...nodes.values()].filter(n=>n.type==='COMPANY').length,personCount=[...nodes.values()].filter(n=>n.type==='PERSON_CITATION').length;
 type Anchor={name:string;normal:string;padded:string;key:string;full?:string;depth:number;order:number;tokens:string[]};
 let cachedAnchors:Anchor[]=[],exactAnchors=new Map<string,Anchor[]>(),tokenAnchors=new Map<string,Anchor[]>();
 const citationGroups=new Map<string,Map<string,NetworkNode>>();for(const n of nodes.values())if(n.type==='PERSON_CITATION'&&n.person_name){const name=norm(n.person_name);if(!citationGroups.has(name))citationGroups.set(name,new Map());citationGroups.get(name)!.set(n.key,n)}
 async function edge(kind:NetworkEdge['kind'],from:string,to:string,o:NetworkObservation,basis:string,role?:string){if(from===to||!nodes.has(from)||!nodes.has(to)||excludedNodes.has(from)||excludedNodes.has(to))return;const signature=edgeSignature(kind,from,to);if(edgeSignatures.has(signature))return;if(edges.size>=MAX.edges){push(limitErrors,'GRAPH_EDGE_LIMIT_400');return}const id=await familyStableId(signature);edgeSignatures.add(signature);edges.set(id,{id,from,to,kind,observation_key:o.key,match_basis:basis,...(role?{role}:{}),confidence:'LOW',validation_status:'UNVALIDATED',...flags})}
 function anchors(){if(anchorVersion===graphVersion)return cachedAnchors;const rows:Array<{name:string;key:string;depth:number}>=[{name:context.lead_name,key:'root',depth:0}];for(const n of nodes.values())if(n.type==='PERSON_CITATION'&&n.person_name&&n.observation_key&&observations.has(n.observation_key))rows.push({name:n.person_name,key:n.key,depth:n.depth});for(const seed of seedByFull.values())if(seed.person_name)rows.push({name:seed.person_name,key:companyKey(seed.full_cnpj),depth:1});cachedAnchors=rows.filter(a=>a.depth<MAX.depth&&!excludedNodes.has(a.key)).map((a,order)=>{const normal=norm(a.name);return {...a,normal,padded:' '+normal+' ',full:nodes.get(a.key)?.full_cnpj,order,tokens:a.key==='root'?[context.surname]:normal.split(' ').slice(1).filter(t=>t.length>=4&&!['JUNIOR','FILHO','NETO','SOBRINHO'].includes(t))}});exactAnchors=new Map();tokenAnchors=new Map();for(const a of cachedAnchors){if(!exactAnchors.has(a.normal))exactAnchors.set(a.normal,[]);exactAnchors.get(a.normal)!.push(a);if(a.key!=='root')for(const token of a.tokens){if(!tokenAnchors.has(token))tokenAnchors.set(token,[]);tokenAnchors.get(token)!.push(a)}}for(const bucket of tokenAnchors.values())bucket.sort((a,b)=>a.depth-b.depth||a.order-b.order);anchorVersion=graphVersion;return cachedAnchors}
 const normalizedObservations=new WeakMap<NetworkObservation,{padded:string;companyTokens:Set<string>;allTokens:Set<string>;names:Set<string>}>();
 function normalizedObservation(o:NetworkObservation){let saved=normalizedObservations.get(o);if(saved)return saved;const company=norm(o.company_name),companyTokens=new Set(company.split(' ')),allTokens=new Set(companyTokens),names=new Set(o.people.map(p=>norm(p.name)));for(const name of names)for(const token of name.split(' '))allTokens.add(token);saved={padded:' '+company+' ',companyTokens,allTokens,names};normalizedObservations.set(o,saved);return saved}
 function relation(o:NetworkObservation){const candidates=anchors(),cached=normalizedObservation(o);let exact:Anchor|undefined,legal=false;for(const a of candidates){if(a.full!==o.full_cnpj&&a.padded.length<=cached.padded.length&&cached.padded.includes(a.padded)){exact=a;legal=true;break}}for(const name of cached.names){const a=exactAnchors.get(name)?.find(a=>a.full!==o.full_cnpj);if(a&&(!exact||a.order<exact.order)){exact=a;legal=false}}if(exact)return {origin:exact.key,depth:exact.depth+1,kind:'ROOT_CONTEXT_CANDIDATE' as const,basis:legal?'LEGAL_NAME_EXACT_PERSON_NAME':'QSA_EXACT_NAME',rank:0};if(cached.allTokens.has(context.surname))return {origin:'root',depth:1,kind:'SURNAME_CONTEXT_CANDIDATE' as const,basis:cached.companyTokens.has(context.surname)?'LEGAL_NAME_SURNAME_TOKEN':'QSA_SURNAME_TOKEN',rank:1};if(!state.municipal_exhausted)return null;let weak:Anchor|undefined;for(const token of cached.allTokens){const a=tokenAnchors.get(token)?.find(a=>a.full!==o.full_cnpj);if(a&&(!weak||a.depth<weak.depth||a.depth===weak.depth&&a.order<weak.order))weak=a}return weak?{origin:weak.key,depth:weak.depth+1,kind:'SURNAME_CONTEXT_CANDIDATE' as const,basis:'QSA_NAME_TOKEN',rank:2}:null}
 async function select(o:NetworkObservation,depth:number,origin='root',kind:NetworkEdge['kind']='ROOT_CONTEXT_CANDIDATE',basis='SEED_CNPJ_OBSERVED'){
  const full=o.full_cnpj,key=companyKey(full);if(excluded.has(full)||excludedNodes.has(key)||depth>MAX.depth||limitErrors.length)return false;const beforeNodes=nodes.size;
  if(!nodes.has(key)&&basis==='QSA_NAME_TOKEN'){const strong=new Set([...edges.values()].filter(e=>e.kind==='ROOT_CONTEXT_CANDIDATE'||e.kind==='SURNAME_CONTEXT_CANDIDATE'&&e.match_basis!=='QSA_NAME_TOKEN').map(e=>e.to));const weak=new Set([...edges.values()].filter(e=>e.match_basis==='QSA_NAME_TOKEN'&&!strong.has(e.to)).map(e=>e.to));if(weak.size>=MAX.weakCompanies){push(coverageErrors,'WEAK_NAME_TOKEN_EXPANSION_LIMIT_30');return false}}
  if(!nodes.has(key)&&companyCount>=MAX.companies){push(limitErrors,'GRAPH_COMPANY_LIMIT_120');return false}
  observations.set(o.key,o);sizes.observation(o);const prior=nodes.get(key),seed=seedByFull.get(full);
  if(prior?.observation_key===o.key&&depth>=prior.depth){await edge(kind,origin,key,o,basis);if(seed)await edge('ROOT_CONTEXT_CANDIDATE','root',key,o,'SEED_CNPJ_OBSERVED');return false}
  const companyNode:NetworkNode={key,type:'COMPANY',label:o.company_name,full_cnpj:full,city:o.city,state:o.state,cnae_code:o.cnae_code,cnae_description:o.cnae_description,trade_name:o.trade_name,registration_status:o.registration_status,depth:Math.min(depth,prior?.depth??depth),observation_key:o.key,...(seed?{candidate_id:seed.candidate_id}:{}),...flags};nodes.set(key,companyNode);if(!prior){companyCount++;graphVersion++}else if(companyNode.depth<prior.depth)graphVersion++;await edge(kind,origin,key,o,basis);if(seed)await edge('ROOT_CONTEXT_CANDIDATE','root',key,o,'SEED_CNPJ_OBSERVED');
  if(!o.qsa_complete)push(coverageErrors,'QSA_PARTIAL_OR_MISSING');
  for(const p of o.people){const name=norm(p.name),pkey='person:'+full+':'+name;if(excludedNodes.has(pkey))continue;const priorPerson=nodes.get(pkey);if(!priorPerson&&personCount>=MAX.people){push(limitErrors,'GRAPH_PERSON_LIMIT_160');break}const personNode:NetworkNode={key:pkey,type:'PERSON_CITATION',label:p.name,person_name:p.name,full_cnpj:full,depth:companyNode.depth,observation_key:o.key,...flags};nodes.set(pkey,personNode);if(!priorPerson){personCount++;graphVersion++}else if(personNode.depth<priorPerson.depth)graphVersion++;if(!citationGroups.has(name))citationGroups.set(name,new Map());const group=citationGroups.get(name)!;group.set(pkey,personNode);await edge('QSA_PARTICIPATION',key,pkey,o,'QSA_NAME_CITATION',p.role);if(name===norm(context.lead_name))await edge('ROOT_CONTEXT_CANDIDATE','root',pkey,o,'EXACT_LEAD_NAME_PENDING_IDENTITY');const other=[...group.values()].filter(n=>n.full_cnpj!==full).sort((a,b)=>a.depth-b.depth||a.key.localeCompare(b.key))[0];if(other){const [from,to]=[other.key,pkey].sort();await edge('SAME_NAME_CANDIDATE',from,to,o,'EXACT_FULL_NAME_HOMONYM_POSSIBLE')}if(companyNode.depth<MAX.depth&&!inverse.has(name))inverse.set(name,{name:p.name,origin_key:pkey,depth:companyNode.depth,page:1,done:false,attempts:0})}
  return nodes.size!==beforeNodes||!prior||prior.observation_key!==o.key||companyNode.depth<prior.depth;
 }
 let reconciledSignature='';
 async function reconcile(){
  const signature=graphVersion+'|'+indexVersion+'|'+state.municipal_exhausted;if(signature===reconciledSignature)return;
  const ranked=()=>[...index.values()].map(o=>({o,r:seedByFull.has(o.full_cnpj)?{origin:'root',depth:1,kind:'ROOT_CONTEXT_CANDIDATE' as const,basis:'SEED_CNPJ_OBSERVED',rank:-1}:relation(o)})).filter(x=>x.r).sort((a,b)=>a.r!.rank-b.r!.rank||a.r!.depth-b.r!.depth);
  async function strong(){for(let pass=0;pass<=MAX.depth;pass++){let changed=false;for(const {o,r} of ranked().filter(x=>x.r!.rank<2)){if(clock()>=deadline)return;changed=await select(o,r!.depth,r!.origin,r!.kind,r!.basis)||changed}if(!changed)break}}
  await strong();if(!state.municipal_exhausted){reconciledSignature=graphVersion+'|'+indexVersion+'|'+state.municipal_exhausted;return}
  for(let pass=0;pass<MAX.depth;pass++){let selected=0;for(const {o,r} of ranked().filter(x=>x.r!.rank===2&&!nodes.has(companyKey(x.o.full_cnpj)))){if(clock()>=deadline)return;if(await select(o,r!.depth,r!.origin,r!.kind,r!.basis))selected++;if(selected>=10)break}await strong();if(!selected)break}
  if(ranked().some(x=>x.r!.rank===2&&!nodes.has(companyKey(x.o.full_cnpj))))push(coverageErrors,'WEAK_NAME_TOKEN_EXPANSION_LIMIT_30');
  reconciledSignature=graphVersion+'|'+indexVersion+'|'+state.municipal_exhausted;
 }
 async function read(url:string,provider:Provider|'IBGE_LOCALIDADES',endpoint:string){
  if(clock()+300>=deadline)return {ok:false,status:null,data:null,error:'DEADLINE'};
  if(provider!=='IBGE_LOCALIDADES'&&state.cooldowns[provider]&&Date.parse(state.cooldowns[provider]!)>clock())return {ok:false,status:429,data:null,error:'COOLDOWN'};
  const begun=clock();let status:number|null=null,error:string|null=null,data:any=null;
  try{const response=await fetcher(url,{method:'GET',redirect:'error',headers:{Accept:'application/json','User-Agent':'MAX-Intelligence/1.0'},signal:AbortSignal.timeout(Math.max(1,Math.min(5000,deadline-clock()-150)))});status=response.status;if(status===429&&provider!=='IBGE_LOCALIDADES'){const raw=response.headers.get('Retry-After')||'60',seconds=/^\d+$/.test(raw)?Number(raw):Math.max(1,(Date.parse(raw)-clock())/1000)||60;state.cooldowns[provider]=new Date(clock()+Math.min(86400,Math.max(1,seconds))*1000).toISOString()}if(!response.ok)error='HTTP_'+status;else data=await boundedJson(response)}catch(e){const name=(e as Error)?.name,message=(e as Error)?.message;error=name==='AbortError'||name==='TimeoutError'?'TIMEOUT':['INVALID_RESPONSE','RESPONSE_TOO_LARGE'].includes(message)?message:'NETWORK_ERROR'}
  sourceAttempts.push({provider,endpoint,status,error,duration_ms:Math.max(0,clock()-begun)});if(error){newSourceFailure=true;push(notes,error);if(provider!=='IBGE_LOCALIDADES'&&['TIMEOUT','NETWORK_ERROR'].includes(error))state.cooldowns[provider]=new Date(clock()+30000).toISOString()}return {ok:!error,status,data,error};
 }
 function finish(blocked=false){state.nodes=[...nodes.values()];state.edges=[...edges.values()];const referenced=new Set([...state.nodes.map(n=>n.observation_key),...state.edges.map(e=>e.observation_key)]);state.observations=[...observations.values()].filter(o=>referenced.has(o.key));state.municipal_index=[...index.values()];state.detail_queue=[...detailQueue.values()];state.inverse_queries=[...inverse.values()];const times=Object.values(state.cooldowns).filter((v):v is string=>Boolean(v)&&Date.parse(v!)>clock()).sort();state.retry_not_before=null;
  const hardLimit=limitErrors.length>0;const municipalPending=minhaAvailable&&!state.municipal_exhausted&&!state.pagination_stalled;const detailsPending=[...detailQueue.values()].some(t=>t.attempts<2&&(t.full_cnpj?minhaAvailable||baseAvailable:baseAvailable));const inversePending=baseAvailable&&(state.municipal_exhausted||!minhaAvailable)&&[...inverse.values()].some(t=>!t.done&&t.depth<MAX.depth);let continuation=!blocked&&!hardLimit&&(municipalPending||detailsPending||inversePending);
  const ready=(provider:Provider)=>!state.cooldowns[provider]||Date.parse(state.cooldowns[provider]!)<=clock();
  const canProgress=municipalPending&&ready('MINHA_RECEITA')||[...detailQueue.values()].some(t=>t.attempts<2&&(t.full_cnpj?(minhaAvailable&&ready('MINHA_RECEITA')||baseAvailable&&ready('BASE_EMPRESARIAL')):baseAvailable&&ready('BASE_EMPRESARIAL')))||inversePending&&ready('BASE_EMPRESARIAL');
  if(continuation&&!canProgress)state.retry_not_before=times[0]||null;
  // Measure the final checkpoint, after adding any global retry timestamp.
  if(byteSize(state)>MAX.indexBytes){push(limitErrors,'CHECKPOINT_PAYLOAD_LIMIT_2MB');state.municipal_index=state.municipal_index.filter(o=>nodes.has(companyKey(o.full_cnpj)));while(state.municipal_index.length&&byteSize(state)>MAX.indexBytes)state.municipal_index.pop();continuation=false;state.retry_not_before=null}
  const status=blocked?'BLOCKED':newSourceFailure&&!observations.size?'FAILED':'PARTIAL';const actualProvider=sourceAttempts.filter(a=>a.provider!=='IBGE_LOCALIDADES').at(-1)?.provider||[...observations.values()].at(-1)?.provider||null;return {status:status as 'PARTIAL'|'FAILED'|'BLOCKED',complete:false as const,continuation,nodes:state.nodes,edges:state.edges,observations:state.observations,state,search_lineage:{business_provider:actualProvider,business_providers:[...new Set(sourceAttempts.filter(a=>a.provider!=='IBGE_LOCALIDADES').map(a=>a.provider))],source_attempts:sourceAttempts,original:{name:context.lead_name,city:context.city,state:context.state,segment:context.segment},city_code:state.city_code,scope:'ITERATIVE_COMPANY_QSA_NAME_CANDIDATES',sector_filter_applied:false,geography_scope:'COMPANY_ESTABLISHMENT',identity_confirmed:false,kinship_confirmed:false,source_experimental:true,municipal_listing_exhausted:state.municipal_exhausted,national_exact_name_available:baseAvailable,national_coverage_complete:false,pagination_stalled:state.pagination_stalled,scanned_count:state.scanned_count,pages_scanned:state.pages_scanned,detail_reads:detailReads,inverse_reads:inverseReads,limits:MAX,limits_reached:limitErrors,coverage_errors:coverageErrors,notes}}}
 if(!baseAvailable&&!minhaAvailable){push(notes,'SOURCES_DISABLED');return finish(true)}
 if(limitErrors.length)return finish();
 if(!state.city_code&&minhaAvailable){const geo=await read(IBGE+'/estados/'+context.state+'/municipios','IBGE_LOCALIDADES','IBGE /estados/{UF}/municipios');if(!geo.ok)return finish();if(!Array.isArray(geo.data)){push(coverageErrors,'GEOGRAPHY_INVALID_RESPONSE');newSourceFailure=true;return finish()}const matches=geo.data.filter((r:any)=>{const uf=r?.microrregiao?.mesorregiao?.UF||r?.['regiao-imediata']?.['regiao-intermediaria']?.UF;return familyNorm(r?.nome)===familyNorm(context.city)&&uf?.sigla===context.state&&/^\d{7}$/.test(String(r?.id))&&(!uf.id||String(r.id).startsWith(String(uf.id)))});if(matches.length!==1){push(notes,'GEOGRAPHY_NOT_UNIQUE');return finish(true)}state.city_code=String(matches[0].id)}
 while(minhaAvailable&&!state.municipal_exhausted&&!state.pagination_stalled&&municipalPages<MAX.pages&&clock()+300<deadline&&!limitErrors.length){
  const url=new URL(MINHA+'/');url.searchParams.set('municipio',state.city_code!);url.searchParams.set('uf',context.state);url.searchParams.set('limit','100');if(state.municipal_cursor)url.searchParams.set('cursor',state.municipal_cursor);
  const result=await read(url.toString(),'MINHA_RECEITA','MINHA /municipal-all-sector-scan');if(!result.ok)break;const body=result.data,cursor=body?.cursor;
  if(!Array.isArray(body?.data)||body.data.length>100||(cursor!==undefined&&cursor!==null&&(typeof cursor!=='string'||!cursor.length||cursor.length>1024))){push(coverageErrors,'MUNICIPAL_INVALID_RESPONSE');newSourceFailure=true;break}
  const queriedAt=new Date(clock()).toISOString();for(const raw of body.data){const normalized=minhaObservation(raw,queriedAt);if(!normalized||String(raw?.codigo_municipio_ibge)!==state.city_code||norm(normalized.city)!==norm(context.city)||normalized.state!==context.state){push(coverageErrors,'MUNICIPAL_INVALID_COMPANY_ROW');continue}const o=await stampObservation(normalized,norm);if(excluded.has(o.full_cnpj))continue;const prior=index.get(o.full_cnpj);if(!prior){if(index.size>=MAX.index){push(limitErrors,'MUNICIPAL_INDEX_LIMIT_3000');break}indexBytes+=sizes.observation(o)+(index.size?2:0);state.scanned_count++}else indexBytes+=sizes.observation(o)-sizes.observation(prior);index.set(o.full_cnpj,o);indexVersion++}
  state.municipal_started=true;state.pages_scanned++;municipalPages++;
  if(indexBytes>MAX.indexBytes){push(limitErrors,'MUNICIPAL_INDEX_PAYLOAD_LIMIT_2MB');break}
  if(cursor==null){state.municipal_cursor=null;state.municipal_exhausted=true;break}
  if(cursor===state.municipal_cursor||state.cursor_checkpoint.includes(cursor)){state.pagination_stalled=true;push(coverageErrors,'CURSOR_DID_NOT_ADVANCE');break}
  state.cursor_checkpoint.push(cursor);state.cursor_checkpoint=state.cursor_checkpoint.slice(-32);state.municipal_cursor=cursor;
 }
 // Scan the saved index once per batch, not again after each fetched page.
 await reconcile();
 // A saved page can supply every selected company's QSA without another HTTP call.
 for(const [key,task] of [...detailQueue])if(task.full_cnpj&&index.has(task.full_cnpj)){await select(index.get(task.full_cnpj)!,task.depth,task.origin_key);state.processed_details.push(key);detailQueue.delete(key)}
 if(!inverse.has(familyNorm(context.lead_name)))inverse.set(familyNorm(context.lead_name),{name:context.lead_name,origin_key:'root',depth:0,page:1,done:false,attempts:0});
 if(baseAvailable&&(state.municipal_exhausted||!minhaAvailable)&&!limitErrors.length)for(const task of inverse.values()){
  if(task.done||task.depth>=MAX.depth||inverseReads>=MAX.inverse||clock()+300>=deadline)continue;
  const url=new URL(BASE+'/partners');url.searchParams.set('filter[partner_name]',task.name);url.searchParams.set('filter[partner_identifier]','2');url.searchParams.set('per_page','100');url.searchParams.set('page',String(task.page));url.searchParams.set('include','qualification');
  const result=await read(url.toString(),'BASE_EMPRESARIAL','BASE /partners exact-name');inverseReads++;if(!result.ok){if(result.status!==429){task.attempts++;if(task.attempts>=2){task.done=true;push(coverageErrors,'INVERSE_SOURCE_UNAVAILABLE_AFTER_2_ATTEMPTS')}}break}const body=result.data;
  if(!Array.isArray(body?.data)||body.data.length>100||!body.links||!Object.hasOwn(body.links,'next')){push(coverageErrors,'INVERSE_INVALID_RESPONSE');newSourceFailure=true;task.attempts++;if(task.attempts>=2){task.done=true;push(coverageErrors,'INVERSE_SOURCE_UNAVAILABLE_AFTER_2_ATTEMPTS')}break}
  task.attempts=0;
  for(const raw of body.data){const name=usefulName(raw?.partner_name),root=cnpj(raw?.basic_cnpj);if(!name||familyNorm(name)!==familyNorm(task.name)||Number(raw?.partner_identifier?.code)!==2||raw?.is_legal_entity!==false||raw?.name_redacted===true||!isRoot(root)){push(coverageErrors,'INVERSE_INVALID_PARTNER_ROW');continue}addTask({basic_cnpj:root,depth:task.depth+1,origin_key:task.origin_key})}
  if(body.links.next===null)task.done=true;else{try{const next=new URL(body.links.next);const page=Number(next.searchParams.get('page'));if(next.origin!=='https://app.baseempresarial.com.br'||next.pathname!=='/api/v1/partners'||page!==task.page+1||page>100)throw Error();task.page=page}catch{task.done=true;push(coverageErrors,'INVERSE_PAGINATION_INVALID')}}
 }
 for(const [key,task] of [...detailQueue]){
  if(detailReads>=MAX.details||clock()+300>=deadline||limitErrors.length)break;if(task.attempts>=2)continue;let result:any=null;let provider:Provider='MINHA_RECEITA';
  if(task.full_cnpj&&minhaAvailable){result=await read(MINHA+'/'+task.full_cnpj,provider,'MINHA /{cnpj}');detailReads++;if(result.ok){const normalized=minhaObservation(result.data,new Date(clock()).toISOString());if(normalized&&normalized.full_cnpj===task.full_cnpj){await select(await stampObservation(normalized),task.depth,task.origin_key);state.processed_details.push(key);detailQueue.delete(key);continue}push(coverageErrors,'DETAIL_CNPJ_OR_FORMAT_MISMATCH');newSourceFailure=true;task.attempts++;continue}if(result.status===429)break}
  if(baseAvailable&&(!result||['TIMEOUT','NETWORK_ERROR','HTTP_404'].includes(result.error))&&clock()+300<deadline&&detailReads<MAX.details){provider='BASE_EMPRESARIAL';const root=task.basic_cnpj||task.full_cnpj!.slice(0,8);result=await read(BASE+'/companies/'+root,provider,'BASE /companies/{basic_cnpj}');detailReads++;if(result.ok){const raw=result.data?.data,members=people(raw?.partners,provider);if(cnpj(raw?.basic_cnpj)!==root||!Array.isArray(raw?.establishments)){push(coverageErrors,'DETAIL_CNPJ_OR_FORMAT_MISMATCH');newSourceFailure=true;task.attempts++;continue}const originName=nodes.get(task.origin_key)?.person_name||context.lead_name;if(task.basic_cnpj&&!members.people.some(p=>familyNorm(p.name)===familyNorm(originName))){push(coverageErrors,'INVERSE_CURRENT_QSA_NAME_NOT_FOUND');task.attempts++;continue}if(raw.establishments.length>100)push(coverageErrors,'ESTABLISHMENTS_PARTIAL');let accepted=0;for(const unit of raw.establishments.slice(0,100)){const full=cnpj(unit?.full_cnpj);if(!isCnpj(full)||full.slice(0,8)!==root){push(coverageErrors,'DETAIL_CNPJ_OR_FORMAT_MISMATCH');continue}const normalized=safeObservation({provider,full_cnpj:full,company_name:raw.corporate_name,city:unit?.address?.city?.name??unit.city_name,state:unit?.address?.state?.abbreviation??unit.state_abbreviation,cnae_code:unit.main_cnae,cnae_description:unit.main_cnae_name,trade_name:unit.trade_name,registration_status:unit.registration_status?.name,people:members.people,qsa_complete:members.complete,queried_at:new Date(clock()).toISOString()});if(!normalized){push(coverageErrors,'DETAIL_CNPJ_OR_FORMAT_MISMATCH');continue}if(task.full_cnpj&&full!==task.full_cnpj)continue;await select(await stampObservation(normalized),task.depth,task.origin_key,'ROOT_CONTEXT_CANDIDATE','EXACT_NAME_ROOT_LOOKUP_PENDING_IDENTITY');accepted++}if(accepted){state.processed_details.push(key);detailQueue.delete(key);continue}newSourceFailure=true}}
  if(result?.status===429)break;
  task.attempts++;push(coverageErrors,'DETAIL_SOURCE_UNAVAILABLE');
 }
 await reconcile();state.processed_details=[...new Set(state.processed_details)].slice(-500);
 return finish();
}
