import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {normalizeBaseCompany,canonicalRegistryText} from '../supabase/functions/_shared/cnpj-fallback.ts';
import {fetchSourceJson} from '../supabase/functions/_shared/source-operations.ts';
import {insertEvidenceOnce} from '../supabase/functions/_shared/connector-policy.ts';
import {qsaRelationshipType} from '../supabase/functions/_shared/qsa-role.ts';
function setup(review='REJECTED',rawOverride={}){
 let handler,writes=0;const insertedClaims=[],insertedRelationships=[];const ev={id:'e',verification_status:review};
 const db={auth:{getUser:async()=>({data:{user:{id:'u'}}})},from(table){let op='read';const filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},maybeSingle(){return q},single(){return q},upsert(){op='upsert';return q},insert(payload){op='insert';if(table==='claims')insertedClaims.push(payload);if(table==='relationships')insertedRelationships.push(payload);return q},update(){op='update';return q},not(){return q},then(resolve,reject){return Promise.resolve().then(()=>{if(['claims','relationships'].includes(table)&&op!=='read')writes++;const data=table==='profiles'?{active_organization_id:'o'}:table==='organization_members'?{status:'ACTIVE',role:'OWNER'}:table==='leads'?{id:'l',kind:'COMPANY'}:table==='source_registry'?{id:'source'}:table==='companies'?{id:'c'}:table==='lead_company_links'?{id:'link',status:'VERIFIED'}:table==='evidence'?ev:table==='people'&&op==='insert'?{id:'person'}:table==='relationships'&&op==='insert'?{id:'relation'}:table==='claims'&&op==='insert'?{id:'claim-'+insertedClaims.length}:null;return {data,error:null}}).then(resolve,reject)}};return q}};
 const raw={cnpj:'32901144000105',razao_social:'Empresa teste',municipio:'BARRETOS',uf:'SP',descricao_situacao_cadastral:'ATIVA',qsa:[],...rawOverride};
 const source=fs.readFileSync(new URL('../supabase/functions/cnpj-enrich/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://test.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,qsaRelationshipType,fetch:async()=>Response.json(raw),insertEvidenceOnce,normalizeBaseCompany,canonicalRegistryText,fetchSourceJson:(url,valid,options)=>fetchSourceJson(url,valid,{...options,fetcher:async()=>Response.json(raw)}),crypto,TextEncoder,Response,Request,AbortSignal,Date,JSON,String,Number,Map,Set,Uint8Array});
 return {call:()=>handler(new Request('https://test.supabase.co',{method:'POST',headers:{Authorization:'Bearer test-only','Content-Type':'application/json'},body:JSON.stringify({lead_id:'l',cnpj:'32901144000105'})})),writes:()=>writes,insertedClaims,insertedRelationships};
}
test('papel QSA distingue conselho/gestão de propriedade e não presume sócio para papel desconhecido',()=>{for(const role of ['Conselheiro de Administração','CONSELHEIRO DE ADMINISTRACAO RESIDENTE NO EXTERIOR','Diretor','Presidente','Sócio-Administrador'])assert.equal(qsaRelationshipType(role),'ADMINISTRADOR');for(const role of ['Sócio','Sócio Pessoa Física Residente no Exterior','Titular Pessoa Física','Acionista'])assert.equal(qsaRelationshipType(role),'SOCIO');for(const role of [null,'Fundador','Conselheiro Fiscal','Procurador'])assert.equal(qsaRelationshipType(role),'QSA_PARTICIPANT')});
test('CNPJ real handler mantém rejeição e não recria fatos ou relações',async()=>{const s=setup();const r=await s.call();assert.equal(r.status,200);const data=await r.json();assert.equal(data.status,'REVIEW_REQUIRED');assert.deepEqual(data.claim_ids,[]);assert.equal(s.writes(),0)});
test('CNPJ real handler bloqueia também documento pendente ou desatualizado',async()=>{for(const status of ['PENDING','STALE','FAILED']){const s=setup(status);const d=await(await s.call()).json();assert.equal(d.status,'REVIEW_REQUIRED');assert.equal(s.writes(),0)}});

test('handler registra código CNAE separado da descrição e não inventa descrição ausente',async()=>{const s=setup('VERIFIED',{cnae_fiscal:8630501,cnae_fiscal_descricao:null});assert.equal((await s.call()).status,200);assert.equal(s.insertedClaims.find(c=>c.predicate==='cnae_code').value_text,'8630501');assert.equal(s.insertedClaims.some(c=>c.predicate==='cnae'),false)});
test('handler real grava conselheiro em administração e nunca como sócio',async()=>{const s=setup('VERIFIED',{qsa:[{nome_socio:'Pessoa Teste',identificador_de_socio:2,qualificacao_socio:'Conselheiro de Administração'}]});assert.equal((await s.call()).status,200);assert.equal(s.insertedRelationships.length,1);assert.equal(s.insertedRelationships[0].relationship_type,'ADMINISTRADOR');assert.match(s.insertedRelationships[0].reason,/Conselheiro/)});
