import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {insertEvidenceOnce} from '../supabase/functions/_shared/connector-policy.ts';
function setup(review='REJECTED'){
 let handler,writes=0;const ev={id:'e',verification_status:review};
 const db={auth:{getUser:async()=>({data:{user:{id:'u'}}})},from(table){let op='read';const filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},maybeSingle(){return q},single(){return q},upsert(){op='upsert';return q},insert(){op='insert';return q},update(){op='update';return q},not(){return q},then(resolve,reject){return Promise.resolve().then(()=>{if(['claims','relationships'].includes(table)&&op!=='read')writes++;const data=table==='profiles'?{active_organization_id:'o'}:table==='organization_members'?{status:'ACTIVE',role:'OWNER'}:table==='leads'?{id:'l',kind:'COMPANY'}:table==='source_registry'?{id:'source'}:table==='companies'?{id:'c'}:table==='lead_company_links'?{id:'link',status:'VERIFIED'}:table==='evidence'?ev:null;return {data,error:null}}).then(resolve,reject)}};return q}};
 const raw={cnpj:'32901144000105',razao_social:'Empresa teste',municipio:'BARRETOS',uf:'SP',descricao_situacao_cadastral:'ATIVA',qsa:[]};
 const source=fs.readFileSync(new URL('../supabase/functions/cnpj-enrich/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://test.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,fetch:async()=>Response.json(raw),insertEvidenceOnce,crypto,TextEncoder,Response,Request,AbortSignal,Date,JSON,String,Number,Map,Set,Uint8Array});
 return {call:()=>handler(new Request('https://test.supabase.co',{method:'POST',headers:{Authorization:'Bearer test-only','Content-Type':'application/json'},body:JSON.stringify({lead_id:'l',cnpj:'32901144000105'})})),writes:()=>writes};
}
test('CNPJ real handler mantém rejeição e não recria fatos ou relações',async()=>{const s=setup();const r=await s.call();assert.equal(r.status,200);const data=await r.json();assert.equal(data.status,'REVIEW_REQUIRED');assert.deepEqual(data.claim_ids,[]);assert.equal(s.writes(),0)});
test('CNPJ real handler bloqueia também documento pendente ou desatualizado',async()=>{for(const status of ['PENDING','STALE','FAILED']){const s=setup(status);const d=await(await s.call()).json();assert.equal(d.status,'REVIEW_REQUIRED');assert.equal(s.writes(),0)}});
