import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {buildCompanyPassport} from '../lib/company-passport.ts';
const source=fs.readFileSync(new URL('../lib/commercial-opportunities.ts',import.meta.url),'utf8').replace(/^import .*\r?\n/gm,'');const context={exports:{},buildCompanyPassport};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);const build=context.exports.buildCommercialOpportunities;
const fixture=()=>({companies:[{id:'a',legal_name:'Hospital',link_status:'VERIFIED'},{id:'b',legal_name:'Agro',link_status:'VERIFIED'}],evidence:[{id:'e',verification_status:'VERIFIED'}],claims:[{company_id:'a',predicate:'cnae',value_text:'Atividades hospitalares',status:'VERIFIED',classification:'FACT',claim_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]},{company_id:'b',predicate:'cnae',value_text:'Cultivo agrícola',status:'VERIFIED',classification:'FACT',claim_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]}]});
test('perguntas comerciais respeitam atividade e empresa, sem transportar contexto entre núcleos',()=>{const out=build(fixture());assert.equal(out.length,4);assert.match(out.find(o=>o.company==='Hospital'&&o.theme.includes('Crédito')).question,/convênios/);assert.match(out.find(o=>o.company==='Agro'&&o.theme.includes('Crédito')).question,/safra/);assert.ok(out.every(o=>o.evidenceIds.length&&o.stage==='Hipótese para descoberta'))});
test('sem evidência válida ou com contradição não gera oportunidade',()=>{for(const mode of ['failed','contradicted']){const d=fixture();if(mode==='failed')d.evidence[0].verification_status='FAILED';else d.claims.forEach(c=>c.claim_evidence.push({evidence_id:'e',support_type:'CONTRADICTS'}));assert.equal(build(d).length,0)}});
test('empresa rejeitada não produz oportunidade e capital isolado não indica crédito ou patrimônio',()=>{const d=fixture();d.companies.forEach(c=>c.link_status='REJECTED');assert.equal(build(d).length,0);d.companies[0].link_status='VERIFIED';d.claims=[{...d.claims[0],predicate:'registered_capital',value_text:'100000000'}];assert.equal(build(d).length,0)});
test('contratos e financiamento geram perguntas com limites financeiros explícitos',()=>{const d=fixture();d.claims=[];d.events=['PUBLIC_CONTRACT','BNDES_FINANCING'].map((event_type,i)=>({id:String(i),company_id:'a',classification:'FACT',status:'VERIFIED',event_type,event_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]}));const out=build(d);assert.equal(out.length,2);assert.ok(out.every(o=>o.company==='Hospital'));assert.match(out[0].limit,/receita recebida/);assert.match(out[1].limit,/saldo devedor atual/)});

test('atividades secundárias verificadas sustentam perguntas quando descrição principal não está disponível',()=>{const d=fixture();d.claims=d.claims.map(c=>({...c,predicate:'secondary_activities'}));const out=build(d);assert.equal(out.length,4);assert.match(out.find(o=>o.company==='Agro'&&o.theme.includes('Crédito')).question,/safra/);assert.ok(out.every(o=>o.basis.startsWith('Atividades secundárias cadastradas:')))});
