import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {discoverCompaniesByName,isValidCompanyCnpj,companyNameJson} from '../supabase/functions/_shared/company-name-discovery.ts';
import {familyStableId} from '../supabase/functions/_shared/family-discovery.ts';
const ID='11111111-1111-4111-8111-111111111111',ORG='22222222-2222-4222-8222-222222222222',DOC='33333333-3333-4333-8333-333333333333',SOURCE='44444444-4444-4444-8444-444444444444';
const lead={id:ID,kind:'COMPANY',name:'Marca QA',city:'Barretos',state:'SP'},row=(overrides={})=>({full_cnpj:'32901144000105',corporate_name:'INDUSTRIA DOCUMENTADA LTDA',trade_name:'MARCA QA',city_name:'Barretos',state_abbreviation:'SP',main_cnae:'4712100',main_cnae_name:'Comércio',registration_status:'2',qsa:[{cpf:'PRIVATE_CPF'}],address:'PRIVATE_ADDRESS',...overrides});
const source=fn=>async(input,init)=>{const u=new URL(input);assert.equal(u.hostname,'app.baseempresarial.com.br');assert.equal(u.pathname,'/api/v1/companies/search');assert.equal(u.searchParams.get('q'),null);assert.equal(u.searchParams.get('filter[partner_name]'),null);assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,undefined);return fn(u)};
test('razão social e fantasia são consultas separadas; nome de sócio jamais é filtro ou evidência',async()=>{
 const seen=[];const result=await discoverCompaniesByName(lead,{fetcher:source(u=>{seen.push(u);return Response.json({data:u.searchParams.has('trade_name')?[row()]:[],meta:{has_more:false}})})});
 assert.equal(seen.length,2);assert.deepEqual(seen.map(u=>u.searchParams.has('corporate_name')?'corporate_name':'trade_name').sort(),['corporate_name','trade_name']);assert.equal(result.complete,true);assert.equal(result.candidates[0].match_basis,'TRADE_NAME_PREFIX');assert.equal(result.candidates[0].identity_confirmed,false);assert.equal(result.candidates[0].city_match,true);assert.doesNotMatch(JSON.stringify(result),/PRIVATE_|qsa|address|partner_name/);
});
test('duas observações do mesmo CNPJ deduplicam com ambas as bases sem identidade automática',async()=>{const r=await discoverCompaniesByName(lead,{fetcher:source(()=>Response.json({data:[row({corporate_name:'MARCA QA INDUSTRIA LTDA'})],meta:{has_more:false}}))});assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].match_bases.length,2);assert.equal(r.candidates[0].kinship_confirmed,false)});
test('prefixos ignoram acentos/caixa; razão social sem correspondência e CNPJ inválido não são candidatos',async()=>{const r=await discoverCompaniesByName({...lead,name:'Márca QA'},{fetcher:source(u=>Response.json({data:u.searchParams.has('corporate_name')?[row(),row({full_cnpj:'32901144000100',corporate_name:'MARCA QA INVALIDA'})]:[row({trade_name:'marca qa filial'})],meta:{has_more:false}}))});assert.equal(r.candidates.length,1);assert.equal(r.status,'PARTIAL');assert.ok(r.notes.includes('INVALID_OR_NONMATCHING_COMPANY_ROW'));assert.equal(isValidCompanyCnpj('32901144000100'),false);assert.equal(isValidCompanyCnpj('00000000000000'),false)});
test('429/403 e formato inválido não usam bridge nem registram ausência como busca completa',async()=>{for(const status of [429,403]){let fallbacks=0;const r=await discoverCompaniesByName(lead,{fetcher:source(()=>new Response('',{status,headers:{'Retry-After':'120'}})),fallback:async()=>{fallbacks++;throw Error()}});assert.equal(r.status,'FAILED');assert.equal(r.complete,false);assert.equal(fallbacks,0);if(status===429)assert.equal(r.retry_after_seconds,120)}const invalid=await discoverCompaniesByName(lead,{fetcher:source(()=>Response.json({oops:[]}))});assert.equal(invalid.status,'FAILED');assert.equal(invalid.complete,false)});
test('transporte falho usa bridge limitado e origem cadastral preservada',async()=>{const calls=[];const r=await discoverCompaniesByName(lead,{fetcher:source(()=>{throw new DOMException('private upstream','TimeoutError')}),fallback:async(path,timeout)=>{calls.push({path,timeout});return {ok:true,status:200,data:{data:path.includes('trade_name')?[row()]:[],meta:{has_more:false}},error:null}}});assert.equal(r.status,'COMPLETED');assert.equal(calls.length,2);assert.ok(calls.every(c=>c.timeout<=13000));assert.equal(r.search_lineage.source_attempts.filter(a=>a.transport==='OWNED_BRIDGE').length,2);assert.doesNotMatch(JSON.stringify(r),/private upstream/)});
test('paginação ausente ou próxima página expõe parcial, sem confundir vinte resultados com cobertura nacional',async()=>{for(const meta of [{},{has_more:true}]){const r=await discoverCompaniesByName(lead,{fetcher:source(()=>Response.json({data:[],meta}))});assert.equal(r.status,'PARTIAL');assert.equal(r.complete,false)}const r=await discoverCompaniesByName(lead,{fetcher:source(()=>Response.json({data:Array.from({length:21},()=>row()),meta:{has_more:false}}))});assert.equal(r.status,'FAILED')});
test('nome pessoal mascarado no texto empresarial não vira consulta; CPF empresarial é removido',async()=>{let calls=0;const blocked=await discoverCompaniesByName({...lead,name:'Marca 12345678901'},{fetcher:async()=>{calls++;throw Error()}});assert.equal(blocked.status,'BLOCKED');assert.equal(calls,0);const result=await discoverCompaniesByName(lead,{fetcher:source(u=>Response.json({data:u.searchParams.has('trade_name')?[row({corporate_name:'Empresa 12345678901'})]:[],meta:{has_more:false}}))});assert.doesNotMatch(JSON.stringify(result),/12345678901/);assert.ok(result.candidates[0].company_name.includes('[identificador removido]'))});
function fixture(overrides={}){const state={user:{id:ID},role:'OWNER',foreign:false,kind:'COMPANY',sourceStatus:'CONNECTED_LIMITED',runFound:true,evidenceStatus:'VERIFIED',boundStatus:'VERIFIED',writeError:false,logError:false,candidateStatus:'UNVALIDATED',racingReject:false,...overrides};const writes=[],documents=[],store=new Map();let handler;
 const db={auth:{getUser:async()=>({data:{user:state.user},error:null})},from(table){let mode='read',payload,options;const eq={};const q={select:()=>q,maybeSingle:()=>q,eq:(k,v)=>{eq[k]=v;return q},insert:p=>{mode='insert';payload=p;return q},upsert:(p,o)=>{mode='upsert';payload=p;options=o;return q}};q.then=(resolve,reject)=>Promise.resolve().then(()=>{if(mode!=='read')writes.push({table,mode,payload,options,eq});if(table==='candidate_entities'&&mode==='upsert'){assert.equal(options.ignoreDuplicates,true);if(!store.has(payload.id))store.set(payload.id,{...payload,validation_status:state.candidateStatus});if(state.racingReject)store.get(payload.id).validation_status='REJECTED'}const data=table==='profiles'?{active_organization_id:ORG}:table==='organization_members'?{status:'ACTIVE',role:state.role}:table==='leads'?state.foreign?null:{...lead,kind:state.kind}:table==='source_registry'?{id:SOURCE,connection_status:state.sourceStatus}:table==='research_runs'?state.runFound?{id:ID}:null:table==='candidate_entities'?store.get(eq.id):table==='evidence'?{id:DOC,verification_status:state.boundStatus,source_registry_id:SOURCE}:null;return {data,error:table==='candidate_entities'&&mode==='upsert'&&state.writeError||table==='source_fetch_logs'&&state.logError?{message:'Controlled persistence failure'}:null}}).then(resolve,reject);return q}};
 const discovery={ok:true,status:'COMPLETED',complete:true,notes:[],retry_after_seconds:null,search_lineage:{query_name:'MARCA QA',source_attempts:[{provider:'BASE_EMPRESARIAL',status:200,error:null}]},candidates:[{full_cnpj:'32901144000105',basic_cnpj:'32901144',company_name:'INDUSTRIA DOCUMENTADA LTDA',trade_name:'MARCA QA',city:'Barretos',state:'SP',cnae_code:'4712100',cnae_description:'Comércio',source_url:'https://baseempresarial.com.br/empresa/32901144000105',match_bases:['TRADE_NAME_PREFIX'],match_basis:'TRADE_NAME_PREFIX',identity_confirmed:false,kinship_confirmed:false}]};
 const source=fs.readFileSync(new URL('../supabase/functions/company-name-discovery/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:k=>k==='BASE_EMPRESARIAL_PROXY_URL'?undefined:'https://qa.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,discoverCompaniesByName:async()=>discovery,companyNameJson,familyStableId,persistSourceEvidence:async(_db,p)=>{documents.push(p);return {data:{id:DOC,verification_status:state.evidenceStatus},error:null}},Response,Request,AbortSignal,URL,console});return {handler,state,writes,documents,store};
}
const request=(body={},auth=true)=>new Request('https://qa.test',{method:'POST',headers:auth?{Authorization:'Bearer synthetic','Content-Type':'application/json'}:{'Content-Type':'application/json'},body:JSON.stringify({lead_id:ID,...body})});
test('endpoint exige sessão/org/operador/lead empresarial/run próprio e fonte habilitada',async()=>{for(const [opts,auth,status]of [[{},false,401],[{user:null},true,401],[{role:'VIEWER'},true,403],[{role:'UNKNOWN'},true,403],[{foreign:true},true,404],[{kind:'PERSON'},true,409],[{runFound:false},true,404]]){const f=fixture(opts),r=await f.handler(request(opts.runFound===false?{research_run_id:ID}:{},auth));assert.equal(r.status,status);assert.equal(f.writes.length,0);assert.equal(f.documents.length,0)}const blocked=fixture({sourceStatus:'DISABLED'}),r=await blocked.handler(request());assert.equal((await r.json()).status,'BLOCKED');assert.equal(blocked.documents.length,0)});
test('endpoint persiste documento/candidato distinto LOW sem modificar lead/claims/relações',async()=>{const f=fixture(),r=await f.handler(request({research_run_id:ID}));assert.equal(r.status,200);const b=await r.json();assert.equal(b.candidates_found,1);const c=f.writes.find(w=>w.table==='candidate_entities').payload;assert.equal(c.candidate_type,'RFB_COMPANY_NAME_MATCH');assert.equal(c.confidence,'LOW');assert.equal(c.validation_status,'UNVALIDATED');assert.equal(c.metadata.identity_confirmed,false);assert.equal(f.documents[0].document_type,'CNPJ_REGISTRY');assert.ok(f.writes.every(w=>['candidate_entities','source_fetch_logs'].includes(w.table)));assert.doesNotMatch(f.documents[0].raw_reference,/qsa|cpf|age|address/i);for(const eq of f.writes.filter(w=>w.table==='candidate_entities').map(w=>w.payload))assert.equal(eq.organization_id,ORG)});
test('reconsulta e descarte concorrente preservam REJECTED; documento revisado não gera candidato',async()=>{for(const opts of [{candidateStatus:'REJECTED'},{racingReject:true}]){const f=fixture(opts),r=await f.handler(request());assert.equal((await r.json()).candidates_found,0);assert.equal([...f.store.values()][0].validation_status,'REJECTED')}for(const opts of [{evidenceStatus:'REJECTED'},{boundStatus:'REJECTED'}]){const f=fixture(opts),r=await f.handler(request());const b=await r.json();assert.equal(b.candidates_found,0);assert.equal(b.status,'PARTIAL');assert.equal(b.complete,false)}});
test('falha de gravação de candidato ou log nunca responde sucesso',async()=>{for(const opts of [{writeError:true},{logError:true}]){const f=fixture(opts);assert.equal((await f.handler(request())).status,500)}});
