import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {familyContext,familySegmentRule,familyNorm,familyStableId,familyQueryFingerprint,familyResumeState,discoverFamilyContext,surnameToken} from '../supabase/functions/_shared/family-discovery.ts';
const lead={kind:'PERSON',name:'Pessoa de Teste Sobrenome',city:'Cidade QA',state:'SP',segment:'Agro'},context=familyContext(lead,'AGRO');
const company=(n=1,extra={})=>({full_cnpj:String(n).padStart(8,'0')+'000100',corporate_name:n===1?'Empresa Sobrenome Rural':'Empresa Rural '+n,main_cnae:'0111301',main_cnae_name:'Cultivo',city_name:'Cidade QA',state_abbreviation:'SP',city_id:3500001,...extra});
function transport({pages=[[company()]],hasMore,detail,exactCity=true,missingContinuation=false}={}){const calls=[];let active=0,max=0;const f=async raw=>{const u=new URL(raw);calls.push(u);let body;if(u.pathname.endsWith('/locations/states'))body={data:[{ibge_code:35,abbreviation:'SP'}]};else if(u.pathname.endsWith('/locations/cities'))body={data:exactCity?[{ibge_code:3500001,name:'Cidade QA'}]:[]};else if(u.pathname.endsWith('/cities/stats'))body={data:[{ibge_code:3500001,name:'CIDADE QA'},{ibge_code:3500002,name:'Outra cidade'}]};else if(u.pathname.endsWith('/companies/search')){const p=Number(u.searchParams.get('page'));body={data:pages[p-1]||[],meta:missingContinuation?{}:{has_more:hasMore??p<pages.length}}}else{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,1));const root=u.pathname.split('/').at(-1);body=detail?detail(root):{data:{basic_cnpj:root,partners:[{partner_name:'Outro Nome Sobrenome',partner_identifier:{code:'2'},is_legal_entity:false,name_redacted:false,role:'Sócio',cnpj_cpf_partner:'PRIVATE_MARKER',age_group:{name:'PRIVATE_AGE'},address:'PRIVATE_ADDRESS'},{partner_name:'Jurídica Sobrenome',partner_identifier:{code:'1'},is_legal_entity:true},{partner_name:'Nome ocultado Sobrenome',partner_identifier:{code:'2'},is_legal_entity:false,name_redacted:true}]}};active--}return Response.json(body)};return {fetcher:f,calls,get max(){return max}}}
test('contexto exige pessoa/localidade/segmento e usa sobrenome token sem adivinhar atividade genérica',()=>{assert.equal(surnameToken('Nome Sobrenome Junior'),'SOBRENOME');assert.equal(familySegmentRule('Empresário','GENERICO'),null);assert.equal(familySegmentRule('Empresário','AGRO'),null);assert.equal(familySegmentRule('6201-5/01','EMPRESARIO').codes[0],'6201501');assert.equal(familySegmentRule('01.51-2-01').codes[0],'0151201');assert.deepEqual(familySegmentRule('Médico','AGRO').prefixes,['86']);assert.deepEqual(familySegmentRule('Agropecuária').prefixes,['01','02','03']);assert.equal(familyContext({...lead,kind:'COMPANY'},'AGRO').ok,false);assert.equal(familyContext({...lead,city:null},'AGRO').ok,false)});
test('busca invertida encontra nome empresarial e PF do QSA sem CPF/idade/endereço ou parentesco',async()=>{const io=transport(),r=await discoverFamilyContext(context,{},io);assert.equal(r.status,'COMPLETED');assert.equal(r.candidates.length,2);assert.ok(r.candidates.some(c=>c.match_basis==='COMPANY_NAME'&&c.entity_type==='COMPANY'));assert.ok(r.candidates.some(c=>c.person_name==='Outro Nome Sobrenome'));assert.doesNotMatch(JSON.stringify(r),/PRIVATE_/);assert.ok(!io.calls.some(u=>u.pathname==='/api/v1/partners'));assert.ok(io.calls.find(u=>u.pathname.endsWith('/companies/search')).searchParams.get('city_id'));assert.equal(r.search_lineage.geography_scope,'COMPANY_ESTABLISHMENT')});
test('município normaliza acento/caixa por fallback mas exige match exato e UF',async()=>{const io=transport({exactCity:false}),r=await discoverFamilyContext(context,{},io);assert.equal(r.state.city_code,'3500001');assert.ok(io.calls.some(u=>u.pathname.endsWith('/cities/stats')));assert.equal(r.status,'COMPLETED')});
test('CNAE/localidade/sobrenome por token excluem atividades e substrings indevidas',async()=>{const io=transport({pages:[[company(1,{main_cnae:'6422100'}),company(2,{city_name:'Outra cidade'}),company(3,{corporate_name:'Empresa Sobrenomes Rural'})]],detail:root=>({data:{basic_cnpj:root,partners:[]}})}),r=await discoverFamilyContext(context,{},io);assert.equal(r.candidates.length,0);assert.equal(r.qsa_reads,1)});
test('páginas e QSA respeitam teto16/concorrência2 e retomam backlog antes de outras páginas',async()=>{const io=transport({pages:[Array.from({length:100},(_,i)=>company(i+1)),Array.from({length:100},(_,i)=>company(i+101)),Array.from({length:100},(_,i)=>company(i+201))],hasMore:true}),first=await discoverFamilyContext(context,{},io);assert.equal(first.status,'PARTIAL');assert.equal(first.state.scanned_cnpjs.length,300);assert.equal(first.qsa_reads,16);assert.equal(io.max,2);assert.equal(first.state.next_page,4);assert.equal(first.state.backlog.length,284);const io2=transport(),second=await discoverFamilyContext(context,first.state,io2);assert.equal(second.qsa_reads,16);assert.equal(second.state.backlog.length,268);assert.equal(second.state.next_page,4);assert.ok(!io2.calls.some(u=>u.pathname.endsWith('/companies/search')))});
test('checkpoint500 conserva contagem cumulativa e progride até esgotar páginas',async()=>{const fingerprint=await familyQueryFingerprint(context);const previous={query_fingerprint:fingerprint,city_code:'3500001',scanned_cnpjs:Array.from({length:500},(_,i)=>company(i+1).full_cnpj),scanned_count:500,next_page:6,backlog:[],listing_exhausted:false};const io=transport({pages:[[],[],[],[],[],[company(501)]],detail:root=>({data:{basic_cnpj:root,partners:[]}})}),r=await discoverFamilyContext(context,previous,io);assert.equal(r.status,'COMPLETED');assert.equal(r.continuation,false);assert.equal(r.state.scanned_count,501);assert.equal(r.state.scanned_cnpjs.length,500);assert.ok(io.calls.some(u=>u.searchParams.get('page')==='6'))});
test('QSA de uma raiz é propagado aos estabelecimentos pertinentes sem ler raiz duas vezes',async()=>{const io=transport({pages:[[company(1),company(1,{full_cnpj:'00000001000200'})]]}),r=await discoverFamilyContext(context,{},io);assert.equal(r.qsa_reads,1);assert.equal(r.candidates.filter(c=>c.entity_type==='PERSON').length,2);assert.equal(r.state.backlog.length,0);assert.equal(io.calls.filter(u=>u.pathname.endsWith('/companies/00000001')).length,1)});
test('paginação sem has_more não vira pesquisa completa e mudança de contexto reinicia cursor',async()=>{const io=transport({missingContinuation:true}),r=await discoverFamilyContext(context,{},io);assert.equal(r.complete,false);assert.equal(r.state.next_page,1);const changed=familyContext({...lead,name:'Pessoa Outro Apelido'},'AGRO'),io2=transport({pages:[[]]}),reset=await discoverFamilyContext(changed,r.state,io2);assert.notEqual(reset.state.query_fingerprint,r.state.query_fingerprint);assert.equal(reset.state.scanned_cnpjs.length,0)});
test('QSA excedendo100 ou truncado mantém cobertura parcial sem promover parentesco',async()=>{const io=transport({detail:root=>({data:{basic_cnpj:root,partners:Array.from({length:101},()=>({partner_name:'Pessoa Sobrenome',partner_identifier:{code:'2'},is_legal_entity:false,name_redacted:false}))}})}),r=await discoverFamilyContext(context,{},io);assert.equal(r.status,'PARTIAL');assert.equal(r.complete,false);assert.equal(r.state.qsa_incomplete_roots.length,1);assert.equal(r.continuation,false)});
test('falha HTTP429 preserva a página e responde FAILED sem ausência simulada',async()=>{const r=await discoverFamilyContext(context,{}, {fetcher:async()=>new Response('',{status:429,headers:{'Retry-After':'60'}})});assert.equal(r.status,'FAILED');assert.equal(r.complete,false);assert.equal(r.state.next_page,1)});
test('Retry-After salvo impede reconsulta antecipada sem descartar backlog QSA',async()=>{const io=transport(),fetcher=async(url,init)=>String(url).match(/\/companies\/\d+$/)?new Response('',{status:429,headers:{'Retry-After':'60'}}):io.fetcher(url,init);const first=await discoverFamilyContext(context,{}, {fetcher});assert.equal(first.state.backlog.length,1);assert.equal(first.state.backlog[0].attempts,0);assert.ok(first.state.retry_not_before);let calls=0;const retry=await discoverFamilyContext(context,first.state,{fetcher:async()=>{calls++;throw Error('Unexpected query')}});assert.equal(calls,0);assert.equal(retry.status,'PARTIAL');assert.equal(retry.state.backlog.length,1)});
test('linha malformada ou sem campos de contexto mantém PARTIAL inclusive na reconsulta',async()=>{for(const row of [{full_cnpj:'invalid'},company(2,{main_cnae:null}),company(2,{city_name:null}),company(2,{corporate_name:null})]){const first=await discoverFamilyContext(context,{},transport({pages:[[row]]}));assert.equal(first.status,'PARTIAL');assert.equal(first.state.coverage_incomplete,true);const second=await discoverFamilyContext(context,first.state,{fetcher:async()=>{throw Error('No new query expected')}});assert.equal(second.status,'PARTIAL');assert.equal(second.complete,false)}});
test('teto60 de candidatos limita escrita e cobertura excedida não vira completa ao repetir',async()=>{const io=transport({detail:root=>({data:{basic_cnpj:root,partners:Array.from({length:70},(_,i)=>({partner_name:`Nome ${i} Sobrenome`,partner_identifier:{code:'2'},is_legal_entity:false,name_redacted:false}))}})}),first=await discoverFamilyContext(context,{},io);assert.equal(first.candidates.length,60);assert.equal(first.state.candidate_limit_reached,true);assert.equal(first.status,'PARTIAL');assert.equal(first.continuation,false);assert.ok(first.notes.includes('CANDIDATE_COVERAGE_LIMIT_60'));const second=await discoverFamilyContext(context,first.state,transport());assert.equal(second.status,'PARTIAL');assert.equal(second.complete,false)});
test('nova pesquisa reinicia cobertura terminal quando a fonte corrige o formato',async()=>{const first=await discoverFamilyContext(context,{},transport({pages:[[company(1,{main_cnae:null})]]}));assert.equal(first.status,'PARTIAL');assert.equal(first.continuation,false);const fresh=await discoverFamilyContext(context,{},transport());assert.equal(fresh.status,'COMPLETED');assert.equal(fresh.state.scanned_count,1);assert.equal(fresh.state.coverage_incomplete,false)});
function handlerFixture(){
 let handler,role='OWNER',user={id:'user'},foreign=false,rejected=false,evidenceStatus='VERIFIED',writeError=false,sourceStatus='CONNECTED';const writes=[],records=new Map(),discoveryStates=[];let discoveries=0;
 const id='11111111-1111-4111-8111-111111111111';
 const db={auth:{getUser:async()=>({data:{user}})},from(table){let op='read',payload,eqs={},head=false;const q={};q.select=(_s,o)=>{head=o?.head;return q};for(const n of ['single','maybeSingle','neq'])q[n]=()=>q;q.eq=(k,v)=>{eqs[k]=v;return q};for(const n of ['upsert','insert','update'])q[n]=p=>{op=n;payload=p;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  if(op!=='read'){writes.push({table,op,payload});if(writeError)return {data:null,error:{message:'WRITE_FAILED'}};if(table==='candidate_entities'){if(op==='upsert'&&!records.has(payload.id))records.set(payload.id,payload);if(op==='update'){const row=records.get(eqs.id);if(row&&row.validation_status===eqs.validation_status)records.set(eqs.id,{...row,...payload});else return {data:null,error:null}}}}
  const data=table==='profiles'?{active_organization_id:'org'}:table==='organization_members'?{role,status:'ACTIVE'}:table==='leads'?foreign?null:{...lead,id}:table==='source_registry'?{id:'source',connection_status:sourceStatus}:table==='research_runs'?foreign?null:{id}:table==='candidate_entities'?head?null:eqs.candidate_type==='FAMILY_SEARCH_PIVOT'?[...records.values()].find(c=>c.candidate_type==='FAMILY_SEARCH_PIVOT')||null:eqs.candidate_type==='FAMILY_CONTEXT_MATCH'?[...records.values()].filter(c=>c.candidate_type==='FAMILY_CONTEXT_MATCH'&&c.validation_status!=='REJECTED'):records.get(eqs.id)||null:null;
  if(table==='candidate_entities'&&eqs.id&&rejected&&data?.candidate_type==='FAMILY_CONTEXT_MATCH')data.validation_status='REJECTED';return {data,error:null,count:records.size?1:0};
 }).then(resolve,reject);return q}};
 const code=fs.readFileSync(new URL('../supabase/functions/family-cluster-discovery/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.None,target:ts.ScriptTarget.ES2022}}).outputText,{Deno:{env:{get:()=>''},serve:f=>{handler=f}},createClient:()=>db,familyContext,familyNorm,familyStableId,familyQueryFingerprint,familyResumeState,discoverFamilyContext:async(c,previous)=>{discoveries++;discoveryStates.push(previous);return {status:'COMPLETED',complete:true,candidates:[{...company(1),full_cnpj:company(1).full_cnpj,basic_cnpj:'00000001',company_name:'Empresa Sobrenome Rural',city:'Cidade QA',state:'SP',cnae_code:'0111301',cnae_description:'Cultivo',entity_type:'COMPANY',match_basis:'COMPANY_NAME'}],state:{query_fingerprint:await familyQueryFingerprint(c),scanned_cnpjs:[company(1).full_cnpj],scanned_count:1,city_code:'3500001',next_page:null,backlog:[],listing_exhausted:true},search_lineage:{geography_scope:'COMPANY_ESTABLISHMENT'},notes:[],qsa_reads:1,continuation:false}},persistSourceEvidence:async()=>({data:{id:'e',verification_status:evidenceStatus},error:null}),Response,Request,Date,console});
 return {handler,writes,records,discoveryStates,get discoveries(){return discoveries},set role(v){role=v},set user(v){user=v},set foreign(v){foreign=v},set rejected(v){rejected=v},set evidenceStatus(v){evidenceStatus=v},set writeError(v){writeError=v},set sourceStatus(v){sourceStatus=v},request(auth=true,body={}){return new Request('https://qa.test',{method:'POST',headers:auth?{Authorization:'Bearer qa'}:{},body:JSON.stringify({lead_id:id,strategy:'AGRO',...body})})}};
}
test('endpoint controlado exige sessão/papel/lead próprio antes de fonte ou escrita',async()=>{const f=handlerFixture();assert.equal((await f.handler(f.request(false))).status,401);f.user=null;assert.equal((await f.handler(f.request())).status,401);f.user={id:'user'};f.role='VIEWER';assert.equal((await f.handler(f.request())).status,403);f.role='OWNER';f.foreign=true;assert.equal((await f.handler(f.request())).status,404);assert.equal(f.discoveries,0);assert.equal(f.writes.length,0)});
test('endpoint persiste pista LOW UNVALIDATED kinshipfalse e somente tabelas autorizadas',async()=>{const f=handlerFixture(),r=await f.handler(f.request());assert.equal(r.status,200);const d=await r.json();assert.equal(d.status,'COMPLETED');assert.equal(d.pivot.metadata.search_status,'COMPLETE');assert.equal(d.candidates[0].candidate_type,'FAMILY_CONTEXT_MATCH');assert.equal(d.candidates[0].confidence,'LOW');assert.equal(d.candidates[0].metadata.kinship_confirmed,false);assert.ok(f.writes.every(w=>['candidate_entities','source_fetch_logs'].includes(w.table)));assert.ok(f.writes.filter(w=>w.table==='candidate_entities'&&w.op==='update').every(w=>!('validation_status'in w.payload)))});
test('endpoint preserva rejeição concorrente e evidência revisada; erro de escrita impede ok',async()=>{for(const mode of ['rejected','evidenceStatus']){const f=handlerFixture();if(mode==='rejected')f.rejected=true;else f.evidenceStatus='REJECTED';const r=await f.handler(f.request()),d=await r.json();assert.equal(d.candidates.length,0);assert.equal(d.status,'PARTIAL');assert.ok(!f.writes.some(w=>w.op==='update'&&w.payload.validation_status))}const f=handlerFixture();f.writeError=true;const r=await f.handler(f.request());assert.equal(r.status,500);assert.equal((await r.json()).ok,false)});
test('fonte desabilitada registra BLOCKED no pivô anterior completo preservando cursor sem nova busca',async()=>{const f=handlerFixture();await f.handler(f.request());f.sourceStatus='DISCONNECTED';const r=await f.handler(f.request()),d=await r.json();assert.equal(d.status,'BLOCKED');assert.equal(d.pivot.metadata.search_status,'BLOCKED');assert.equal(d.pivot.metadata.complete,false);assert.equal(d.pivot.metadata.scanned_count,1);assert.equal(f.discoveries,1)});
test('contador exclui candidatos de contexto antigo e não sobrescreve revisão existente',async()=>{const f=handlerFixture();f.records.set('legacy',{id:'legacy',candidate_type:'FAMILY_CONTEXT_MATCH',validation_status:'UNVALIDATED',metadata:{query_fingerprint:'old-city'}});const r=await f.handler(f.request()),d=await r.json();assert.equal(d.candidates_found,1);assert.equal(f.records.get('legacy').metadata.query_fingerprint,'old-city')});
test('candidato com mesmo ID e contexto antigo não é renovado automaticamente',async()=>{const f=handlerFixture();const first=await (await f.handler(f.request())).json(),candidate=f.records.get(first.candidates[0].id);candidate.metadata.query_fingerprint='old-city';const next=await (await f.handler(f.request())).json();assert.equal(next.candidates_found,0);assert.equal(next.candidates.length,0);assert.equal(next.status,'PARTIAL');assert.equal(candidate.metadata.query_fingerprint,'old-city')});
test('restart explícito reinicia apenas progresso e mantém candidato rejeitado',async()=>{const f=handlerFixture(),first=await (await f.handler(f.request())).json(),candidate=f.records.get(first.candidates[0].id);candidate.validation_status='REJECTED';const next=await (await f.handler(f.request(true,{restart:true}))).json();assert.equal(Object.keys(f.discoveryStates[1]).length,0);assert.equal(next.status,'PARTIAL');assert.equal(next.candidates.length,0);assert.equal(candidate.validation_status,'REJECTED');assert.ok(!f.writes.some(w=>w.op==='update'&&w.payload.validation_status))});
