import test from 'node:test';
import assert from 'node:assert/strict';
import {familyContext,discoverFamilyContext,familyQueryFingerprint} from '../supabase/functions/_shared/family-discovery.ts';

const lead={kind:'PERSON',name:'Pessoa Principal Sobrenome',city:'Cidade QA',state:'SP',segment:'Agro'};
const context=familyContext(lead);
const row=(n=1,extra={})=>({cnpj:String(n).padStart(8,'0')+'000100',razao_social:n===1?'Empresa Sobrenome Rural':'Empresa Rural '+n,cnae_fiscal:111301,cnae_fiscal_descricao:'Cultivo',municipio:'CIDADE QA',codigo_municipio_ibge:3500001,codigo_municipio:1234,uf:'SP',logradouro:'PRIVATE_ADDRESS',qsa:[{nome_socio:'Outro Nome Sobrenome',identificador_de_socio:2,qualificacao_socio:'Sócio',cnpj_cpf_do_socio:'PRIVATE_CPF',faixa_etaria:'PRIVATE_AGE'},{nome_socio:'Jurídica Sobrenome',identificador_de_socio:1},{nome_socio:'Oculto Sobrenome',identificador_de_socio:2,name_redacted:true}],...extra});
function source(pages=[{data:[row()],cursor:null}],base='timeout'){
 const calls=[];
 const fetcher=async raw=>{
  const u=new URL(raw);calls.push(u);
  if(u.hostname==='servicodados.ibge.gov.br')return Response.json([{id:3500001,nome:'Cidade QA',microrregiao:{mesorregiao:{UF:{id:35,sigla:'SP'}}}}]);
  if(u.hostname==='app.baseempresarial.com.br'){
   if(typeof base==='number')return new Response('',{status:base,headers:{'Retry-After':'60'}});
   if(base==='invalid')return Response.json({invalid:true});
   if(base==='partial'&&u.pathname.endsWith('/companies/search'))return Response.json({data:[{full_cnpj:'99999999000100',corporate_name:'Outra Empresa Sobrenome',main_cnae:'0111301',main_cnae_name:'Cultivo',city_name:'Cidade QA',city_id:3500001,state_abbreviation:'SP'}],meta:{has_more:false}});
   throw new DOMException('PRIVATE_ERROR','TimeoutError');
  }
  assert.equal(u.hostname,'minhareceita.org');assert.equal(u.searchParams.get('municipio'),'3500001');assert.equal(u.searchParams.get('uf'),'SP');assert.equal(u.searchParams.get('limit'),'100');
  const index=u.searchParams.has('cursor')?pages.findIndex(p=>p.previous===u.searchParams.get('cursor')):0;
  assert.ok(index>=0,'cursor must come from source unchanged');
  const body=pages[index];if(body.http)return new Response('',{status:body.http,headers:{'Retry-After':'90'}});if(body.raw)return new Response(body.raw,{status:200});return Response.json(body);
 };
 return {fetcher,calls};
}
test('Minha habilitada encontra empresa/QSA com origem própria, sem campos pessoais sensíveis',async()=>{const io=source(),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.status,'PARTIAL');assert.equal(r.complete,false);assert.equal(r.continuation,false);assert.equal(r.source_key,'minha_receita_rfb');assert.equal(r.search_lineage.business_provider,'MINHA_RECEITA');assert.equal(r.search_lineage.source_experimental,true);assert.equal(r.search_lineage.provider_listing_exhausted,true);assert.equal(r.candidates.length,2);assert.equal(r.qsa_reads,0);assert.ok(r.candidates.every(c=>c.source_provider==='MINHA_RECEITA'));assert.ok(!io.calls.some(u=>u.hostname==='app.baseempresarial.com.br'));assert.doesNotMatch(JSON.stringify(r),/PRIVATE_/)});
test('cursor opaco retoma três páginas por rodada sem consultar Base ou reiniciar o recorte',async()=>{const pages=Array.from({length:4},(_,i)=>({previous:i?'cursor / + '+i:undefined,data:[row(i+1)],cursor:i<3?'cursor / + '+(i+1):null})),io=source(pages),first=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(first.state.pages_scanned,3);assert.equal(first.state.scanned_count,3);assert.equal(first.state.source_cursor,'cursor / + 3');assert.equal(first.continuation,true);const io2=source(pages),second=await discoverFamilyContext(context,first.state,{...io2,minhaAvailable:true});assert.equal(second.state.scanned_count,4);assert.equal(second.state.pages_scanned,4);assert.equal(second.continuation,false);assert.equal(second.complete,false);assert.ok(io2.calls.every(u=>u.hostname==='minhareceita.org'))});
test('CNAE/localidade/token exatos e identificador físico2 excluem pistas indevidas',async()=>{const io=source([{data:[row(1,{cnae_fiscal:6422100}),row(2,{municipio:'OUTRA CIDADE'}),row(3,{razao_social:'Empresa Sobrenomes',qsa:[{nome_socio:'Pessoa Sobrenomes',identificador_de_socio:2},{nome_socio:'Pessoa Sobrenome',identificador_de_socio:1}]} )]}]),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.candidates.length,0);assert.equal(r.continuation,false);assert.equal(r.complete,false)});
test('null/ausência de cursor termina; cursor vazio/inválido não simula término',async()=>{for(const cursor of [null,undefined]){const io=source([{data:[],cursor}]),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.state.listing_exhausted,true);assert.equal(r.continuation,false)}for(const cursor of ['',4]){const io=source([{data:[],cursor}]),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.status,'FAILED');assert.equal(r.state.listing_exhausted,false);assert.equal(r.state.source_attempts.at(-1).error,'INVALID_RESPONSE')}});
test('429 preserva cursor e janela de retry sem consulta antecipada',async()=>{const io=source([{http:429}]),first=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(first.status,'FAILED');assert.ok(Date.parse(first.state.retry_not_before)>Date.now()+85000);let calls=0;const second=await discoverFamilyContext(context,first.state,{minhaAvailable:true,fetcher:async()=>{calls++;throw Error('Must wait')}});assert.equal(calls,0);assert.equal(second.status,'PARTIAL');assert.equal(second.state.listing_exhausted,false)});
test('payload acima de2MB e JSON inválido são falhas de fonte e não pesquisa vazia',async()=>{for(const body of [{raw:'x'.repeat(2*1024*1024+1)},{raw:'<html>not JSON</html>'}]){const io=source([body]),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.status,'FAILED');assert.equal(r.state.scanned_count,0);assert.equal(r.state.listing_exhausted,false);assert.ok(['RESPONSE_TOO_LARGE','INVALID_RESPONSE'].includes(r.state.source_attempts.at(-1).error))}});
test('formato incompleto persiste e limite60 continua parcial após reconsulta sem cursor',async()=>{const io=source([{data:[row(1,{qsa:Array.from({length:70},(_,i)=>({nome_socio:`Nome ${i} Sobrenome`,identificador_de_socio:2}))}),row(2,{uf:null})]}]),first=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(first.candidates.length,60);assert.equal(first.state.candidate_limit_reached,true);assert.equal(first.state.coverage_incomplete,true);const next=await discoverFamilyContext(context,first.state,{minhaAvailable:true,fetcher:async()=>{throw Error('No new request')}});assert.equal(next.status,'PARTIAL');assert.equal(next.complete,false);assert.equal(next.continuation,false)});
test('Base parcial com timeout QSA troca fonte e preserva candidato empresarial observado',async()=>{const io=source(undefined,'partial'),r=await discoverFamilyContext(context,{}, {...io,minhaAvailable:true});assert.equal(r.source_provider,'MINHA_RECEITA');assert.equal(r.search_lineage.provider_switch,true);assert.equal(r.search_lineage.previous_provider_transport_failed,true);assert.ok(r.candidates.some(c=>c.full_cnpj==='99999999000100'&&c.source_provider==='BASE_EMPRESARIAL'));assert.ok(r.candidates.some(c=>c.source_provider==='MINHA_RECEITA'));assert.equal(r.state.scanned_count,1);assert.ok(r.state.source_attempts.some(a=>a.provider==='BASE_EMPRESARIAL'&&a.error==='TIMEOUT'))});
test('erro Base salvo inicia Minha diretamente e reinicia contagem daquele fornecedor',async()=>{const fingerprint=await familyQueryFingerprint(context),previous={query_fingerprint:fingerprint,source_provider:'BASE_EMPRESARIAL',city_code:'3500001',scanned_cnpjs:['99999999000100'],scanned_count:200,next_page:3,listing_exhausted:false,complete:false,source_attempts:[{provider:'BASE_EMPRESARIAL',error:'TIMEOUT',status:null}]},io=source(),r=await discoverFamilyContext(context,previous,{...io,minhaAvailable:true});assert.equal(r.state.source_provider,'MINHA_RECEITA');assert.equal(r.state.scanned_count,1);assert.ok(io.calls.every(u=>u.hostname==='minhareceita.org'));assert.ok(r.notes.includes('SOURCE_PROVIDER_SWITCH_RESTARTED'))});
test('403/429/formato Base não mudam para outro fornecedor e ambos desabilitados não consultam',async()=>{for(const base of [403,429,'invalid']){const io=source(undefined,base),r=await discoverFamilyContext(context,{}, {...io,minhaAvailable:true});assert.equal(r.source_provider,'BASE_EMPRESARIAL');assert.ok(!io.calls.some(u=>u.hostname==='minhareceita.org'))}let calls=0;const r=await discoverFamilyContext(context,{}, {baseAvailable:false,minhaAvailable:false,fetcher:async()=>{calls++;throw Error('Disabled')}});assert.equal(r.status,'BLOCKED');assert.equal(calls,0)});
test('Base consome no máximo30s e fallback usa o restante do orçamento45s',async()=>{const io=source();let now=0;const r=await discoverFamilyContext(context,{}, {minhaAvailable:true,now:()=>now,fetcher:async(url,init)=>{if(String(url).includes('app.baseempresarial.com.br')){now=30000;throw new DOMException('timeout','TimeoutError')}return io.fetcher(url,init)}});assert.equal(r.source_provider,'MINHA_RECEITA');assert.equal(r.candidates.length,2);assert.equal(r.state.source_attempts.find(a=>a.provider==='BASE_EMPRESARIAL').duration_ms,30000);assert.ok(now<=45000)});
test('checkpoint500 permite avançar e cursor estacionado encerra continuação sem progresso',async()=>{const query_fingerprint=await familyQueryFingerprint(context),previous={query_fingerprint,source_provider:'MINHA_RECEITA',city_code:'3500001',source_cursor:'opaque500',scanned_cnpjs:Array.from({length:500},(_,i)=>row(i+1).cnpj),scanned_count:500,next_page:6,pages_scanned:5,listing_exhausted:false},io=source([{previous:'opaque500',data:[row(501)],cursor:null}]),r=await discoverFamilyContext(context,previous,{...io,minhaAvailable:true});assert.equal(r.state.scanned_count,501);assert.equal(r.state.scanned_cnpjs.length,500);assert.equal(r.continuation,false);const stalled=source([{previous:'opaque500',data:[],cursor:'opaque500'}]),s=await discoverFamilyContext(context,previous,{...stalled,minhaAvailable:true});assert.equal(s.state.source_cursor_stalled,true);assert.equal(s.continuation,false);const next=await discoverFamilyContext(context,s.state,{minhaAvailable:true,fetcher:async()=>{throw Error('No stalled requests')}});assert.equal(next.continuation,false)});
test('nome QSA mascarado sem flag ou sobrenome isolado não gera pessoa',async()=>{const io=source([{data:[row(1,{qsa:['***** Sobrenome','# [REDACTED] Sobrenome','Sobrenome'].map(nome_socio=>({nome_socio,identificador_de_socio:2}))})],cursor:null}]),r=await discoverFamilyContext(context,{}, {...io,baseAvailable:false,minhaAvailable:true});assert.equal(r.candidates.filter(c=>c.entity_type==='PERSON').length,0);assert.equal(r.candidates.filter(c=>c.entity_type==='COMPANY').length,1)});
