import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {persistSourceEvidence} from '../supabase/functions/_shared/source-evidence.ts';import {fetchSourceJson} from '../supabase/functions/_shared/source-operations.ts';
const LEAD='11111111-1111-4111-8111-111111111111',ORG='22222222-2222-4222-8222-222222222222',SOURCE='33333333-3333-4333-8333-333333333333',DOC='44444444-4444-4444-8444-444444444444',CAND='55555555-5555-4555-8555-555555555555',CNPJ='32901144000105';
const original={basic_cnpj:'32901144',full_cnpj:CNPJ,company_name:'Empresa Teste',partner_name:'JOAO DA SILVA',source_url:'https://baseempresarial.com.br/empresa/'+CNPJ};
const candidate=(status='UNVALIDATED',metadata=original)=>({id:CAND,organization_id:ORG,lead_id:LEAD,entity_type:'COMPANY',candidate_type:'RFB_QSA_NAME_MATCH',label:'Empresa Teste',candidate_reason:'Pista societária',confidence:'MEDIUM',validation_status:status,metadata:{...metadata}});
function fixture({reviewed=false,companyFails=false,candidateReadFails=false,role='OWNER',kind='PERSON',existing=[],companyCnpj=CNPJ,companyName='Empresa Teste',evidenceFails=false,candidateWriteFails=false,concurrentReject=false,boundDocs=[],duplicates=false}={}){
 let handler;const tables=[],docs=new Map(boundDocs.map(doc=>[doc.dedupe_key||doc.id,structuredClone(doc)])),candidates=new Map(existing.map(row=>[row.id,structuredClone(row)]));let sourceCalls=0;
 const matches=(row,filters)=>Object.entries(filters).every(([key,value])=>key==='metadata'?JSON.stringify(row.metadata)===JSON.stringify(JSON.parse(value)):row[key]===value);
 const db={auth:{getUser:async()=>({data:{user:{id:LEAD}}})},from(table){let action='read',payload,options,one=false;const filters={};const q={select:()=>q,eq:(k,v)=>{filters[k]=v;return q},single:()=>{one=true;return q},maybeSingle:()=>{one=true;return q}};for(const m of ['insert','upsert','update'])q[m]=(p,o)=>{action=m;payload=JSON.parse(JSON.stringify(p));options=o;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  tables.push({table,action,payload,filters:structuredClone(filters),options});let data=null,error=null;
  if(table==='profiles')data={active_organization_id:ORG};else if(table==='organization_members')data={status:'ACTIVE',role};else if(table==='leads')data={id:LEAD,name:'João da Silva',city:'Barretos',state:'SP',kind};else if(table==='source_registry')data={id:SOURCE};
  else if(table==='evidence'){
   if(evidenceFails&&action!=='read')error={message:'failed'};
   else if(action!=='read'){if(!docs.has(payload.dedupe_key))docs.set(payload.dedupe_key,{...payload,id:DOC,verification_status:reviewed?'REJECTED':payload.verification_status})}
   const values=[...docs.values()].filter(row=>matches(row,filters));data=one?(values[0]||null):values;
  }else if(table==='candidate_entities'){
   if(action==='read'&&candidateReadFails)error={message:'failed'};
   if(action!=='read'&&candidateWriteFails)error={message:'failed'};
   if(!error&&action==='upsert'&&!candidates.has(payload.id))candidates.set(payload.id,payload);
   if(!error&&action==='update'){
    if(concurrentReject){const old=candidates.get(filters.id);if(old){old.validation_status='REJECTED';old.metadata={...old.metadata,rejected_by_user:true,rejection_reason:'Revisão simultânea'};concurrentReject=false}}
    const found=[...candidates.values()].find(row=>matches(row,filters));if(found){Object.assign(found,payload);data=found}
   }else if(action==='read'){const values=[...candidates.values()].filter(row=>matches(row,filters));data=one?(values[0]||null):values}
  }
  return{data:data?structuredClone(data):data,error};
 }).then(resolve,reject);return q}};
 const fetcher=async url=>{sourceCalls++;return url.includes('/partners?')?Response.json({data:Array.from({length:duplicates?2:1},()=>({partner_name:'JOAO DA SILVA',basic_cnpj:'32901144',age_group:{name:'PRIVATE_AGE'}}))}):companyFails?Response.json({error:'fail'},{status:503}):Response.json({data:{corporate_name:companyName,establishments:[{full_cnpj:companyCnpj,main_branch_office:{code:'1'},address:{city:{name:'Bauru'},state:{abbreviation:'SP'}}}]}})};
 const source=fs.readFileSync(new URL('../supabase/functions/name-company-discovery/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:f=>handler=f},createClient:()=>db,fetchSourceJson:(url,valid,options)=>fetchSourceJson(url,valid,{...options,fetcher,wait:async()=>{}}),persistSourceEvidence,Response,Request,AbortSignal,crypto,TextEncoder,console});
 return{call:()=>handler(new Request('https://qa.supabase.co',{method:'POST',headers:{Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({lead_id:LEAD})})),tables,docs,candidates,get sourceCalls(){return sourceCalls}};
}
const writes=f=>f.tables.filter(row=>row.action!=='read'),candidateWrites=f=>writes(f).filter(row=>row.table==='candidate_entities');
test('Reviewed source evidence is retained and cannot create an active identity candidate',async()=>{const f=fixture({reviewed:true}),r=await f.call(),d=await r.json();assert.equal(r.status,200);assert.equal(d.complete,false);assert.equal(d.status,'PARTIAL');assert.equal(d.candidates.length,0);assert.equal(candidateWrites(f).length,0);assert.equal([...f.docs.values()][0].verification_status,'REJECTED')});
test('Canonical discovery persists immutable evidence before its exactly bound candidate and honest location context',async()=>{const f=fixture(),r=await f.call(),d=await r.json();assert.equal(r.status,200);assert.equal(d.candidates[0].evidence_id,DOC);assert.equal(d.candidates[0].evidence_status,'VERIFIED');assert.equal(d.candidates[0].search_lineage.match_scope,'STATE');assert.equal(d.candidates[0].search_lineage.city_constraint_matched,false);assert.equal(d.search_lineage.geographic_filter_applied,false);assert.equal(d.search_lineage.query_name,'JOAO DA SILVA');const changes=writes(f);assert.ok(changes.findIndex(row=>row.table==='evidence')<changes.findIndex(row=>row.table==='candidate_entities'));const doc=changes.find(row=>row.table==='evidence').payload;assert.deepEqual(JSON.parse(doc.raw_reference),{schema_version:2,basic_cnpj:'32901144',full_cnpj:CNPJ,partner_name:'JOAO DA SILVA',company_name:'Empresa Teste',query_name:'JOAO DA SILVA'});assert.equal(JSON.stringify(doc).includes('PRIVATE_AGE'),false);assert.equal([...f.candidates.values()][0].metadata.evidence_id,DOC)});
test('Failed company reads retain partial coverage instead of claiming no match',async()=>{const f=fixture({companyFails:true}),r=await f.call(),d=await r.json();assert.equal(r.status,200);assert.equal(d.complete,false);assert.equal(d.status,'PARTIAL');assert.equal(d.candidates_found,0);assert.equal(writes(f).find(x=>x.table==='source_fetch_logs').payload.result_status,'PARTIAL')});
test('Review read failures, unsupported roles and COMPANY leads stop before source/candidate writes',async()=>{const f=fixture({candidateReadFails:true});assert.equal((await f.call()).status,500);assert.equal(writes(f).length,0);for(const change of [{role:'VIEWER'},{role:'UNKNOWN'},{kind:'COMPANY'}]){const f=fixture(change);assert.equal((await f.call()).status,change.kind?409:403);assert.equal(writes(f).length,0);assert.equal(f.sourceCalls,0)}});
test('Confirmed and rejected candidates keep their original CNPJ, review and metadata when the canonical matrix changes',async()=>{for(const status of ['CONFIRMED','REJECTED']){const row=candidate(status),f=fixture({existing:[row],companyCnpj:'32901144000296'}),r=await f.call(),data=await r.json();assert.equal(r.status,200);assert.equal(data.candidates[0]?.full_cnpj,CNPJ);assert.equal(data.candidates[0]?.validation_status,status);assert.equal(candidateWrites(f).length,0);assert.deepEqual(f.candidates.get(CAND),row)}});
test('Confirmed legacy candidate recovers only the exact citation binding without changing identity or review metadata',async()=>{const row=candidate('CONFIRMED',{...original,confirmed_by_user:true,assigned_initial_cnpj:true,confirmed_at:'2026-09-01'}),f=fixture({existing:[row]});assert.equal((await f.call()).status,200);const saved=f.candidates.get(CAND);assert.equal(saved.validation_status,'CONFIRMED');assert.deepEqual(saved.metadata,{...row.metadata,evidence_id:DOC});const update=candidateWrites(f)[0];assert.deepEqual(Object.keys(update.payload),['metadata']);assert.equal(update.filters.validation_status,'CONFIRMED');assert.equal(update.filters.metadata,JSON.stringify(row.metadata))});
test('Requery cannot change the citation of an already bound confirmed candidate',async()=>{const row=candidate('CONFIRMED',{...original,evidence_id:DOC}),f=fixture({existing:[row],boundDocs:[{id:DOC,organization_id:ORG,lead_id:LEAD,verification_status:'VERIFIED'}]});assert.equal((await f.call()).status,200);assert.equal(writes(f).some(row=>row.table==='evidence'||row.table==='candidate_entities'),false);assert.deepEqual(f.candidates.get(CAND),row)});
test('Bound and legacy rejected documents block rebinding instead of selecting a newer verified record',async()=>{const row=candidate('UNVALIDATED',{...original,evidence_id:DOC}),f=fixture({existing:[row],boundDocs:[{id:DOC,organization_id:ORG,lead_id:LEAD,verification_status:'REJECTED'}]});const r=await f.call();assert.equal((await r.json()).status,'PARTIAL');assert.equal(candidateWrites(f).length,0);assert.deepEqual(f.candidates.get(CAND),row);const legacy=candidate(),g=fixture({existing:[legacy],boundDocs:[{id:DOC,organization_id:ORG,lead_id:LEAD,source_registry_id:SOURCE,document_type:'RFB_QSA_NAME_DISCOVERY',source_url:original.source_url,raw_reference:'partner_name=JOAO DA SILVA; basic_cnpj=32901144',verification_status:'REJECTED'}]});assert.equal((await g.call()).status,200);assert.equal(candidateWrites(g).length,0);assert.equal(writes(g).some(row=>row.table==='evidence'),false)});
test('A concurrent rejection wins over discovery metadata refresh and returned state is read back',async()=>{const f=fixture({existing:[candidate()],concurrentReject:true}),r=await f.call(),d=await r.json();assert.equal(r.status,200);assert.equal(d.status,'PARTIAL');assert.equal(d.candidates[0].validation_status,'REJECTED');assert.equal(f.candidates.get(CAND).metadata.rejected_by_user,true);assert.equal(f.candidates.get(CAND).metadata.evidence_id,undefined)});
test('Evidence and candidate write failures return explicit errors without making an unsupported identity write',async()=>{const f=fixture({evidenceFails:true});assert.equal((await f.call()).status,500);assert.equal(candidateWrites(f).length,0);const g=fixture({candidateWriteFails:true});assert.equal((await g.call()).status,500);assert.equal(g.candidates.size,0);assert.equal([...g.docs.values()].length,1)});
test('Invalid or mismatched full CNPJ rows are partial source failures and never become candidates',async()=>{for(const companyCnpj of ['32901144000100','84429695000111']){const f=fixture({companyCnpj}),r=await f.call(),d=await r.json();assert.equal(d.status,'PARTIAL');assert.equal(d.candidates_found,0);assert.equal(candidateWrites(f).length,0)}});
test('Duplicate source rows and requeries keep a deterministic own-scope candidate with no duplicate identity',async()=>{const f=fixture({duplicates:true});assert.equal((await f.call()).status,200);assert.equal(f.candidates.size,1);const id=[...f.candidates.keys()][0];assert.match(id,/^[0-9a-f-]{36}$/);assert.equal((await f.call()).status,200);assert.equal(f.candidates.size,1);assert.equal([...f.candidates.keys()][0],id);assert.equal([...f.candidates.values()][0].organization_id,ORG)});
