import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {persistSourceEvidence} from '../supabase/functions/_shared/source-evidence.ts';import {fetchSourceJson} from '../supabase/functions/_shared/source-operations.ts';
function fixture({rejected=true,companyFails=false,candidateReadFails=false,role='OWNER'}={}){
 let handler,evidenceWrites=0;const tables=[],id='qa-lead';
 const db={auth:{getUser:async()=>({data:{user:{id}}})},from(table){let action='read',payload;const q={};for(const m of ['select','eq','single','maybeSingle'])q[m]=()=>q;for(const m of ['insert','upsert','update'])q[m]=p=>{action=m;payload=p;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  if(action!=='read'){tables.push({table,action,payload});if(table==='evidence')evidenceWrites++}
  const data=table==='profiles'?{active_organization_id:'org'}:table==='organization_members'?{status:'ACTIVE',role}:table==='leads'?{id,name:'João da Silva',city:'Barretos',state:'SP'}:table==='source_registry'?{id:'source'}:table==='candidate_entities'?(action==='read'?[]:{id:'candidate'}):table==='evidence'?{id:'reviewed-evidence',verification_status:rejected?'REJECTED':'VERIFIED'}:null;
  return {data,error:table==='candidate_entities'&&action==='read'&&candidateReadFails?{message:'failed'}:null};
 }).then(resolve,reject);return q}};
 const fetcher=async url=>url.includes('/partners?')?Response.json({data:[{partner_name:'JOAO DA SILVA',basic_cnpj:'32901144'}]}):companyFails?Response.json({error:'fail'},{status:503}):Response.json({data:{corporate_name:'Empresa Teste',establishments:[{full_cnpj:'32901144000105',main_branch_office:{code:'1'},address:{city:{name:'Bauru'},state:{abbreviation:'SP'}}}]}});
 const source=fs.readFileSync(new URL('../supabase/functions/name-company-discovery/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:f=>handler=f},createClient:()=>db,fetchSourceJson:(url,valid,options)=>fetchSourceJson(url,valid,{...options,fetcher,wait:async()=>{}}),persistSourceEvidence,Response,Request,AbortSignal,crypto,TextEncoder,console});
 return {call:()=>handler(new Request('https://qa.supabase.co',{method:'POST',headers:{Authorization:'Bearer qa','Content-Type':'application/json'},body:JSON.stringify({lead_id:id})})),tables,evidenceWrites:()=>evidenceWrites};
}
test('handler nominal preserva evidência rejeitada e explicita cidade que não corresponde',async()=>{const f=fixture();const r=await f.call();assert.equal(r.status,200);const d=await r.json();assert.equal(f.evidenceWrites(),0);assert.equal(d.candidates[0].evidence_status,'REJECTED');assert.equal(d.candidates[0].search_lineage.match_scope,'STATE');assert.equal(d.candidates[0].search_lineage.city_constraint_matched,false);assert.equal(d.search_lineage.geographic_filter_applied,false);assert.equal(d.search_lineage.query_name,'JOAO DA SILVA')});
test('falha ao ler empresa mantém pesquisa parcial e não afirma ausência',async()=>{const f=fixture({companyFails:true});const r=await f.call();const d=await r.json();assert.equal(r.status,200);assert.equal(d.complete,false);assert.equal(d.status,'PARTIAL');assert.equal(d.candidates_found,0);assert.equal(f.tables.find(x=>x.table==='source_fetch_logs').payload.result_status,'PARTIAL')});
test('busca nominal interrompe quando não consegue ler revisão e nega VIEWER sem escrita',async()=>{const f=fixture({candidateReadFails:true});assert.equal((await f.call()).status,500);assert.equal(f.evidenceWrites(),0);const v=fixture({role:'VIEWER'});assert.equal((await v.call()).status,403);assert.equal(v.tables.length,0)});
