import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {webcrypto} from 'node:crypto';
import {validQsaDiscoveryEvidence} from '../supabase/functions/_shared/qsa-evidence.ts';
const ORG='11111111-1111-4111-8111-111111111111',ID='22222222-2222-4222-8222-222222222222',DOC='33333333-3333-4333-8333-333333333333',SOURCE='44444444-4444-4444-8444-444444444444',COMPANY='55555555-5555-4555-8555-555555555555';
const lead={id:ID,organization_id:ORG,kind:'PERSON',name:'João Pereira',identity_status:'PENDING'};
const candidate={id:ID,organization_id:ORG,lead_id:ID,entity_type:'COMPANY',candidate_type:'RFB_QSA_NAME_MATCH',validation_status:'SUPPORTED',metadata:{full_cnpj:'32901144000105',basic_cnpj:'32901144',partner_name:'JOAO PEREIRA',company_name:'Empresa QA',evidence_id:DOC,identity_engine:{score:80,decision:'SUPPORTED',ambiguous:false}}};
const document={id:DOC,organization_id:ORG,lead_id:ID,source_registry_id:SOURCE,verification_status:'VERIFIED',document_type:'RFB_QSA_NAME_DISCOVERY',source_url:'https://baseempresarial.com.br/empresa/32901144000105',raw_reference:JSON.stringify({schema_version:2,full_cnpj:'32901144000105',basic_cnpj:'32901144',partner_name:'João Pereira',query_name:'JOAO PEREIRA',company_name:'Empresa QA'})};
test('document binding accepts exact JSON and scoped legacy occurrence with accent normalization',()=>{assert.equal(validQsaDiscoveryEvidence(candidate,lead,document,'base_empresarial_rfb'),true);assert.equal(validQsaDiscoveryEvidence(candidate,lead,{...document,raw_reference:'partner_name=JOAO PEREIRA; basic_cnpj=32901144'},'base_empresarial_rfb'),true)});
test('failed/pending/foreign/wrong source/URL/type/missing or mismatched JSON cannot support identity',()=>{for(const change of [{verification_status:'FAILED'},{verification_status:'PENDING'},{lead_id:ORG},{organization_id:ID},{id:ID},{document_type:'CNPJ_REGISTRY'},{source_url:'https://baseempresarial.com.br/empresa/32901144000100'},{raw_reference:'{}'},{raw_reference:'null'},{raw_reference:document.raw_reference.replace('Empresa QA','Outra Empresa')}])assert.equal(validQsaDiscoveryEvidence(candidate,lead,{...document,...change},'base_empresarial_rfb'),false);assert.equal(validQsaDiscoveryEvidence(candidate,lead,document,'brasilapi_cnpj'),false);assert.equal(validQsaDiscoveryEvidence(candidate,{...lead,name:'Outro Nome'},document,'base_empresarial_rfb'),false);assert.equal(validQsaDiscoveryEvidence(candidate,{...lead,kind:'COMPANY'},document,'base_empresarial_rfb'),false)});
function fixture(endpoint,options={}){const state={role:'OWNER',rpcError:false,cas:false,evidenceStatus:'VERIFIED',reviewRequired:false,upstreamOk:true,wrongCnpj:false,docValid:true,...options},writes=[],calls=[],docs=[];let handler;
 const db={auth:{getUser:async()=>({data:{user:{id:ID}}})},rpc:async(name,args)=>{calls.push({name,args});return {data:state.cas?{applied:false}:name==='apply_qsa_candidate_company_link'?{ok:true,validation_status:'SUPPORTED',link_status:'SUPPORTED',relationship_id:ID}:{applied:true,validation_status:'SUPPORTED'},error:state.rpcError?{message:'review concurrently rejected'}:null}},from(table){let mode='read',payload;const q={select:()=>q,eq:()=>q,neq:()=>q,in:()=>q,order:()=>q,limit:()=>q,maybeSingle:()=>q,single:()=>q,insert:p=>{mode='insert';payload=p;return q},update:p=>{mode='update';payload=p;return q},upsert:p=>{mode='upsert';payload=p;return q}};q.then=(resolve,reject)=>Promise.resolve().then(()=>{if(mode!=='read')writes.push({table,mode,payload});const data=table==='profiles'?{active_organization_id:ORG}:table==='organization_members'?{status:'ACTIVE',role:state.role}:table==='leads'?lead:table==='candidate_entities'?endpoint==='cross-validate-identity-links'?[candidate,{...candidate,id:COMPANY}]:[candidate]:table==='source_registry'?{id:SOURCE}:table==='evidence'?{...document,verification_status:state.docValid?'VERIFIED':'FAILED'}:table==='research_runs'?{id:ID}:table==='research_job_queue'?{id:ID,status:'COMPLETED',created_at:new Date().toISOString()}:null;return {data,error:null}}).then(resolve,reject);return q}};
 const source=fs.readFileSync(new URL(`../supabase/functions/${endpoint}/index.ts`,import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,validQsaDiscoveryEvidence,persistSourceEvidence:async(_db,p)=>{docs.push(p);return {data:{id:DOC,verification_status:state.evidenceStatus},error:null}},fetchSourceJson:async()=>({ok:state.upstreamOk,status:state.upstreamOk?200:429,error:state.upstreamOk?null:'HTTP_429',data:{cnpj:state.wrongCnpj?'32901144000100':'32901144000105',qsa:[{identificador_de_socio:2,nome_socio:'João Pereira',cnpj_cpf_do_socio:'***123456**'}]}}),fetch:async()=>Response.json({company_id:COMPANY,evidence_id:DOC,...(state.reviewRequired?{status:'REVIEW_REQUIRED'}:{})}),Response,Request,AbortSignal,URL,crypto:webcrypto,TextEncoder,Uint8Array,Map,Date,setTimeout});return {handler,state,writes,calls,docs};
}
const request=()=>new Request('https://qa.test',{method:'POST',headers:{Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({lead_id:ID})});
test('cluster applies current atomic attribution; never performs distributed link/relation writes',async()=>{const f=fixture('enrich-supported-identity-cluster'),r=await f.handler(request()),b=await r.json();assert.equal(r.status,200);assert.equal(f.calls[0].name,'apply_qsa_candidate_company_link');assert.equal(b.companies[0].validation_status,'SUPPORTED');assert.equal(b.companies[0].link_status,'SUPPORTED');assert.equal(f.writes.length,0)});
test('cluster concurrent rejection or reviewed registry produces no attribution or queued research',async()=>{for(const options of [{rpcError:true},{reviewRequired:true}]){const f=fixture('enrich-supported-identity-cluster',options),r=await f.handler(request()),b=await r.json();assert.equal(b.enriched_companies,0);assert.equal(r.status,502);assert.equal(f.writes.length,0);if(options.reviewRequired)assert.equal(f.calls.length,0)}});
test('cross binds real provider URL then atomically CASes the exact candidate snapshot',async()=>{const f=fixture('cross-validate-identity-links'),r=await f.handler(request()),b=await r.json();assert.equal(r.status,200);assert.equal(b.groups[0].size,2);assert.ok(f.calls.every(c=>c.name==='record_qsa_cross_validation'&&c.args.p_expected_status==='SUPPORTED'&&c.args.p_expected_meta.evidence_id===DOC));assert.ok(f.docs.every(d=>d.source_url==='https://brasilapi.com.br/api/cnpj/v1/32901144000105'));assert.equal(f.writes.length,0)});
test('cross stale CAS, reviewed evidence, invalid registry or discovery does not publish support',async()=>{for(const options of [{cas:true},{rpcError:true},{evidenceStatus:'FAILED'},{wrongCnpj:true},{docValid:false},{upstreamOk:false}]){const f=fixture('cross-validate-identity-links',options),r=await f.handler(request()),b=await r.json();assert.equal(b.groups.length,0);assert.equal(f.writes.length,0);if(options.evidenceStatus||options.wrongCnpj||options.docValid===false||options.upstreamOk===false)assert.equal(f.calls.length,0)}});
test('automatic QSA writers reject viewer and unknown roles before attribution',async()=>{for(const endpoint of ['cross-validate-identity-links','enrich-supported-identity-cluster'])for(const role of ['VIEWER','UNKNOWN']){const f=fixture(endpoint,{role}),r=await f.handler(request());assert.equal(r.status,403);assert.equal(f.calls.length,0);assert.equal(f.docs.length,0)}});
