import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const USER='11111111-1111-4111-8111-111111111111',ORG='22222222-2222-4222-8222-222222222222',LEAD='33333333-3333-4333-8333-333333333333',CAND='44444444-4444-4444-8444-444444444444',DOC='55555555-5555-4555-8555-555555555555',COMPANY='66666666-6666-4666-8666-666666666666',REGISTRY='77777777-7777-4777-8777-777777777777',SOURCE='88888888-8888-4888-8888-888888888888',CNPJ='32901144000105';
const reference={schema_version:2,basic_cnpj:CNPJ.slice(0,8),full_cnpj:CNPJ,partner_name:'JOAO DA SILVA',company_name:'Empresa QA',query_name:'JOAO DA SILVA'};
function fixture(endpoint='confirm-company-candidate',overrides={}){
 let handler;const reads=[],writes=[],events=[];
 const state={user:{id:USER},role:'OWNER',org:ORG,candidate:{id:CAND,organization_id:ORG,lead_id:LEAD,entity_type:'COMPANY',candidate_type:'RFB_QSA_NAME_MATCH',validation_status:'UNVALIDATED',metadata:{evidence_id:DOC,basic_cnpj:CNPJ.slice(0,8),full_cnpj:CNPJ,partner_name:'JOAO DA SILVA',company_name:'Empresa QA'}},lead:{id:LEAD,organization_id:ORG,name:'João da Silva',kind:'PERSON',initial_cnpj:'84429695000111'},document:{id:DOC,organization_id:ORG,lead_id:LEAD,verification_status:'VERIFIED',source_registry_id:SOURCE,document_type:'RFB_QSA_NAME_DISCOVERY',source_url:'https://baseempresarial.com.br/empresa/'+CNPJ,raw_reference:JSON.stringify(reference)},source:{id:SOURCE,key:'base_empresarial_rfb'},enrichment:{ok:true,company_id:COMPANY,evidence_id:REGISTRY},rpcData:{ok:true},rpcError:null,...overrides};
 const db={auth:{getUser:async()=>({data:{user:state.user}})},from(table){let mode='read',payload;const filters={};const q={};for(const m of ['select','single','maybeSingle'])q[m]=()=>q;q.eq=(k,v)=>{filters[k]=v;return q};for(const m of ['insert','update','upsert'])q[m]=p=>{mode=m;payload=p;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  (mode==='read'?reads:writes).push({table,mode,payload,filters});let data=table==='profiles'?{active_organization_id:state.org}:table==='organization_members'?{status:'ACTIVE',role:state.role}:table==='candidate_entities'?state.candidate:table==='leads'?state.lead:table==='evidence'?state.document:table==='source_registry'?state.source:null;
  if(data&&['candidate_entities','leads','evidence','source_registry'].includes(table)&&Object.entries(filters).some(([k,v])=>data[k]!==v))data=null;
  return{data,error:state.readError===table?{message:'PRIVATE_DATABASE_READ'}:null};
 }).then(resolve,reject);return q},rpc:async(name,args)=>{events.push({kind:'rpc',name,args:JSON.parse(JSON.stringify(args))});return{data:state.rpcData,error:state.rpcError}}};
 const source=fs.readFileSync(new URL(`../supabase/functions/${endpoint}/index.ts`,import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:fn=>handler=fn},createClient:()=>db,fetch:async(url,init)=>{events.push({kind:'fetch',url,body:JSON.parse(init.body)});if(state.fetchThrows)throw Error('PRIVATE_UPSTREAM_ERROR');return Response.json(url.includes('identity-resolution')?(state.recompute||{ok:true,lead_status:'CAUTION'}):state.enrichment,{status:url.includes('identity-resolution')?(state.recomputeHttp||200):(state.enrichmentHttp||200)})},Request,Response,AbortSignal,console});
 return{state,reads,writes,events,call:async(body={},auth=true)=>handler(new Request('https://qa.test',{method:'POST',headers:auth?{Authorization:'Bearer synthetic','Content-Type':'application/json'}:{'Content-Type':'application/json'},body:JSON.stringify({candidate_id:CAND,action:'REJECT',reason:'Vínculo selecionado incorretamente',...body})}))};
}
test('QSA confirmation requires an authenticated operator and own person/company candidate context',async()=>{
 for(const [change,auth,status] of [[{},false,401],[{user:null},true,401],[{role:'VIEWER'},true,403],[{role:'UNKNOWN'},true,403],[{org:null},true,409],[{candidate:null},true,404],[{lead:null},true,404]]){const f=fixture(undefined,change);assert.equal((await f.call({},auth)).status,status);assert.equal(f.events.length,0);assert.equal(f.writes.length,0)}
 const f=fixture();f.state.lead.kind='COMPANY';assert.equal((await f.call()).status,409);assert.equal(f.events.length,0);
});
test('Rejected QSA candidates never reach a source or review mutation',async()=>{const f=fixture();f.state.candidate.validation_status='REJECTED';assert.equal((await f.call()).status,409);assert.equal(f.events.length,0);assert.equal(f.writes.length,0)});
test('A legacy candidate without an evidence binding asks for requery instead of selecting a latest document',async()=>{const f=fixture();delete f.state.candidate.metadata.evidence_id;const response=await f.call();assert.equal(response.status,409);assert.equal((await response.json()).code,'DISCOVERY_REQUERY_REQUIRED');assert.equal(f.reads.some(r=>r.table==='evidence'),false);assert.equal(f.events.length,0)});
test('Discovery document must be verified and scoped to its exact company and QSA name',async()=>{
 for(const change of [{verification_status:'REJECTED'},{organization_id:'other'},{lead_id:'other'},{document_type:'WEB_PAGE'},{source_url:'https://baseempresarial.com.br/empresa/84429695000111'},{raw_reference:JSON.stringify({...reference,full_cnpj:'84429695000111'})},{raw_reference:JSON.stringify({...reference,partner_name:'JOSE PEREIRA'})},{raw_reference:JSON.stringify({...reference,query_name:'JOSE PEREIRA'})},{raw_reference:'malformed'}]){const f=fixture();Object.assign(f.state.document,change);assert.equal((await f.call()).status,409);assert.equal(f.events.length,0);assert.equal(f.writes.length,0)}
 const f=fixture();f.state.source.key='other';assert.equal((await f.call()).status,409);assert.equal(f.events.length,0);
});
test('Strict legacy raw reference is supported only after the exact binding was persisted',async()=>{const f=fixture();f.state.document.raw_reference='partner_name=JOAO DA SILVA; basic_cnpj=32901144';assert.equal((await f.call()).status,200);assert.equal(f.events.at(-1).name,'review_qsa_name_candidate')});
test('A changed person name or company root blocks confirmation before enrichment',async()=>{for(const alter of [f=>f.state.lead.name='José Pereira',f=>f.state.candidate.metadata.basic_cnpj='84429695']){const f=fixture();alter(f);assert.equal((await f.call()).status,409);assert.equal(f.events.length,0)}});
test('Every failed database read aborts without mutation or exposing database messages',async()=>{for(const table of ['profiles','organization_members','candidate_entities','leads','evidence','source_registry']){const f=fixture(undefined,{readError:table}),r=await f.call();assert.equal(r.status,500);assert.equal(f.events.length,0);assert.equal(f.writes.length,0);assert.doesNotMatch(await r.text(),/PRIVATE_DATABASE_READ/)}});
test('Enrichment failure and HTTP200 review-required cannot produce a confirmation',async()=>{for(const change of [{enrichmentHttp:502},{fetchThrows:true},{enrichment:{ok:true,status:'REVIEW_REQUIRED',company_id:COMPANY,evidence_id:REGISTRY}},{enrichment:{ok:true,company_id:COMPANY}},{enrichment:{ok:false,company_id:COMPANY,evidence_id:REGISTRY}}]){const f=fixture(undefined,change),r=await f.call();assert.equal(r.status,change.enrichmentHttp||change.fetchThrows?502:409);assert.equal(f.events.filter(e=>e.kind==='rpc').length,0);assert.equal(f.writes.length,0);assert.doesNotMatch(await r.text(),/PRIVATE_UPSTREAM_ERROR/)}});
test('Confirmation uses only the transactional RPC after enrichment and preserves a different manual initial CNPJ',async()=>{const f=fixture(),r=await f.call();assert.equal(r.status,200);assert.deepEqual(f.events.map(e=>e.kind),['fetch','rpc']);assert.equal(f.writes.length,0);assert.equal(f.state.lead.initial_cnpj,'84429695000111');assert.deepEqual(f.events[1].args,{p_org:ORG,p_user:USER,p_candidate:CAND,p_action:'CONFIRM',p_reason:null,p_company:COMPANY,p_evidence:REGISTRY});assert.equal(f.events[1].name,'review_qsa_name_candidate');assert.match((await r.json()).note,/entre esta pessoa e a empresa selecionada/)});
test('Concurrent rejection or document review in the final RPC blocks confirmation without fallback writes',async()=>{for(const [code,status] of [['42501',403],['P0002',404],['22023',400],['P0001',409],['57014',500]]){const f=fixture(undefined,{rpcError:{code,message:'PRIVATE_RPC_ERROR'},rpcData:null}),r=await f.call();assert.equal(r.status,status);assert.equal(f.writes.length,0);assert.equal(f.events.filter(e=>e.kind==='rpc').length,1);assert.doesNotMatch(await r.text(),/PRIVATE_RPC_ERROR/)}});
test('Rejection commits before optional identity recalculation and never writes source/identity tables in the endpoint',async()=>{const f=fixture('review-identity-candidate'),r=await f.call();assert.equal(r.status,200);assert.deepEqual(f.events.map(e=>e.kind),['rpc','fetch']);assert.equal(f.writes.length,0);assert.deepEqual(f.events[0].args,{p_org:ORG,p_user:USER,p_candidate:CAND,p_action:'REJECT',p_reason:'Vínculo selecionado incorretamente',p_company:null,p_evidence:null});assert.equal((await r.json()).recompute_status,'COMPLETED')});
test('Failed rejection RPC never invokes identity recompute and reports preservation of the previous review',async()=>{const f=fixture('review-identity-candidate',{rpcError:{code:'P0001',message:'PRIVATE'},rpcData:null}),r=await f.call();assert.equal(r.status,409);assert.equal(f.events.length,1);assert.equal(f.events[0].kind,'rpc');assert.equal(f.writes.length,0)});
test('Committed rejection remains committed when the complementary identity recalculation fails',async()=>{for(const change of [{recomputeHttp:500},{fetchThrows:true},{recompute:{ok:false}}]){const f=fixture('review-identity-candidate',change),r=await f.call();assert.equal(r.status,200);const data=await r.json();assert.equal(data.rejected,true);assert.equal(data.recomputed,null);assert.equal(data.recompute_status,'PENDING_RETRY');assert.match(data.note,/pendente/);assert.equal(f.writes.length,0)}});
