import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {webcrypto} from 'node:crypto';
import {fetchQueridoDiarioJson,QUERIDO_DIARIO_API} from '../supabase/functions/_shared/querido-diario-fetch.ts';
import {selectTerritory,searchOutcome} from '../supabase/functions/_shared/source-operations.ts';
import {resolveCompanyCnpj} from '../supabase/functions/_shared/company-context.ts';
import {buildSourceRoutes,runIndependent} from '../supabase/functions/_shared/source-router.ts';
import {ensureCompanyResearchLink,persistCompanyIdentitySupport} from '../supabase/functions/_shared/company-research-link.ts';
const USER='11111111-1111-4111-8111-111111111111',ORG='22222222-2222-4222-8222-222222222222',LEAD='33333333-3333-4333-8333-333333333333',RUN='44444444-4444-4444-8444-444444444444',DOC='55555555-5555-4555-8555-555555555555',SOURCE='66666666-6666-4666-8666-666666666666',CITY='3505500';
const city={territory_id:CITY,territory_name:'Barretos',state_code:'SP'},gazette={territory_id:CITY,territory_name:'Barretos',state_code:'SP',date:'2025-01-01',url:'https://public.example.gov.br/edition.pdf',excerpts:['Trecho público de QA']};

test('transporte mantém duas tentativas/8s, classifica o HTTP real e nunca encaminha credenciais',async()=>{
 let calls=0;const response=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{fetcher:async(u,init)=>{assert.equal(u,QUERIDO_DIARIO_API+'/cities');assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,undefined);calls++;return new Response('PRIVATE_PROVIDER_BODY',{status:503})},wait:async()=>{}});assert.equal(calls,2);assert.equal(response.status,503);assert.equal(response.error,'HTTP_503');assert.equal(response.data,null);assert.equal(response.attempts.length,2);assert.doesNotMatch(JSON.stringify(response),/PRIVATE_PROVIDER_BODY/);
 await assert.rejects(fetchQueridoDiarioJson('https://arbitrary.invalid/cities',Array.isArray),/Unsupported/);
});
test('429 interrompe tentativas mesmo com espera curta; Retry-After numérico e data são preservados',async()=>{
 for(const retry of ['1','60',new Date(200000).toUTCString()]){let calls=0;const result=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{clock:()=>100000,deadline:300000,fetcher:async()=>{calls++;return new Response('',{status:429,headers:{'Retry-After':retry}})},wait:async()=>{}});assert.equal(calls,1);assert.equal(result.error,'HTTP_429');assert.equal(result.retry_after_seconds,retry==='1'?1:retry==='60'?60:100)}
 for(const status of [401,403,422]){let calls=0;const result=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{fetcher:async()=>{calls++;return new Response('',{status})},wait:async()=>{}});assert.equal(calls,1);assert.equal(result.error,'HTTP_'+status)}
});
test('resposta inválida/grande não recebe retry ou rótulo de zero; timeout/rede têm classificação segura',async()=>{
 for(const [body,error]of [['{','INVALID_RESPONSE'],['{}','INVALID_RESPONSE'],['x'.repeat(1024*1024+1),'RESPONSE_TOO_LARGE']]){let calls=0;const result=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{fetcher:async()=>{calls++;return new Response(body)},wait:async()=>{}});assert.equal(calls,1);assert.equal(result.error,error);assert.equal(result.status,200)}
 for(const e of [new DOMException('PRIVATE_DETAIL','TimeoutError'),new TypeError('PRIVATE_DETAIL')]){const result=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{fetcher:async()=>{throw e},wait:async()=>{}});assert.equal(result.attempts.length,2);assert.equal(result.status,null);assert.equal(result.error,e.name==='TimeoutError'?'TIMEOUT':'NETWORK_ERROR');assert.doesNotMatch(JSON.stringify(result),/PRIVATE_DETAIL/)}
});
test('deadline compartilhado impede uma nova tentativa sem tempo e permite recuperação transitória',async()=>{
 let now=1000,calls=0;const result=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{clock:()=>now,deadline:1600,fetcher:async()=>{calls++;now+=200;return new Response('',{status:503})},wait:async ms=>{now+=ms}});assert.equal(calls,1);assert.equal(result.error,'HTTP_503');assert.equal(now,1200);
 const recovered=await fetchQueridoDiarioJson(QUERIDO_DIARIO_API+'/cities',Array.isArray,{fetcher:async()=>{if(calls++===1)throw new DOMException('deadline','TimeoutError');return Response.json([])},wait:async()=>{}});assert.equal(recovered.ok,true);assert.deepEqual(recovered.data,[]);assert.equal(recovered.attempts.length,2);
});

function fixture(overrides={}){
 const state={user:{id:USER},role:'OWNER',activeOrg:ORG,leadFound:true,runFound:true,sourceStatus:'CONNECTED',cityBody:{cities:[city]},cityStatus:200,links:[],evidenceStatus:'PENDING',failTable:null,gazettes:()=>Response.json({total_gazettes:0,gazettes:[]}),...overrides};
 const reads=[],writes=[],calls=[],store=new Map();let handler,now=Date.parse('2026-10-05T12:00:00Z'),start=now;
 const clockDate=class extends Date{static now(){return now}};
 const db={auth:{getUser:async()=>({data:{user:state.user},error:null})},from(table){let mode='read',payload;const eq={},q={};for(const m of ['select','single','maybeSingle','neq'])q[m]=()=>q;q.eq=(k,v)=>{eq[k]=v;return q};q.insert=p=>{mode='insert';payload=p;return q};q.upsert=(p,o)=>{mode='upsert';payload=p;assert.equal(o.ignoreDuplicates,true);return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  (mode==='read'?reads:writes).push({table,mode,payload,eq});if(table==='evidence'&&mode==='upsert'&&!store.has(payload.dedupe_key))store.set(payload.dedupe_key,{id:DOC,...payload,verification_status:state.evidenceStatus});
  const data=table==='profiles'?{active_organization_id:state.activeOrg}:table==='organization_members'?{status:'ACTIVE',role:state.role}:table==='leads'?state.leadFound?{id:LEAD,name:'PRIVATE_NAME_MARKER',city:'Barretos',state:'SP'}:null:table==='research_runs'?state.runFound?{id:RUN}:null:table==='source_registry'?{id:SOURCE,connection_status:state.sourceStatus}:table==='lead_company_links'?state.links:table==='evidence'?store.get(eq.dedupe_key):table==='investigation_questions'?null:null;
  return {data,error:state.failTable===table&&(mode!=='read'||state.failReads)?{message:'PRIVATE_DATABASE_DETAIL'}:null};
 }).then(resolve,reject);return q}};
 const fetcher=async(input,init)=>{const u=new URL(input);assert.equal(u.origin,QUERIDO_DIARIO_API);assert.equal(init.headers.Authorization,undefined);calls.push({path:u.pathname,query:u.searchParams.get('querystring')});if(u.pathname==='/cities')return Response.json(state.cityBody,{status:state.cityStatus,headers:state.cityHeaders});return state.gazettes(u.searchParams.get('querystring'),calls.length,{advance:(ms)=>{now+=Math.min(ms,Math.max(0,start+45000-now))}})};
 const source=fs.readFileSync(new URL('../supabase/functions/querido-diario-search/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,selectTerritory,searchOutcome,API:QUERIDO_DIARIO_API,fetchQueridoDiarioJson:(u,v,o)=>fetchQueridoDiarioJson(u,v,{...o,fetcher,clock:()=>now,wait:async ms=>{now+=ms}}),Date:clockDate,Request,Response,AbortSignal,TextEncoder,crypto:webcrypto,URLSearchParams,console});
 return {state,reads,writes,calls,store,request:async(body={},auth=true)=>handler(new Request('https://qa.test',{method:'POST',headers:auth?{Authorization:'Bearer synthetic','Content-Type':'application/json'}:{'Content-Type':'application/json'},body:JSON.stringify({lead_id:LEAD,research_run_id:RUN,...body})}))};
}

test('handler exige sessão/org/operador e run escopado antes de consultar ou gravar',async()=>{
 for(const [opts,auth,status]of [[{},false,401],[{user:null},true,401],[{role:'VIEWER'},true,403],[{role:'UNKNOWN'},true,403],[{activeOrg:null},true,409],[{leadFound:false},true,404],[{runFound:false},true,404]]){const f=fixture(opts);assert.equal((await f.request({},auth)).status,status);assert.equal(f.calls.length,0);assert.equal(f.writes.length,0)}
 for(const body of [{lead_id:'invalid'},{research_run_id:'invalid'},{max_results:'NaN'}]){const f=fixture();assert.equal((await f.request(body)).status,400);assert.equal(f.calls.length,0)}
 const disabled=fixture({sourceStatus:'DISABLED'});assert.equal((await (await disabled.request()).json()).status,'BLOCKED');assert.equal(disabled.calls.length,0);assert.equal(disabled.writes.length,0);
});
test('upstream503 e contrato inválido de cidades ficam distintos do wrapper502 e ausência de cobertura',async()=>{
 for(const [opts,error,upstream]of [[{cityStatus:503},'HTTP_503',503],[{cityBody:{cities:[{}]}},'INVALID_RESPONSE',200]]){const f=fixture(opts),r=await f.request();assert.equal(r.status,502);const result=await r.json();assert.equal(result.status,'CITY_LOOKUP_FAILED');assert.equal(result.source_error,error);assert.equal(result.upstream_http_status,upstream);assert.equal(result.complete,false);assert.ok(f.calls.every(c=>c.path==='/cities'));const log=f.writes.find(w=>w.table==='source_fetch_logs').payload;assert.equal(log.research_run_id,RUN);assert.equal(log.organization_id,ORG);assert.equal(log.http_status,upstream);assert.doesNotMatch(JSON.stringify(log),/PRIVATE_NAME_MARKER|PRIVATE_DATABASE_DETAIL/)}
});
test('documentos PENDING são preservados quando outro termo esgota prazo; não cria fato/identidade',async()=>{
 const f=fixture({gazettes:(term,_n,time)=>{if(term==='PRIVATE_NAME_MARKER')return Response.json({total_gazettes:1,gazettes:[gazette]});time.advance(8000);throw new DOMException('PRIVATE_FAILURE','TimeoutError')}}),r=await f.request({terms:['Segundo termo']});assert.equal(r.status,200);const result=await r.json();assert.equal(result.status,'PARTIAL');assert.equal(result.complete,false);assert.equal(result.mentions_found,1);assert.equal(result.evidence[0].verification_status,'PENDING');assert.equal(result.source_error,'TIMEOUT');assert.equal(result.upstream_http_status,null);assert.equal(result.queries_completed,1);assert.equal(result.queries_failed,1);assert.equal(result.source_attempts.filter(a=>a.endpoint==='/gazettes').length,3);assert.ok(f.writes.every(w=>['evidence','investigation_questions','source_fetch_logs'].includes(w.table)));const log=f.writes.find(w=>w.table==='source_fetch_logs').payload;assert.doesNotMatch(JSON.stringify(log),/PRIVATE_NAME_MARKER|Segundo termo|PRIVATE_FAILURE|edition\.pdf/);
});
test('429/403 interrompem outros termos; Retry-After retorna sem reconsulta automática da fonte',async()=>{
 for(const status of [429,403]){const f=fixture({gazettes:()=>new Response('',{status,headers:{'Retry-After':'60'}})}),r=await f.request({terms:['Segundo termo','Terceiro termo']});assert.equal(r.status,502);const result=await r.json();assert.equal(result.status,'QUERY_FAILED');assert.equal(result.upstream_http_status,status);assert.equal(result.queries_skipped,2);assert.equal(result.queries_failed,1);assert.equal(result.source_error,'HTTP_'+status);assert.equal(f.calls.length,2);if(status===429){assert.equal(result.retry_after_seconds,60);assert.equal(r.headers.get('Retry-After'),'60');assert.ok(Date.parse(result.retry_not_before)>Date.parse('2026-10-05T12:00:00Z'))}}
});
test('falha total conserva diagnósticos de timeout e é QUERY_FAILED, jamais ausência de menções',async()=>{
 const f=fixture({gazettes:(_term,_n,time)=>{time.advance(8000);throw new DOMException('deadline','TimeoutError')}}),r=await f.request({terms:['Segundo termo']});assert.equal(r.status,502);const result=await r.json();assert.equal(result.status,'QUERY_FAILED');assert.equal(result.queries_failed,2);assert.equal(result.source_error,'TIMEOUT');assert.equal(result.upstream_http_status,null);assert.equal(result.mentions_found,0);assert.match(result.note,/não concluída/);assert.equal(f.calls.length,5);
});
test('total maior que página, total desconhecido, documento inválido e revisão REJECTED permanecem parciais',async()=>{
 for(const options of [{gazettes:()=>Response.json({total_gazettes:2,gazettes:[gazette]})},{gazettes:()=>Response.json({gazettes:[gazette]})},{gazettes:()=>Response.json({total_gazettes:1,gazettes:[{...gazette,territory_id:'OTHER'}]})},{gazettes:()=>Response.json({total_gazettes:1,gazettes:[gazette]}),evidenceStatus:'REJECTED'}]){const f=fixture(options),r=await f.request(),result=await r.json();assert.equal(r.status,200);assert.equal(result.status,'PARTIAL');assert.equal(result.complete,false);assert.ok(!f.writes.some(w=>w.table==='claims'));if(options.evidenceStatus){assert.equal(result.mentions_found,0);assert.equal([...f.store.values()][0].verification_status,'REJECTED')}}
});
test('reconsulta preserva FAILED/STALE existentes e os exclui das menções utilizáveis com cobertura parcial',async()=>{
 for(const status of ['FAILED','STALE']){
  const f=fixture({gazettes:()=>Response.json({total_gazettes:1,gazettes:[gazette]})});
  const initial=await(await f.request()).json();assert.equal(initial.mentions_found,1);assert.equal(initial.complete,true);
  const stored=[...f.store.values()][0];stored.verification_status=status;
  const questionsBefore=f.writes.filter(w=>w.table==='investigation_questions').length;
  const response=await f.request(),result=await response.json();
  assert.equal(response.status,200);assert.equal(result.status,'PARTIAL');assert.equal(result.complete,false);assert.equal(result.review_excluded,true);assert.equal(result.mentions_found,0);assert.deepEqual(result.evidence,[]);
  assert.equal(stored.verification_status,status);assert.equal(f.store.size,1);assert.equal(f.writes.filter(w=>w.table==='investigation_questions').length,questionsBefore);assert.ok(!f.writes.some(w=>['claims','leads','candidate_entities'].includes(w.table)));
 }
 const verified=fixture({gazettes:()=>Response.json({total_gazettes:1,gazettes:[gazette]}),evidenceStatus:'VERIFIED'}),result=await(await verified.request()).json();assert.equal(result.mentions_found,1);assert.equal(result.evidence[0].verification_status,'VERIFIED');assert.equal(result.review_excluded,false);assert.equal(result.complete,true);
});
test('falhas de gravação não recebem sucesso e conclusão conserva pesquisa/run escopados',async()=>{
 for(const failTable of ['evidence','investigation_questions','source_fetch_logs']){const f=fixture({failTable,gazettes:()=>Response.json({total_gazettes:1,gazettes:[gazette]})}),r=await f.request();assert.equal(r.status,500);assert.equal((await r.json()).complete,false)}
 const f=fixture(),r=await f.request(),result=await r.json();assert.equal(result.status,'NO_MENTIONS');assert.equal(result.complete,true);assert.equal(f.writes.find(w=>w.table==='source_fetch_logs').payload.research_run_id,RUN);const run=f.reads.find(r=>r.table==='research_runs');assert.deepEqual(run.eq,{id:RUN,lead_id:LEAD,organization_id:ORG});
});

async function orchestration(sourceResult,http=200){
 let handler;const steps=[];const lead={id:LEAD,kind:'COMPANY',name:'Marca QA',city:'Barretos',state:'SP',initial_cnpj:null},sources=[{key:'base_empresarial_rfb',connection_status:'CONNECTED'},{key:'querido_diario',connection_status:'CONNECTED'}];
 const db={auth:{getUser:async()=>({data:{user:{id:USER}}})},from(table){let mode='read',payload;const eq={},q={};for(const m of ['select','single','maybeSingle','neq'])q[m]=()=>q;q.eq=(k,v)=>{eq[k]=v;return q};for(const m of ['insert','update'])q[m]=p=>{mode=m;payload=p;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{if(table==='research_steps'&&mode==='insert')steps.push(...payload);if(table==='research_steps'&&mode==='update')Object.assign(steps.find(s=>s.step_key===eq.step_key)||{},payload);const data=table==='profiles'?{active_organization_id:ORG}:table==='organization_members'?{role:'OWNER',status:'ACTIVE'}:table==='leads'?lead:table==='lead_company_links'?[]:table==='source_registry'?sources:table==='research_runs'?{id:RUN}:table==='research_steps'?steps:[];return {data,error:null,count:0}}).then(resolve,reject);return q}};
 const source=fs.readFileSync(new URL('../supabase/functions/start-research/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:k=>k==='BRAVE_SEARCH_API_KEY'||k==='PORTAL_TRANSPARENCIA_API_TOKEN'?undefined:'https://qa.supabase.co'},serve:fn=>{handler=fn}},createClient:()=>db,resolveCompanyCnpj,buildSourceRoutes,runIndependent,ensureCompanyResearchLink,persistCompanyIdentitySupport,fetch:async(url)=>Response.json(url.endsWith('querido-diario-search')?sourceResult:{ok:true,candidates:[],signals:[],complete:true},{status:url.endsWith('querido-diario-search')?http:200}),Request,Response,AbortSignal,console});
 assert.equal((await handler(new Request('https://qa.test',{method:'POST',headers:{Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({lead_id:LEAD,strategy:'AGRO'})}))).status,200);return steps.find(s=>s.step_key==='municipal_gazettes');
}
test('plano mantém erro upstream/retry e resultados parciais sem colapsar tudo em HTTP502',async()=>{
 const diagnostic={status:'QUERY_FAILED',complete:false,source_error:'TIMEOUT',upstream_http_status:null,note:'Consulta à fonte não concluída: TIMEOUT.',retry_after_seconds:60,retry_not_before:'2026-10-05T12:01:00Z',source_attempts:[{endpoint:'/gazettes',status:null,error:'TIMEOUT'}]};const failed=await orchestration(diagnostic,502);assert.equal(failed.status,'FAILED');assert.match(failed.error_summary,/TIMEOUT/);assert.equal(failed.metadata.wrapper_http_status,502);assert.equal(failed.metadata.upstream_http_status,null);assert.equal(failed.metadata.retry_after_seconds,60);assert.equal(failed.metadata.source_attempts[0].error,'TIMEOUT');
 const partial=await orchestration({...diagnostic,status:'PARTIAL',mentions_found:1},200);assert.equal(partial.status,'PARTIAL');assert.equal(partial.metadata.mentions_found,1);assert.equal(partial.metadata.complete,false);const blocked=await orchestration({status:'BLOCKED',complete:false,note:'Fonte desativada'},200);assert.equal(blocked.status,'BLOCKED');
});
