import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {sourceBatches} from '../supabase/functions/_shared/source-batches.ts';
import {normalizeBaseCompany,validateQsaMapping,canonicalRegistryText} from '../supabase/functions/_shared/cnpj-fallback.ts';import {fetchSourceJson} from '../supabase/functions/_shared/source-operations.ts';import {persistSourceEvidence} from '../supabase/functions/_shared/source-evidence.ts';
function setup(name,{role='OWNER',fetcher=async()=>new Response('',{status:503})}={}){let handler,writes=0;const id='11111111-1111-4111-8111-111111111111';const db={auth:{getUser:async()=>({data:{user:{id}}})},rpc:async()=>{writes++;return {data:{},error:null}},from(table){let write=false;const q={};for(const fn of ['select','eq','maybeSingle','single','order','limit','in','not','contains'])q[fn]=()=>q;for(const fn of ['insert','upsert','update'])q[fn]=()=>{write=true;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{if(write&&table!=='source_fetch_logs')writes++;return {data:table==='profiles'?{active_organization_id:id}:table==='organization_members'?{role,status:'ACTIVE'}:table==='leads'?{id}:table==='companies'?{id,cnpj:'32901144000105',legal_name:'QA Hospital'}:table==='lead_company_links'?{status:'SUPPORTED'}:table==='source_registry'?{id}:null,error:null}}).then(resolve,reject);return q}};const source=fs.readFileSync(new URL('../supabase/functions/'+name+'/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');const failFetch=fetcher;vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=> 'https://qa.supabase.co'},serve:f=>{handler=f}},createClient:()=>db,fetch:failFetch,fetchSourceJson:(url,valid,options)=>fetchSourceJson(url,valid,{...options,fetcher:failFetch,wait:async()=>{}}),persistSourceEvidence,normalizeBaseCompany,sourceBatches,unzipSync:()=>({}),Response,Request,AbortSignal,crypto,TextEncoder,TextDecoder,Uint8Array,console:{error(){}}});return {call:(auth=true)=>handler(new Request('https://qa.supabase.co',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer qa'}:{})},body:JSON.stringify({lead_id:id,company_id:id,relationship_id:id,action:'REJECT',reason:'QA only reason'})})),writes:()=>writes}}
test('conectores e novas revisões negam escrita a VIEWER antes de consultar ou persistir',async()=>{for(const name of ['pncp-company-contracts','bndes-company-financing','cvm-company-check','cvm-ipe-search','central-balancos-search','capture-intelligence','review-relationship','review-graph-candidate']){const s=setup(name,{role:'VIEWER'});assert.equal((await s.call()).status,403,name);assert.equal(s.writes(),0,name);assert.equal((await s.call(false)).status,401,name)}});
test('BNDES e CVM não transformam falha de fonte em ausência de registros',async()=>{for(const name of ['bndes-company-financing','cvm-company-check','cvm-ipe-search']){const s=setup(name);const r=await s.call();assert.equal(r.status,502,name);assert.equal(s.writes(),0,name)}});
test('captura histórica não grava desaparecimento quando leitura do dossiê falha',async()=>{const s=setup('capture-intelligence');assert.equal((await s.call()).status,502);assert.equal(s.writes(),0)});
test('fallback cadastral exige raiz e estabelecimento exato e elimina documentos pessoais',()=>{const cnpj='32901144000105',value={data:{basic_cnpj:'32901144',corporate_name:'QA Company',establishments:[{full_cnpj:cnpj,address:{city:{name:'Barretos'},state:{abbreviation:'SP'}}}],partners:[{partner_name:'Pessoa',partner_identifier:{code:'2'},cnpj_cpf_partner:'personal-private',legal_representative:'private'}]}};const out=normalizeBaseCompany(value,cnpj);assert.equal(out.qsa[0].cnpj_cpf_do_socio,null);assert.ok(!JSON.stringify(out).includes('private'));assert.equal(normalizeBaseCompany(value,'32901144000296'),null);value.data.basic_cnpj='00000000';assert.equal(normalizeBaseCompany(value,cnpj),null)});
test('documento legado rejeitado permanece bloqueado e não é substituído por nova revisão',async()=>{let writes=0;const db={from(){const q={select(){return q},eq(){return q},maybeSingle(){return Promise.resolve({data:{id:'legacy',verification_status:'FAILED'},error:null})},upsert(){writes++;return q}};return q}};const r=await persistSourceEvidence(db,{organization_id:'o',lead_id:'l',dedupe_key:'k'});assert.equal(r.data.verification_status,'FAILED');assert.equal(writes,0)});
test('resolver empresa sócia exige QSA atual, tipo jurídico, nome e raiz corroborados',()=>{const candidate={label:'Sócia Teste LTDA',metadata:{basic_cnpj:'35255963',parent_company_cnpj:'32901144000105'}},parent={data:{basic_cnpj:'32901144',establishments:[{full_cnpj:'32901144000105'}],partners:[{partner_name:'Soc ia errada',partner_identifier:{code:'1'}}]}},cnpj='35255963000100',target={data:{basic_cnpj:'35255963',corporate_name:'Sócia Teste LTDA',establishments:[{full_cnpj:cnpj}],partners:[]}};assert.equal(validateQsaMapping(parent,target,cnpj,candidate),false);parent.data.partners[0].partner_name='SÓCIA TESTE LTDA';assert.equal(validateQsaMapping(parent,target,cnpj,candidate),true);parent.data.partners[0].partner_identifier.code='2';assert.equal(validateQsaMapping(parent,target,cnpj,candidate),false);parent.data.partners=[];assert.equal(validateQsaMapping(parent,target,cnpj,candidate),false)});

test('normalização cadastral iguala apresentação sem ocultar mudança real',()=>{assert.equal(canonicalRegistryText('  Ativa '),canonicalRegistryText('ATIVA'));assert.equal(canonicalRegistryText('Barretos'),canonicalRegistryText('BARRETOS'));assert.notEqual(canonicalRegistryText('ATIVA'),canonicalRegistryText('BAIXADA'))});
test('BNDES aceita consulta vazia somente quando os recursos e formatos responderam validamente',async()=>{const s=setup('bndes-company-financing',{fetcher:async()=>Response.json({success:true,result:{records:[],total:0}})});const r=await s.call();assert.equal(r.status,200);const d=await r.json();assert.equal(d.complete,true);assert.equal(d.operations_found,0)});
