import test from 'node:test';import assert from 'node:assert/strict';
import {buildSourceRoutes,runIndependent,normalizeResearchStep} from '../supabase/functions/_shared/source-router.ts';
import {resolveCompanyCnpj} from '../supabase/functions/_shared/company-context.ts';
import {ensureCompanyResearchLink,persistCompanyIdentitySupport} from '../supabase/functions/_shared/company-research-link.ts';
import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {buildCompanyPassport} from '../lib/company-passport.ts';
const readinessSource=fs.readFileSync(new URL('../lib/investigation-readiness.ts',import.meta.url),'utf8').replace(/^import .*\r?\n/gm,'');const readinessContext={exports:{},buildCompanyPassport};vm.runInNewContext(ts.transpileModule(readinessSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,readinessContext);const buildInvestigationReadiness=readinessContext.exports.buildInvestigationReadiness;
const sources=['brasilapi_cnpj','base_empresarial_rfb','central_balancos_sped','bndes_financing','querido_diario','pncp','cvm','cvm_ipe','cvm_dfp','web_search','portal_transparencia','jucesp','cade'].map(key=>({key,name:key,connection_status:'CONNECTED'}));
test('histórico municipal legado permanece inconclusivo em todas as apresentações sem alterar registro original',()=>{const step={source_key:'querido_diario',status:'PARTIAL',result_summary:'Município não está coberto/localizado no Querido Diário.',action_url:'https://api.queridodiario.ok.org.br/docs'};const normalized=normalizeResearchStep(step);assert.match(normalized.result_summary,/legado inconclusivo/);assert.equal(normalized.action_url,'https://api.queridodiario.org.br/docs');assert.equal(step.result_summary,'Município não está coberto/localizado no Querido Diário.');assert.equal(normalizeResearchStep({...step,result_summary:'HTTP 503'}).result_summary,'HTTP 503')});
test('rotas nunca liberam Brave ou Portal sem credencial, mesmo com catálogo CONNECTED',()=>{const routes=buildSourceRoutes(sources,{companyResolved:true,kind:'COMPANY'});for(const key of ['web_context','federal_records']){const r=routes.find(r=>r.key===key);assert.equal(r.state,'CONFIG_REQUIRED');assert.equal(r.selected,null)}assert.ok(!routes.some(r=>r.key==='company_discovery'));assert.equal(routes.find(r=>r.key==='corporate_history').state,'MANUAL');assert.equal(routes.find(r=>r.key==='mna').selected,null)});
test('fonte alternativa cadastral permanece elegível sem confundir provedores com funções',()=>{const routes=buildSourceRoutes(sources.filter(s=>s.key!=='brasilapi_cnpj'),{companyResolved:true});const r=routes.find(r=>r.key==='company_registry');assert.equal(r.providers[0].enabled,false);assert.equal(r.providers[1].enabled,true);assert.equal(r.selected,'cnpj-enrich');assert.equal(r.state,'READY')});
test('prerequisito de empresa bloqueia rotas sem eleger empresa de pessoa arbitrariamente',()=>{const routes=buildSourceRoutes(sources,{companyResolved:false,kind:'PERSON',portalConfigured:true});assert.equal(routes.find(r=>r.key==='company_registry').selected,null);assert.equal(routes.find(r=>r.key==='company_registry').state,'NEEDS_COMPANY');assert.equal(routes.find(r=>r.key==='company_discovery').selected,'name-company-discovery')});
test('pivô permite alternativa Minha Receita cadastrada sem liberar fontes sem credenciais nem duplicar investigação',()=>{
 const registry=sources.filter(s=>s.key!=='base_empresarial_rfb').concat({key:'minha_receita_rfb',connection_status:'CONNECTED_LIMITED'});const routes=buildSourceRoutes(registry,{companyResolved:false,kind:'PERSON'});const pivot=routes.find(r=>r.key==='family_context');assert.equal(pivot.selected,'family-cluster-discovery');assert.equal(pivot.providers.filter(p=>p.enabled).length,1);assert.equal(pivot.providers[1].key,'minha_receita_rfb');assert.equal(routes.find(r=>r.key==='web_context').selected,null);assert.equal(routes.find(r=>r.key==='federal_records').selected,null);assert.equal(buildSourceRoutes(registry.map(s=>({...s,connection_status:'DISABLED'})),{companyResolved:false,kind:'PERSON'}).find(r=>r.key==='family_context').selected,null);
});
test('consultas independentes usam no máximo duas concorrentes e aguardam todo o lote',async()=>{let running=0,max=0;const finished=[];await runIndependent([1,2,3,4,5],async x=>{running++;max=Math.max(max,running);await new Promise(resolve=>setTimeout(resolve,3));finished.push(x);running--});assert.equal(max,2);assert.equal(running,0);assert.equal(finished.length,5)});
test('falha de lote não deixa consulta ativa nem inicia lote seguinte',async()=>{let finished=false,third=false;await assert.rejects(runIndependent([1,2,3],async x=>{if(x===1)throw new Error('write failed');if(x===2){await new Promise(resolve=>setTimeout(resolve,3));finished=true}else third=true}));assert.equal(finished,true);assert.equal(third,false)});
const dossier=()=>({lead:{kind:'COMPANY'},companies:[{id:'a',legal_name:'Empresa A',link_status:'SUPPORTED'}],evidence:[{id:'e',verification_status:'VERIFIED'}],claims:['legal_name','registration_status','location','cnae'].map((predicate,i)=>({id:'c'+i,company_id:'a',predicate,value_text:predicate,status:'VERIFIED',classification:'FACT',claim_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]})),relationships:[],events:[],research_runs:[{status:'COMPLETED',research_steps:[{status:'COMPLETED',source_key:'pncp'}]}]});
test('pesquisa concluída não converte ausência de finanças e eventos em respostas documentadas',()=>{const r=buildInvestigationReadiness(dossier());assert.equal(r.dimensions.find(x=>x.key==='identity').state,'DOCUMENTED');assert.equal(r.dimensions.find(x=>x.key==='operation').state,'PARTIAL');assert.equal(r.dimensions.find(x=>x.key==='financial').state,'UNKNOWN');assert.equal(r.dimensions.find(x=>x.key==='events').state,'UNKNOWN');assert.equal(r.state,'NEEDS_MORE_EVIDENCE')});
test('dados de outra empresa, vínculo rejeitado e suporte contraditório não completam perguntas',()=>{for(const mode of ['company','rejected','contradicts']){const d=dossier();if(mode==='company')d.claims.forEach(c=>c.company_id='other');if(mode==='rejected')d.companies[0].link_status='REJECTED';if(mode==='contradicts')d.claims.forEach(c=>c.claim_evidence.push({evidence_id:'e',support_type:'CONTRADICTS'}));assert.equal(buildInvestigationReadiness(d).dimensions[0].state,'UNKNOWN',mode)}});
test('QSA e publicação financeira não comprovam poderes nem posição financeira atual',()=>{const d=dossier();d.relationships=[{id:'r',from_entity_type:'COMPANY',from_entity_id:'a',to_label:'Pessoa',relationship_type:'ADMINISTRADOR',status:'VERIFIED',relationship_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]}];d.events=[{id:'event',company_id:'a',status:'VERIFIED',event_type:'FINANCIAL_REPORT',title:'Demonstração',event_evidence:[{evidence_id:'e',support_type:'SUPPORTS'}]}];const r=buildInvestigationReadiness(d);assert.equal(r.dimensions.find(x=>x.key==='decision').state,'PARTIAL');assert.equal(r.dimensions.find(x=>x.key==='financial').state,'PARTIAL');d.claims[0].status='CONTRADICTED';assert.equal(buildInvestigationReadiness(d).dimensions[0].state,'CONFLICTING')});

async function runOrchestratorFixture(kind='COMPANY',strategy='EMPRESARIO',familyStatus='PARTIAL',familyProvider='base_empresarial_rfb',networkFailure=false){
 let handler,role='OWNER',active=0,maxActive=0,writes=0;const calls=[],steps=[];
 const id='11111111-1111-4111-8111-111111111111';
 const lead={id,kind,name:'Pessoa Magurno',city:'João Ramalho',state:'SP',segment:'Agro',initial_cnpj:kind==='COMPANY'?'32901144000105':null,identity_status:kind==='COMPANY'?'SUPPORTED':'CAUTION',identity_confirmed_by_user:false};const leadWrites=[];
 const db={auth:{getUser:async()=>({data:{user:{id}}})},from(table){let mode='read',payload,eqs={};const q={};for(const m of ['select','single','maybeSingle','order','limit','neq'])q[m]=()=>q;q.eq=(k,v)=>{eqs[k]=v;return q};for(const m of ['insert','update'])q[m]=p=>{mode=m;payload=p;return q};q.then=(resolve,reject)=>Promise.resolve().then(()=>{
  if(mode!=='read'){writes++;if(table==='research_steps'){if(mode==='insert')steps.push(...payload);else Object.assign(steps.find(s=>s.step_key===eqs.step_key)||{},payload)}}
  if(table==='leads'&&mode!=='read')leadWrites.push(payload);
  const data=table==='profiles'?{active_organization_id:id}:table==='organization_members'?{status:'ACTIVE',role}:table==='leads'?lead:table==='lead_company_links'?(steps.length?{id,status:'SUPPORTED'}:[{status:'SUPPORTED',companies:{cnpj:'32901144000105'}}]):table==='source_registry'?sources:table==='research_runs'?{id}:table==='research_steps'?steps:[];
  return {data,error:null,count:0};
 }).then(resolve,reject);return q}};
 const fetcher=async url=>{const name=url.split('/').at(-1);calls.push(name);active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,3));active--;if(name==='family-network-discovery')return Response.json(networkFailure?{error:'temporary source failure'}:{ok:true,pivot:{id},continuation:true,network:{counts:{companies:3,people:4},continuation:true,status:'PARTIAL'}},{status:networkFailure?502:200});return Response.json(name==='family-cluster-discovery'?{ok:true,provider:familyProvider,status:familyStatus,complete:familyStatus==='COMPLETED',candidates_found:2,search_lineage:{business_provider:familyProvider==='minha_receita_rfb'?'MINHA_RECEITA':'BASE_EMPRESARIAL'},pivot:{id}}:name==='identity-resolution'?{lead_status:'CAUTION'}:name==='name-company-discovery'?{candidates:[],complete:true}:name==='cnpj-enrich'?{company_id:id,provider:'base_empresarial_rfb',relationship_ids:[]}:name==='cvm-company-check'?{found:false}:name==='central-balancos-search'?{documents_found:1,truncated:true}:name==='derive-signals'?{signals:[]}:name==='capture-intelligence'?{ok:true}:{complete:true,contracts_found:1,operations_found:1,mentions_found:1})};
 const source=fs.readFileSync(new URL('../supabase/functions/start-research/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:k=>k==='BRAVE_SEARCH_API_KEY'||k==='PORTAL_TRANSPARENCIA_API_TOKEN'?undefined:'https://qa.supabase.co'},serve:f=>{handler=f}},createClient:()=>db,resolveCompanyCnpj,ensureCompanyResearchLink,persistCompanyIdentitySupport,buildSourceRoutes,runIndependent,fetch:fetcher,Response,Request,AbortSignal,console});
 const request=()=>new Request('https://qa.supabase.co',{method:'POST',headers:{Authorization:'Bearer qa','Content-Type':'application/json'},body:JSON.stringify({lead_id:id,strategy})});
 role='VIEWER';assert.equal((await handler(request())).status,403);assert.equal(writes,0);role='OWNER';
 const result=await handler(request());assert.equal(result.status,200);assert.equal((await result.json()).status,'PARTIAL');assert.equal(active,0);
 return {steps,calls,maxActive,lead,leadWrites};
}
test('orquestrador real persiste rotas, limita concorrência, bloqueia fontes sem chave e aguarda elegibilidade CVM',async()=>{
 const {steps,calls,maxActive}=await runOrchestratorFixture();assert.equal(maxActive,2);
 assert.ok(!calls.includes('web-context-search'));assert.ok(!calls.includes('portal-transparencia-company'));assert.ok(!calls.includes('cvm-ipe-search'));assert.ok(!calls.includes('cvm-financial-statements'));assert.equal(steps.find(s=>s.step_key==='cvm_ipe').status,'SKIPPED');assert.equal(steps.find(s=>s.step_key==='financial_statements').status,'SKIPPED');assert.equal(steps.find(s=>s.step_key==='financial_filings').status,'PARTIAL');assert.equal(steps.find(s=>s.step_key==='public_contracts').metadata.source_route.key,'public_contracts');assert.ok(steps.every(s=>!['PENDING','RUNNING'].includes(s.status)));
 assert.ok(!calls.includes('family-cluster-discovery'));assert.ok(!calls.includes('family-network-discovery'));assert.equal(steps.find(s=>s.step_key==='surname_candidates').status,'SKIPPED');assert.equal(steps.find(s=>s.step_key==='family_validation').status,'SKIPPED');
});
test('pivô real roda nas quatro estratégias para pessoa sem identidade resolvida ou busca web, antes da consulta municipal',async()=>{
 for(const strategy of ['EMPRESARIO','AGRO','MEDICO','GENERICO']){
  const {steps,calls,lead,leadWrites}=await runOrchestratorFixture('PERSON',strategy);const pivot=steps.find(s=>s.step_key==='surname_candidates');
  assert.equal(pivot.status,'PARTIAL');assert.equal(pivot.metadata.candidates_found,2);assert.equal(pivot.metadata.complete,false);assert.equal(pivot.metadata.source_route.key,'family_context');
  assert.ok(calls.indexOf('family-cluster-discovery')<calls.indexOf('querido-diario-search'));assert.ok(!calls.includes('web-context-search'));assert.ok(!calls.includes('cnpj-enrich'));assert.ok(!calls.includes('enrich-supported-identity-cluster'));
  assert.equal(steps.find(s=>s.step_key==='family_validation').status,'BLOCKED');assert.equal(lead.identity_status,'CAUTION');assert.equal(lead.initial_cnpj,null);assert.deepEqual(leadWrites,[]);assert.ok(steps.every(s=>!['PENDING','RUNNING'].includes(s.status)));
 }
});
test('bloqueio e falha retornados pelo pivô permanecem inconclusivos no plano',async()=>{
 for(const status of ['BLOCKED','FAILED']){const {steps,calls}=await runOrchestratorFixture('PERSON','AGRO',status);assert.equal(steps.find(s=>s.step_key==='surname_candidates').status,status);assert.equal(steps.find(s=>s.step_key==='family_validation').status,'BLOCKED');assert.ok(!calls.includes('family-network-discovery'))}
});
test('orquestrador registra o fornecedor real da descoberta alternativa sem investigar duas vezes',async()=>{
 const {steps,calls,leadWrites}=await runOrchestratorFixture('PERSON','AGRO','COMPLETED','minha_receita_rfb');const step=steps.find(s=>s.step_key==='surname_candidates');assert.equal(step.status,'PARTIAL');assert.equal(step.source_key,'minha_receita_rfb');assert.equal(step.metadata.provider,'minha_receita_rfb');assert.equal(step.metadata.search_lineage.business_provider,'MINHA_RECEITA');assert.equal(step.metadata.complete,false);assert.equal(step.metadata.network_counts.companies,3);assert.equal(step.metadata.network_counts.people,4);assert.equal(step.metadata.network_continuation,true);assert.equal(calls.filter(c=>c==='family-cluster-discovery').length,1);assert.equal(calls.filter(c=>c==='family-network-discovery').length,1);assert.deepEqual(leadWrites,[]);
});
test('falha na expansão preserva pistas e identidade do lead sem registrar conclusão falsa',async()=>{const {steps,calls,leadWrites}=await runOrchestratorFixture('PERSON','AGRO','COMPLETED','minha_receita_rfb',true);const step=steps.find(s=>s.step_key==='surname_candidates');assert.equal(step.status,'PARTIAL');assert.equal(step.metadata.candidates_found,2);assert.equal(step.metadata.complete,false);assert.equal(calls.filter(c=>c==='family-network-discovery').length,1);assert.deepEqual(leadWrites,[])});
