'use client'
import { buildCommercialBrief } from '@/lib/commercial-brief'
import { CompanyPassport } from '@/components/CompanyPassport'
import { StatusBadge } from '@/components/StatusBadge'
import {buildCommercialOpportunities} from '@/lib/commercial-opportunities'
export function CommercialBrief({dossier,mode="commercial"}:{dossier:Record<string,any>;mode?:"commercial"|"profile"}){
 const brief=buildCommercialBrief(dossier)
 const opportunities=buildCommercialOpportunities(dossier)
 const additionalTopics=brief.topics.filter(t=>!t.title.startsWith('Operação ·')&&!t.title.startsWith('Governança ·'))
 function sources(ids:string[]){return <details><summary className="source-link">Consultar evidências ({ids.length})</summary>{brief.evidence.filter(e=>ids.includes(e.id)).map(e=><div className="banner" key={e.id}><strong>{e.title}</strong><div className="micro">{e.source_label} · consultado em {e.retrieved_at?new Date(e.retrieved_at).toLocaleDateString('pt-BR'):'data não informada'}</div><p>{e.excerpt}</p>{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Abrir documento ↗</a>}</div>)}</details>}
 return <section className="stack" style={{marginBottom:20}} aria-label="Inteligência comercial">
  {mode==='commercial'&&<div className="card"><h2>Preparação para a conversa comercial</h2><p className="muted">{brief.facts.length} fatos com evidência verificada · {brief.events.length} eventos documentados · {opportunities.length} hipóteses para validar</p><div className="caution">{brief.financialWarning}</div></div>}
  {mode==='profile'&&(brief.companies.length?brief.companies.map(company=><CompanyPassport key={company.id} dossier={dossier} company={company}/>):<div className="empty">Nenhuma empresa atribuída a este núcleo. Confirme os candidatos em Validação.</div>)}
  {mode==='commercial'&&<div className="card"><h3>Oportunidades para validar</h3><p className="muted">Perguntas específicas sustentadas por fatos. A hipótese só avança com validação da empresa.</p>{opportunities.length?<div className="split">{opportunities.map(o=><article className="banner" key={o.id}><div className="micro">{o.company} · {o.stage}</div><h4>{o.theme}</h4><p><b>Base documentada:</b> {o.basis}</p><div className="question">{o.question}</div><p><b>Próxima validação:</b> {o.validation}</p><p className="micro">{o.limit}</p>{sources(o.evidenceIds)}</article>)}</div>:<div className="empty">Sem fatos suficientes para uma hipótese específica. Consulte o Perfil documentado e as pendências de Validação.</div>}</div>}
  {mode==='commercial'&&additionalTopics.length>0&&<div className="card"><h3>Outros temas documentados</h3><p className="muted">Interpretações e perguntas de descoberta. Cada tema indica o fato que o sustenta e o que ainda precisa ser validado.</p>{additionalTopics.length?<div className="split">{additionalTopics.map((t,i)=><article className="banner" key={`${t.title}-${i}`}><h4>{t.title}</h4><p><strong>Base documentada:</strong> {t.basis}</p><p><strong>Relevância comercial:</strong> {t.relevance}</p><div className="question">{t.question}</div><p className="micro">{t.caution}</p>{sources(t.evidenceIds)}</article>)}</div>:<div className="empty">Ainda não há base documental suficiente para preparar uma abordagem específica. Inicie a investigação e valide os vínculos.</div>}</div>}
  {mode==='commercial'&&<div className="card"><h3>O que falta para aprofundar</h3>{!brief.hasResearch&&<p>A investigação deste núcleo ainda não foi executada.</p>}{brief.gaps.map((g,i)=><div className="research-step" key={i}><div className="step-num">!</div><div><strong>{g.title}</strong><p>{g.reason}</p>{g.url&&<a className="source-link" href={g.url} target="_blank" rel="noreferrer">Consultar fonte ↗</a>}</div><StatusBadge value={g.status}/></div>)}<p className="muted">Valide com a empresa os documentos financeiros atuais, a estrutura de decisão e os próximos investimentos antes de formular uma proposta.</p></div>}
  {mode==='profile'&&<div className="card"><h3>Pistas para aprofundar</h3><p className="muted">Resultados de busca aguardam leitura e validação da fonte. Não confirmam fatos, vínculos ou capacidade financeira.</p>{(dossier.web_context_hits||[]).length?(dossier.web_context_hits||[]).map((hit:any)=><article className="banner" key={hit.id}><a className="source-link" href={(hit.result_url.startsWith("https://")||hit.result_url.startsWith("http://"))?hit.result_url:undefined} target="_blank" rel="noreferrer">{hit.title||hit.result_domain}</a><p>{hit.snippet}</p><div className="micro">{hit.result_domain} · {hit.validation_status==='PROMOTED'?'Associado à revisão documental':'Pista de descoberta'}</div></article>):<div className="empty">Nenhuma pista web registrada neste núcleo.</div>}</div>}
 </section>
}
