'use client'
import { buildCommercialBrief } from '@/lib/commercial-brief'
import { StatusBadge } from '@/components/StatusBadge'
const labels:Record<string,string>={registration_status:'Situação cadastral',legal_name:'Razão social',location:'Localidade',cnae:'Atividade principal',opening_date:'Início das atividades',legal_nature:'Natureza jurídica',company_size:'Porte cadastral',headquarters_branch:'Matriz / filial',registered_capital:'Capital social declarado',secondary_activities:'Atividades secundárias'}
export function CommercialBrief({dossier,mode="commercial"}:{dossier:Record<string,any>;mode?:"commercial"|"profile"}){
 const brief=buildCommercialBrief(dossier)
 function sources(ids:string[]){return <details><summary className="source-link">Consultar evidências ({ids.length})</summary>{brief.evidence.filter(e=>ids.includes(e.id)).map(e=><div className="banner" key={e.id}><strong>{e.title}</strong><div className="micro">{e.source_label} · consultado em {e.retrieved_at?new Date(e.retrieved_at).toLocaleDateString('pt-BR'):'data não informada'}</div><p>{e.excerpt}</p>{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Abrir documento ↗</a>}</div>)}</details>}
 return <section className="stack" style={{marginBottom:20}} aria-label="Inteligência comercial">
  {mode==='commercial'&&<div className="card"><h2>Preparação para a conversa comercial</h2><p className="muted">{brief.facts.length} fatos com evidência verificada · {brief.events.length} eventos documentados · {brief.topics.length} temas para aprofundar</p><div className="caution">{brief.financialWarning}</div></div>}
  {mode==='profile'&&brief.companies.map(company=>{const facts=brief.facts.filter(f=>f.company_id===company.id);const dimensions=[{label:"Cadastro jurídico",known:facts.some(f=>f.predicate==="legal_name")},{label:"Atividade",known:facts.some(f=>f.predicate==="cnae")},{label:"Dados financeiros",known:facts.some(f=>["revenue","net_income","cash_balance"].includes(f.predicate))}];return <div className="card" key={company.id}><h3>{company.legal_name||company.trade_name}</h3><div className="micro">CNPJ {company.cnpj} · {company.link_status==='VERIFIED'?'Vínculo confirmado':company.link_status==='SUPPORTED'?'Vínculo suportado':'Relação contextual — validar atribuição ao lead'}</div><div className="knowledge-coverage" aria-label="Informações documentadas">{dimensions.map(x=><div className="banner" key={x.label}><strong>{x.label}</strong><div className="micro">{x.known?"Com evidência — abrangência parcial":"Não documentado"}</div></div>)}</div>{facts.length?<dl className="company-facts">{facts.map(f=><div key={f.id}><dt>{labels[f.predicate]||f.predicate.replace(/_/g,' ')}</dt><dd>{f.predicate==='registered_capital'?Number(f.value_text).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):f.value_text||'Não informado'}{f.predicate==='registered_capital'&&<div className="micro">Não representa faturamento, valor de mercado ou patrimônio dos sócios.</div>}</dd></div>)}</dl>:<p className="muted">Cadastro vinculado; a pesquisa deste núcleo ainda precisa produzir fatos com evidência própria.</p>}{sources([...new Set<string>(facts.flatMap(f=>(f.claim_evidence||[]).map((x:any)=>x.evidence_id)))])}</div>})}
  {mode==='commercial'&&<div className="card"><h3>Temas para abordagem</h3><p className="muted">Interpretações e perguntas de descoberta. Cada tema indica o fato que o sustenta e o que ainda precisa ser validado.</p>{brief.topics.length?<div className="split">{brief.topics.map((t,i)=><article className="banner" key={`${t.title}-${i}`}><h4>{t.title}</h4><p><strong>Base documentada:</strong> {t.basis}</p><p><strong>Relevância comercial:</strong> {t.relevance}</p><div className="question">{t.question}</div><p className="micro">{t.caution}</p>{sources(t.evidenceIds)}</article>)}</div>:<div className="empty">Ainda não há base documental suficiente para preparar uma abordagem específica. Inicie a investigação e valide os vínculos.</div>}</div>}
  {mode==='commercial'&&<div className="card"><h3>O que falta para aprofundar</h3>{!brief.hasResearch&&<p>A investigação deste núcleo ainda não foi executada.</p>}{brief.gaps.map((g,i)=><div className="research-step" key={i}><div className="step-num">!</div><div><strong>{g.title}</strong><p>{g.reason}</p>{g.url&&<a className="source-link" href={g.url} target="_blank" rel="noreferrer">Consultar fonte ↗</a>}</div><StatusBadge value={g.status}/></div>)}<p className="muted">Valide com a empresa os documentos financeiros atuais, a estrutura de decisão e os próximos investimentos antes de formular uma proposta.</p></div>}
  {mode==='profile'&&<div className="card"><h3>Pistas para aprofundar</h3><p className="muted">Resultados de busca aguardam leitura e validação da fonte. Não confirmam fatos, vínculos ou capacidade financeira.</p>{(dossier.web_context_hits||[]).length?(dossier.web_context_hits||[]).map((hit:any)=><article className="banner" key={hit.id}><a className="source-link" href={(hit.result_url.startsWith("https://")||hit.result_url.startsWith("http://"))?hit.result_url:undefined} target="_blank" rel="noreferrer">{hit.title||hit.result_domain}</a><p>{hit.snippet}</p><div className="micro">{hit.result_domain} · {hit.validation_status==='PROMOTED'?'Associado à revisão documental':'Pista de descoberta'}</div></article>):<div className="empty">Nenhuma pista web registrada neste núcleo.</div>}</div>}
 </section>
}
