'use client'
import {buildCompanyPassport} from '@/lib/company-passport'
import {EvidenceList} from '@/components/EvidenceList'

export function CompanyPassport({dossier,company}:{dossier:Record<string,any>;company:Record<string,any>}) {
 const p=buildCompanyPassport(dossier,company)
 return <article className="stack passport" aria-label={`Perfil empresarial de ${company.legal_name||company.trade_name}`}>
  <div className="card"><h2>{company.legal_name||company.trade_name}</h2><p className="micro">CNPJ {company.cnpj||'a validar'} · {company.link_status==='VERIFIED'?'Vínculo confirmado':company.link_status==='SUPPORTED'?'Vínculo suportado':'Atribuição ao lead ainda não confirmada'}</p><p className="micro">Última coleta das fontes utilizadas: {p.lastConsulted?new Date(p.lastConsulted).toLocaleString('pt-BR'):'não disponível'}. A data da coleta não garante atualidade do conteúdo.</p><div className="knowledge-coverage">{p.sections.map(s=><a className="banner" href={`#passport-${company.id}-${s.key}`} key={s.key}><strong>{s.title}</strong><div className="micro">{s.items.length?'Com documentação parcial':'Não documentado'}</div></a>)}</div><p className="caution">{p.caution}</p></div>
  {p.sections.map(s=><section className="card" id={`passport-${company.id}-${s.key}`} key={s.key}><h3>{s.title}</h3>{s.items.length?s.items.map(i=><div className="banner" key={i.id}><strong>{i.label}</strong><p>{i.value}</p>{i.date&&<div className="micro">Data ou referência documental: {i.date}</div>}{i.provisional&&<p className="caution">Relação indicativa; exige confirmação.</p>}<details><summary className="source-link">Ver fonte e data ({i.evidenceIds.length})</summary><EvidenceList rows={p.sources.filter(e=>i.evidenceIds.includes(e.id))}/></details></div>):<p className="muted">{s.gap}</p>}{s.key==='decision'&&s.items.length>0&&<p className="muted">Validar quem aprova caixa, crédito e investimentos. O cadastro não determina esses poderes.</p>}{s.key==='financial'&&p.capital.map(i=><div className="caution" key={i.id}>Capital social declarado: {Number.isFinite(Number(i.value))?Number(i.value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):i.value}. Não representa receita, lucro, valor da empresa ou liquidez dos sócios.<details><summary className="source-link">Ver documento cadastral</summary><EvidenceList rows={p.sources.filter(e=>i.evidenceIds.includes(e.id))}/></details></div>)}</section>)}
 </article>
}
