'use client'
import {useState} from 'react'
import {compareIntelligence,IntelligenceSnapshot} from '@/lib/intelligence-history'
export function IntelligenceHistory({rows,busy,readOnly,onCapture}:{rows:any[];busy:boolean;readOnly:boolean;onCapture:()=>void}){
 const [selected,setSelected]=useState('')
 const current=rows[0],previous=rows.find(r=>r.id===selected&&r.id!==current?.id)||rows[1]
 const diff=current&&previous?compareIntelligence(previous.payload as IntelligenceSnapshot,current.payload as IntelligenceSnapshot):null
 const sources=(item:any,snapshot:any)=>item?.evidenceIds?.map((id:string)=>snapshot.payload.sources.find((e:any)=>e.id===id)).filter(Boolean)||[]
 return <section className="stack" aria-label="Histórico da inteligência"><div className="card"><div className="top"><div><h2>O que mudou nas pesquisas</h2><p className="muted">Até 20 registros recentes. O histórico começa na primeira captura; não reconstrói pesquisas anteriores.</p></div><button className="btn secondary" disabled={busy||readOnly} onClick={onCapture}>{busy?'Registrando…':'Registrar estado atual'}</button></div><div className="caution">Uma informação que perdeu suporte não comprova encerramento de sociedade, saída de administrador ou fim de contrato. Os documentos abaixo registram o suporte existente na data da captura.</div></div>
 {!current?<div className="empty">Ainda sem registro histórico. Ao concluir uma pesquisa, o MAX registra o estado documentado automaticamente.</div>:<div className="card"><h3>Captura mais recente · {new Date(current.captured_at).toLocaleString('pt-BR')}</h3>{previous?<><label className="label">Comparar com<select className="select" value={previous.id} onChange={e=>setSelected(e.target.value)}>{rows.slice(1).map(r=><option key={r.id} value={r.id}>{new Date(r.captured_at).toLocaleString('pt-BR')}</option>)}</select></label><p className="muted">{diff?.changes.length} alteração(ões) documentada(s). {diff?.identityChanged?'A avaliação de identidade mudou. ':''}{diff?.sourceCoverageChanged?'O estado das consultas às fontes mudou.':''}</p>{diff?.changes.map((change,i)=><article className="banner" key={i}><strong>{change.type==='ADDED'?'Novo registro':change.type==='CHANGED'?'Conteúdo alterado':'Sem suporte no estado atual'} · {(change.after||change.before)?.label}</strong>{change.before&&<p><b>Antes:</b> {change.before.value}</p>}{change.after&&<p><b>Agora:</b> {change.after.value}</p>}{change.type==='NO_LONGER_SUPPORTED'&&<p className="micro">Revisar as evidências e a cobertura antes de concluir que ocorreu uma mudança empresarial.</p>}<details><summary className="source-link">Documentos nas capturas</summary>{[{item:change.before,snapshot:previous,label:'Antes'},{item:change.after,snapshot:current,label:'Agora'}].flatMap(({item,snapshot,label})=>sources(item,snapshot).map((e:any)=><p key={`${label}:${e.id}`} className="micro">{label} · {e.title} · {e.date||'Data não informada'} {e.url&&<a className="source-link" href={e.url} target="_blank" rel="noreferrer">Abrir documento ↗</a>}</p>))}</details></article>)}{!diff?.changes.length&&<div className="empty">Nenhuma alteração no conteúdo documentado entre estas capturas.</div>}<p className="micro">As lacunas de consulta mais recentes: {current.payload.gaps.map((g:any)=>`${g.source}: ${g.status}`).join(' · ')||'Nenhuma etapa incompleta registrada; isso não garante cobertura integral.'}</p></>:<div className="banner">Primeira referência registrada: {current.payload.items.length} item(ns) documentado(s). Uma nova captura permitirá comparar mudanças.</div>}</div>}
 </section>
}
