'use client'
import type {ReactNode} from 'react'
import {isActiveResearch,researchOutcome,researchSourceUrl,researchStepSummary,type ResearchJob,type ResearchRun} from '@/lib/research-progress'

const labels:Record<string,string>={PENDING:'Aguardando',QUEUED:'Na fila',RUNNING:'Em andamento',RETRY:'Nova tentativa agendada',COMPLETED:'Concluída',PARTIAL:'Parcial',BLOCKED:'Bloqueada',FAILED:'Falhou',SKIPPED:'Não executada',CANCELLED:'Cancelada'}
type Props={leadName:string;job:ResearchJob|null;run:ResearchRun|null;hasJobId:boolean;starting:boolean;readOnly:boolean;error:string;configuration:ReactNode;onStart:()=>void;onRefresh:()=>void;onDismiss:()=>void}
export function ResearchWorkspace({leadName,job,run,hasJobId,starting,readOnly,error,configuration,onStart,onRefresh,onDismiss}:Props){
 const outcome=researchOutcome(job,run),active=isActiveResearch(job),steps=[...(run?.research_steps||[])].sort((a,b)=>a.step_order-b.step_order),counts=researchStepSummary(steps)
 const status=starting?'Iniciando pesquisa':!job?(hasJobId?'Localizando execução':'Preparar pesquisa'):outcome==='waiting_results'?'Carregando resultados':outcome==='partial'?'Finalizada · parcial':labels[job.status]||'Consultando execução'
 const title=starting?'Confirmando o início da pesquisa…':job?.status==='PENDING'?'Sua pesquisa está na fila':job?.status==='RETRY'?'O MAX fará uma nova tentativa':active?'Consultando fontes e organizando evidências':outcome==='waiting_results'?'A pesquisa terminou. Abrindo os resultados…':outcome==='failed'?'A pesquisa encontrou um erro':outcome==='cancelled'?'Esta pesquisa foi cancelada':job?'Resultados disponíveis':'Configure a pesquisa'
 return <section className="research-workspace section" aria-label="Acompanhamento da pesquisa">
  <div className="research-hero card">
   <div className="research-heading"><div><div className="research-eyebrow">PESQUISA MAX · {leadName}</div><h2>{title}</h2></div><span className={`badge ${outcome==='failed'?'bad':active||starting||outcome==='partial'?'pending':'neutral'}`}>{status}</span></div>
   <p className="muted">{starting?'A execução aparecerá assim que a fila confirmar o início.':active?'Você pode continuar usando o MAX. Esta tela acompanha a execução salva e abrirá a visão comercial ao finalizar.':outcome==='waiting_results'?'O MAX está conferindo as evidências da execução concluída antes de abrir o dossiê.':'A pesquisa mantém fatos, pistas e lacunas separados. Resultados parciais também serão apresentados.'}</p>
   <div className="research-stages" aria-label="Fases da execução"><Phase title="Fila" detail={job?'Execução registrada':starting?'Confirmando início':'Aguardando início'} state={job?'done':starting?'current':'pending'}/><Phase title="Consulta às fontes" detail={run?`${counts.settled} de ${counts.total} etapas encerradas`:job?.status==='RETRY'?'Aguardando nova tentativa':job?.status==='PENDING'?'Aguardando processamento':'O plano aparece quando a execução começar'} state={run?(active?'current':['PARTIAL','FAILED','CANCELLED'].includes(run.status)?'issue':'done'):'pending'}/><Phase title="Resultados" detail={outcome==='partial'?'Cobertura parcial':outcome==='completed'?'Documentos disponíveis':outcome==='waiting_results'?'Conferindo execução':['failed','cancelled'].includes(outcome)?'Requer nova pesquisa':'Abertura automática ao finalizar'} state={outcome==='completed'?'done':['partial','failed','cancelled'].includes(outcome)?'issue':outcome==='waiting_results'?'current':'pending'}/></div>
   <div role="status" aria-live="polite" className="research-current">{job?.progress?.message||(!job&&hasJobId?'Buscando o estado salvo desta execução…':!job?'Escolha a estratégia ou inicie com o contexto atual do lead.':'Aguardando atualização da execução.')}</div>
   {job?.updated_at&&<div className="micro">Último estado salvo: {new Date(job.updated_at).toLocaleString('pt-BR')}{error?' · A atualização falhou; este é o último estado conhecido.':''}</div>}
   {job?.status==='RETRY'&&(job.next_attempt_at||job.progress?.next_attempt_at)&&<p className="muted">Próxima tentativa: {new Date(job.next_attempt_at||job.progress?.next_attempt_at).toLocaleString('pt-BR')}. A execução continua na mesma fila.</p>}
   {job?.last_error&&<div className="banner warn section">Última tentativa: {job.last_error}</div>}
   {error&&<div role="alert" className="banner bad section">{error}<div className="actions" style={{marginTop:10}}><button className="btn secondary" onClick={onRefresh}>Atualizar acompanhamento</button></div></div>}
   {['failed','cancelled'].includes(outcome)&&<div className="actions section"><button className="btn" disabled={starting||readOnly} onClick={onStart}>Tentar nova pesquisa</button></div>}
   {!job&&!hasJobId&&!starting&&<div className="research-configuration section">{configuration}<button className="btn" disabled={starting||readOnly} onClick={onStart}>Iniciar pesquisa</button>{readOnly&&<p className="muted">Seu acesso permite acompanhar pesquisas. Para iniciar uma execução, é necessário acesso de edição.</p>}</div>}
   <div className="actions section"><button className="btn secondary" onClick={onDismiss}>{active||starting?'Ver dossiê enquanto pesquisa':'Voltar ao dossiê'}</button><span className="micro">Recarregar esta página retoma o acompanhamento; nenhuma nova pesquisa é criada automaticamente.</span></div>
  </div>
  {run&&<div className="card research-live-steps"><div className="research-heading"><div><h3>Etapas desta pesquisa</h3><div className="muted">{counts.completed} concluída(s) · {counts.partial} parcial(is) · {counts.blocked} bloqueada(s) · {counts.failed} com erro · {counts.skipped} não executada(s)</div></div><span className="badge neutral">{labels[run.status]||run.status}</span></div>{counts.total>0&&<progress aria-label="Etapas encerradas do plano; não mede cobertura de inteligência" value={counts.settled} max={counts.total}/>}{steps.map(step=>{const url=researchSourceUrl(step.action_url);return <div className={`research-step research-live-step ${step.status==='RUNNING'?'is-running':''}`} key={step.id}><div className="step-num">{step.status==='RUNNING'?'↻':step.step_order}</div><div><strong>{step.title}</strong><div className="muted">{step.result_summary||step.error_summary||(step.status==='PENDING'?'Aguardando esta etapa.':'Estado atualizado pela execução.')}</div>{url&&<a className="source-link" href={url} target="_blank" rel="noreferrer">Abrir fonte ↗</a>}</div><span className={`badge ${step.status==='COMPLETED'?'ok':step.status==='FAILED'?'bad':['PARTIAL','BLOCKED','RUNNING'].includes(step.status)?'pending':'neutral'}`}>{labels[step.status]||step.status}</span></div>})}</div>}
 </section>
}
function Phase({title,detail,state}:{title:string;detail:string;state:'done'|'current'|'pending'|'issue'}){return <div className={`research-phase ${state}`}><strong><span aria-hidden="true">{state==='done'?'✓':state==='current'?'↻':state==='issue'?'!':'○'}</span> {title}</strong><div>{detail}</div></div>}
