-- Read-only equivalence and positive/negative regression cases.
-- No database rows or credentials are used. Every value is synthetic.
BEGIN READ ONLY;
SET LOCAL statement_timeout='8s';
WITH fixtures(case_name,payload,expected) AS (VALUES
('cpf_top','{"cpf":null}'::jsonb,true),
('cpf_nested','{"safe":{"cpf":[]}}'::jsonb,true),
('cpf_array','{"safe":[{"other":[{"cpf":"synthetic"}]}]}'::jsonb,true),
('cpf_uppercase','{"CPF":1}'::jsonb,false),
('cpf_prefix','{"prefix_cpf":1}'::jsonb,false),
('cpf_suffix','{"cpf_suffix":1}'::jsonb,false),
('cpf_string_value','{"safe":"{\"cpf\":1}"}'::jsonb,false),
('cpf_string_injection','{"safe":",{ \"cpf\": 1 },["}'::jsonb,false),
('cpf_quoted_key','{"quote\"cpf":1}'::jsonb,false),
('cpf_backslash_key','{"slash\\cpf":1}'::jsonb,false),
('cpf_unicode_key','{"\u0063\u0070\u0066":1}'::jsonb,true),
('cnpj_cpf_top','{"cnpj_cpf":null}'::jsonb,true),
('cnpj_cpf_nested','{"safe":{"cnpj_cpf":[]}}'::jsonb,true),
('cnpj_cpf_array','{"safe":[{"other":[{"cnpj_cpf":"synthetic"}]}]}'::jsonb,true),
('cnpj_cpf_uppercase','{"CNPJ_CPF":1}'::jsonb,false),
('cnpj_cpf_prefix','{"prefix_cnpj_cpf":1}'::jsonb,false),
('cnpj_cpf_suffix','{"cnpj_cpf_suffix":1}'::jsonb,false),
('cnpj_cpf_string_value','{"safe":"{\"cnpj_cpf\":1}"}'::jsonb,false),
('cnpj_cpf_string_injection','{"safe":",{ \"cnpj_cpf\": 1 },["}'::jsonb,false),
('cnpj_cpf_quoted_key','{"quote\"cnpj_cpf":1}'::jsonb,false),
('cnpj_cpf_backslash_key','{"slash\\cnpj_cpf":1}'::jsonb,false),
('cnpj_cpf_unicode_key','{"\u0063\u006e\u0070\u006a\u005f\u0063\u0070\u0066":1}'::jsonb,true),
('cnpj_cpf_partner_top','{"cnpj_cpf_partner":null}'::jsonb,true),
('cnpj_cpf_partner_nested','{"safe":{"cnpj_cpf_partner":[]}}'::jsonb,true),
('cnpj_cpf_partner_array','{"safe":[{"other":[{"cnpj_cpf_partner":"synthetic"}]}]}'::jsonb,true),
('cnpj_cpf_partner_uppercase','{"CNPJ_CPF_PARTNER":1}'::jsonb,false),
('cnpj_cpf_partner_prefix','{"prefix_cnpj_cpf_partner":1}'::jsonb,false),
('cnpj_cpf_partner_suffix','{"cnpj_cpf_partner_suffix":1}'::jsonb,false),
('cnpj_cpf_partner_string_value','{"safe":"{\"cnpj_cpf_partner\":1}"}'::jsonb,false),
('cnpj_cpf_partner_string_injection','{"safe":",{ \"cnpj_cpf_partner\": 1 },["}'::jsonb,false),
('cnpj_cpf_partner_quoted_key','{"quote\"cnpj_cpf_partner":1}'::jsonb,false),
('cnpj_cpf_partner_backslash_key','{"slash\\cnpj_cpf_partner":1}'::jsonb,false),
('cnpj_cpf_partner_unicode_key','{"\u0063\u006e\u0070\u006a\u005f\u0063\u0070\u0066\u005f\u0070\u0061\u0072\u0074\u006e\u0065\u0072":1}'::jsonb,true),
('cnpj_cpf_representative_top','{"cnpj_cpf_representative":null}'::jsonb,true),
('cnpj_cpf_representative_nested','{"safe":{"cnpj_cpf_representative":[]}}'::jsonb,true),
('cnpj_cpf_representative_array','{"safe":[{"other":[{"cnpj_cpf_representative":"synthetic"}]}]}'::jsonb,true),
('cnpj_cpf_representative_uppercase','{"CNPJ_CPF_REPRESENTATIVE":1}'::jsonb,false),
('cnpj_cpf_representative_prefix','{"prefix_cnpj_cpf_representative":1}'::jsonb,false),
('cnpj_cpf_representative_suffix','{"cnpj_cpf_representative_suffix":1}'::jsonb,false),
('cnpj_cpf_representative_string_value','{"safe":"{\"cnpj_cpf_representative\":1}"}'::jsonb,false),
('cnpj_cpf_representative_string_injection','{"safe":",{ \"cnpj_cpf_representative\": 1 },["}'::jsonb,false),
('cnpj_cpf_representative_quoted_key','{"quote\"cnpj_cpf_representative":1}'::jsonb,false),
('cnpj_cpf_representative_backslash_key','{"slash\\cnpj_cpf_representative":1}'::jsonb,false),
('cnpj_cpf_representative_unicode_key','{"\u0063\u006e\u0070\u006a\u005f\u0063\u0070\u0066\u005f\u0072\u0065\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u0076\u0065":1}'::jsonb,true),
('cpf_partner_top','{"cpf_partner":null}'::jsonb,true),
('cpf_partner_nested','{"safe":{"cpf_partner":[]}}'::jsonb,true),
('cpf_partner_array','{"safe":[{"other":[{"cpf_partner":"synthetic"}]}]}'::jsonb,true),
('cpf_partner_uppercase','{"CPF_PARTNER":1}'::jsonb,false),
('cpf_partner_prefix','{"prefix_cpf_partner":1}'::jsonb,false),
('cpf_partner_suffix','{"cpf_partner_suffix":1}'::jsonb,false),
('cpf_partner_string_value','{"safe":"{\"cpf_partner\":1}"}'::jsonb,false),
('cpf_partner_string_injection','{"safe":",{ \"cpf_partner\": 1 },["}'::jsonb,false),
('cpf_partner_quoted_key','{"quote\"cpf_partner":1}'::jsonb,false),
('cpf_partner_backslash_key','{"slash\\cpf_partner":1}'::jsonb,false),
('cpf_partner_unicode_key','{"\u0063\u0070\u0066\u005f\u0070\u0061\u0072\u0074\u006e\u0065\u0072":1}'::jsonb,true),
('cpf_representative_top','{"cpf_representative":null}'::jsonb,true),
('cpf_representative_nested','{"safe":{"cpf_representative":[]}}'::jsonb,true),
('cpf_representative_array','{"safe":[{"other":[{"cpf_representative":"synthetic"}]}]}'::jsonb,true),
('cpf_representative_uppercase','{"CPF_REPRESENTATIVE":1}'::jsonb,false),
('cpf_representative_prefix','{"prefix_cpf_representative":1}'::jsonb,false),
('cpf_representative_suffix','{"cpf_representative_suffix":1}'::jsonb,false),
('cpf_representative_string_value','{"safe":"{\"cpf_representative\":1}"}'::jsonb,false),
('cpf_representative_string_injection','{"safe":",{ \"cpf_representative\": 1 },["}'::jsonb,false),
('cpf_representative_quoted_key','{"quote\"cpf_representative":1}'::jsonb,false),
('cpf_representative_backslash_key','{"slash\\cpf_representative":1}'::jsonb,false),
('cpf_representative_unicode_key','{"\u0063\u0070\u0066\u005f\u0072\u0065\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u0076\u0065":1}'::jsonb,true),
('partner_identifier_top','{"partner_identifier":null}'::jsonb,true),
('partner_identifier_nested','{"safe":{"partner_identifier":[]}}'::jsonb,true),
('partner_identifier_array','{"safe":[{"other":[{"partner_identifier":"synthetic"}]}]}'::jsonb,true),
('partner_identifier_uppercase','{"PARTNER_IDENTIFIER":1}'::jsonb,false),
('partner_identifier_prefix','{"prefix_partner_identifier":1}'::jsonb,false),
('partner_identifier_suffix','{"partner_identifier_suffix":1}'::jsonb,false),
('partner_identifier_string_value','{"safe":"{\"partner_identifier\":1}"}'::jsonb,false),
('partner_identifier_string_injection','{"safe":",{ \"partner_identifier\": 1 },["}'::jsonb,false),
('partner_identifier_quoted_key','{"quote\"partner_identifier":1}'::jsonb,false),
('partner_identifier_backslash_key','{"slash\\partner_identifier":1}'::jsonb,false),
('partner_identifier_unicode_key','{"\u0070\u0061\u0072\u0074\u006e\u0065\u0072\u005f\u0069\u0064\u0065\u006e\u0074\u0069\u0066\u0069\u0065\u0072":1}'::jsonb,true),
('age_top','{"age":null}'::jsonb,true),
('age_nested','{"safe":{"age":[]}}'::jsonb,true),
('age_array','{"safe":[{"other":[{"age":"synthetic"}]}]}'::jsonb,true),
('age_uppercase','{"AGE":1}'::jsonb,false),
('age_prefix','{"prefix_age":1}'::jsonb,false),
('age_suffix','{"age_suffix":1}'::jsonb,false),
('age_string_value','{"safe":"{\"age\":1}"}'::jsonb,false),
('age_string_injection','{"safe":",{ \"age\": 1 },["}'::jsonb,false),
('age_quoted_key','{"quote\"age":1}'::jsonb,false),
('age_backslash_key','{"slash\\age":1}'::jsonb,false),
('age_unicode_key','{"\u0061\u0067\u0065":1}'::jsonb,true),
('age_group_top','{"age_group":null}'::jsonb,true),
('age_group_nested','{"safe":{"age_group":[]}}'::jsonb,true),
('age_group_array','{"safe":[{"other":[{"age_group":"synthetic"}]}]}'::jsonb,true),
('age_group_uppercase','{"AGE_GROUP":1}'::jsonb,false),
('age_group_prefix','{"prefix_age_group":1}'::jsonb,false),
('age_group_suffix','{"age_group_suffix":1}'::jsonb,false),
('age_group_string_value','{"safe":"{\"age_group\":1}"}'::jsonb,false),
('age_group_string_injection','{"safe":",{ \"age_group\": 1 },["}'::jsonb,false),
('age_group_quoted_key','{"quote\"age_group":1}'::jsonb,false),
('age_group_backslash_key','{"slash\\age_group":1}'::jsonb,false),
('age_group_unicode_key','{"\u0061\u0067\u0065\u005f\u0067\u0072\u006f\u0075\u0070":1}'::jsonb,true),
('faixa_etaria_top','{"faixa_etaria":null}'::jsonb,true),
('faixa_etaria_nested','{"safe":{"faixa_etaria":[]}}'::jsonb,true),
('faixa_etaria_array','{"safe":[{"other":[{"faixa_etaria":"synthetic"}]}]}'::jsonb,true),
('faixa_etaria_uppercase','{"FAIXA_ETARIA":1}'::jsonb,false),
('faixa_etaria_prefix','{"prefix_faixa_etaria":1}'::jsonb,false),
('faixa_etaria_suffix','{"faixa_etaria_suffix":1}'::jsonb,false),
('faixa_etaria_string_value','{"safe":"{\"faixa_etaria\":1}"}'::jsonb,false),
('faixa_etaria_string_injection','{"safe":",{ \"faixa_etaria\": 1 },["}'::jsonb,false),
('faixa_etaria_quoted_key','{"quote\"faixa_etaria":1}'::jsonb,false),
('faixa_etaria_backslash_key','{"slash\\faixa_etaria":1}'::jsonb,false),
('faixa_etaria_unicode_key','{"\u0066\u0061\u0069\u0078\u0061\u005f\u0065\u0074\u0061\u0072\u0069\u0061":1}'::jsonb,true),
('address_top','{"address":null}'::jsonb,true),
('address_nested','{"safe":{"address":[]}}'::jsonb,true),
('address_array','{"safe":[{"other":[{"address":"synthetic"}]}]}'::jsonb,true),
('address_uppercase','{"ADDRESS":1}'::jsonb,false),
('address_prefix','{"prefix_address":1}'::jsonb,false),
('address_suffix','{"address_suffix":1}'::jsonb,false),
('address_string_value','{"safe":"{\"address\":1}"}'::jsonb,false),
('address_string_injection','{"safe":",{ \"address\": 1 },["}'::jsonb,false),
('address_quoted_key','{"quote\"address":1}'::jsonb,false),
('address_backslash_key','{"slash\\address":1}'::jsonb,false),
('address_unicode_key','{"\u0061\u0064\u0064\u0072\u0065\u0073\u0073":1}'::jsonb,true),
('personal_address_top','{"personal_address":null}'::jsonb,true),
('personal_address_nested','{"safe":{"personal_address":[]}}'::jsonb,true),
('personal_address_array','{"safe":[{"other":[{"personal_address":"synthetic"}]}]}'::jsonb,true),
('personal_address_uppercase','{"PERSONAL_ADDRESS":1}'::jsonb,false),
('personal_address_prefix','{"prefix_personal_address":1}'::jsonb,false),
('personal_address_suffix','{"personal_address_suffix":1}'::jsonb,false),
('personal_address_string_value','{"safe":"{\"personal_address\":1}"}'::jsonb,false),
('personal_address_string_injection','{"safe":",{ \"personal_address\": 1 },["}'::jsonb,false),
('personal_address_quoted_key','{"quote\"personal_address":1}'::jsonb,false),
('personal_address_backslash_key','{"slash\\personal_address":1}'::jsonb,false),
('personal_address_unicode_key','{"\u0070\u0065\u0072\u0073\u006f\u006e\u0061\u006c\u005f\u0061\u0064\u0064\u0072\u0065\u0073\u0073":1}'::jsonb,true),
('residential_address_top','{"residential_address":null}'::jsonb,true),
('residential_address_nested','{"safe":{"residential_address":[]}}'::jsonb,true),
('residential_address_array','{"safe":[{"other":[{"residential_address":"synthetic"}]}]}'::jsonb,true),
('residential_address_uppercase','{"RESIDENTIAL_ADDRESS":1}'::jsonb,false),
('residential_address_prefix','{"prefix_residential_address":1}'::jsonb,false),
('residential_address_suffix','{"residential_address_suffix":1}'::jsonb,false),
('residential_address_string_value','{"safe":"{\"residential_address\":1}"}'::jsonb,false),
('residential_address_string_injection','{"safe":",{ \"residential_address\": 1 },["}'::jsonb,false),
('residential_address_quoted_key','{"quote\"residential_address":1}'::jsonb,false),
('residential_address_backslash_key','{"slash\\residential_address":1}'::jsonb,false),
('residential_address_unicode_key','{"\u0072\u0065\u0073\u0069\u0064\u0065\u006e\u0074\u0069\u0061\u006c\u005f\u0061\u0064\u0064\u0072\u0065\u0073\u0073":1}'::jsonb,true),
('sql_null',null::jsonb,false),
('json_null','null'::jsonb,false),
('scalar_number','123'::jsonb,false),
('scalar_string','"\"cpf\": 1"'::jsonb,false),
('empty_object','{}'::jsonb,false),
('empty_array','[]'::jsonb,false)
), checks AS (
 SELECT case_name,expected,
  coalesce(jsonb_path_exists(payload,'$.** ? (@.type() == "object").keyvalue() ? (
          @.key == "cpf"
          || @.key == "cnpj_cpf"
          || @.key == "cnpj_cpf_partner"
          || @.key == "cnpj_cpf_representative"
          || @.key == "cpf_partner"
          || @.key == "cpf_representative"
          || @.key == "partner_identifier"
          || @.key == "age"
          || @.key == "age_group"
          || @.key == "faixa_etaria"
          || @.key == "address"
          || @.key == "personal_address"
          || @.key == "residential_address"
        )'),false) AS old_detected,
  coalesce(payload::text ~ '(^|[,{])[[:space:]]*"(cpf|cnpj_cpf|cnpj_cpf_partner|cnpj_cpf_representative|cpf_partner|cpf_representative|partner_identifier|age|age_group|faixa_etaria|address|personal_address|residential_address)"[[:space:]]*:',false) AS new_detected
 FROM fixtures
)
SELECT count(*) AS cases,
 count(*) FILTER(WHERE old_detected IS DISTINCT FROM new_detected) AS semantic_differences,
 count(*) FILTER(WHERE old_detected IS DISTINCT FROM expected OR new_detected IS DISTINCT FROM expected) AS failed_expectations
FROM checks;
ROLLBACK;
